### ISSUE TITLE
Request Create new row in table (CURL/JSON/RAILS)

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/full-stack-project#110]
- the AJAX or curl request that you’re using

``` bash
#!/bin/bash

TOKEN='59afd6452274275c49b24bdcd53e1a99'
ID='7'

BASE_URL="localhost:3000"
URL="${BASE_URL}/pets"

json() {
  CONTENT_TYPE="application/json"

  curl ${URL} \
  --include \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --header "Authorization: Token token=${TOKEN}" \
  --data  "{
      \"animal\": \"DEADkitten\",
      \"name\": \"WTF\",
      \"age\": 99
    }"
}

json

echo
```
- the output of `rake routes`

``` bash
 Prefix Verb   URI Pattern                    Controller#Action
   pets GET    /pets(.:format)                pets#index
        POST   /pets(.:format)                pets#create
    pet GET    /pets/:id(.:format)            pets#show
        PATCH  /pets/:id(.:format)            pets#update
        PUT    /pets/:id(.:format)            pets#update
        DELETE /pets/:id(.:format)            pets#destroy
sign_up POST   /sign-up(.:format)             users#signup
sign_in POST   /sign-in(.:format)             users#signin
        DELETE /sign-out/:id(.:format)        users#signout
        PATCH  /change-password/:id(.:format) users#changepw
  users GET    /users(.:format)               users#index
   user GET    /users/:id(.:format)           users#show

```
- the content of the error message you’re getting
  (CURL ERROR)

``` bash

HTTP/1.1 400 Bad Request 
Content-Type: text/html; charset=utf-8
Content-Length: 85820
X-Request-Id: c8f5c59d-6d95-458d-b72f-dd12c5a13def
X-Runtime: 0.101027
Server: WEBrick/1.3.1 (Ruby/2.2.4/2015-12-16)
Date: Thu, 25 Feb 2016 15:08:54 GMT
Connection: Keep-Alive

```

``` bash
Started POST "/pets" for ::1 at 2016-02-25 10:08:54 -0500
Processing by PetsController#create as */*
  Parameters: {"animal"=>"DEADkitten", "name"=>"WTF", "age"=>99}
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: pet):
  app/controllers/pets_controller.rb:57:in `pet_params'
  app/controllers/pets_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.2ms)
  Rendered /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (38.7ms)
```

**Comment by GA-MEB** [comment]
> ```
> ActionController::ParameterMissing (param is missing or the value is empty: pet):
>   app/controllers/pets_controller.rb:57:in `pet_params'
>   app/controllers/pets_controller.rb:21:in `create'
> ```

This suggests an error with your controller. Can you paste the content of your `pet_params` strong params method?

**Comment by gaand** [comment]
You need to wrap that data in an object with the single key "pet".  This is the "root" key.

See provided scripts for auth, etc.

**Comment by jrhorn424** [comment]
For completeness:

``` diff
  --data  "{
+   \"pet\": {
      \"animal\": \"DEADkitten\",
      \"name\": \"WTF\",
      \"age\": 99
+   }
  }"
```
