### ISSUE TITLE
Rails: PATCH request syntax

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/full-stack-project#140]
I don't think I have a good example or template for making a PATCH request to update database information. Here is my curl request:

```
curl --include --request PATCH http://localhost:3000/doses/2 \
  --header "Authorization: Token token={correct token, not an issue}" \
  --header "Content-Type: application/json" \
  --data '{
      "size": "15" 
  }'
```

And here is the error that gets returned on the server:

![image](https://cloud.githubusercontent.com/assets/8867447/13366758/5fd00ae2-dcab-11e5-8281-880c2e8c2439.png)

I have tried mixing up the syntax on the --data attribute of the curl request a number of times, to no avail. How do I do this?

**Comment by gaand** [comment]
Please post copy-and-pasted text in code blocks.

Stoing params requires that the data you send have an appropriate root key.

**Comment by MFBrewster** [comment]
Here is my params definition from the controller:

``` rb
def dose_strong_params
      params.require(:doses).permit(:label, :size, :time, :user_id, :medicine_id)
    end

    def dose_params
      params[:doses]
    end
```

I'm using dose_params for my update method, because I want to be able to pass in varying attributes. I tried changing my curl request to the following:

``` sh
curl --include --request PATCH http://localhost:3000/doses/2 \
  --header "Authorization: Token token=ab3a38dbf20b6ae047da21e930d37cbf" \
  --header "Content-Type: application/json" \
  --data '{
      "doses": {
        "size": "15"
      }
  }'
```

...and it returns a different error: 

![image](https://cloud.githubusercontent.com/assets/8867447/13367010/1bf0c0a8-dcad-11e5-8deb-c8b40ee8c299.png)

**Comment by jrhorn424** [comment]
`"doses": {` there's a typo here. Thing about whether you're editing a collection or not.

**Comment by gaand** [comment]
More text, fewer images :-).

Please post the update method.

**Comment by MFBrewster** [comment]
``` rb
  def update
    @dose = Dose.find(params[:id])

    if @dose.update(dose_params)
      head :no_content
    else
      render json: @dose.errors, status: :unprocessable_entity
    end
  end
```

```
Started PATCH "/doses/2" for ::1 at 2016-02-26 17:20:36 -0500
Processing by DosesController#update as */*
  Parameters: {"dose"=>{"size"=>"15"}, "id"=>"2"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "ab3a38dbf20b6ae047da21e930d37cbf"]]
  Dose Load (0.3ms)  SELECT  "doses".* FROM "doses" WHERE "doses"."id" = $1 LIMIT 1  [["id", 2]]
  CACHE (0.0ms)  SELECT  "doses".* FROM "doses" WHERE "doses"."id" = $1 LIMIT 1  [["id", "2"]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.0ms)

ArgumentError (When assigning attributes, you must pass a hash as an argument.):
  app/controllers/doses_controller.rb:37:in `update'
```

**Comment by MFBrewster** [comment]
```
Started PATCH "/doses/2" for ::1 at 2016-02-26 17:13:57 -0500
Processing by DosesController#update as */*
  Parameters: {"doses"=>{"size"=>"15"}, "id"=>"2"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "ab3a38dbf20b6ae047da21e930d37cbf"]]
  Dose Load (0.3ms)  SELECT  "doses".* FROM "doses" WHERE "doses"."id" = $1 LIMIT 1  [["id", 2]]
  CACHE (0.0ms)  SELECT  "doses".* FROM "doses" WHERE "doses"."id" = $1 LIMIT 1  [["id", "2"]]
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 58ms (ActiveRecord: 7.9ms)

ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  app/controllers/doses_controller.rb:37:in `update'
```

**Comment by gaand** [comment]
You have to use the require permit syntax for parameters other than `id` or passed in the url following a `?`.

**Comment by MFBrewster** [comment]
That worked!
