### ISSUE TITLE
Sign Up/Sign In troubles

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/full-stack-project#163]
When I try to sign up I get this error in the browser:

```
POST http://localhost:3000/sign-up send @ jquery.js:9175jQuery.extend.ajax @ jquery.js:8656signUp @ index.js:56jQuery.event.dispatch @ jquery.js:4732elemData.handle @ jquery.js:4544
(index):1 XMLHttpRequest cannot load http://localhost:3000/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
index.js:66 Object {readyState: 0, status: 0, statusText: "error"}
```

and this error in the console:

```
Started POST "/sign-up" for 127.0.0.1 at 2016-02-29 13:38:09 -0500
Processing by UsersController#signup as */*
Completed 400 Bad Request in 24ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/users_controller.rb:63:in `user_creds'
  app/controllers/users_controller.rb:7:in `signup'
```

I looked in the users control, but assumed we arn't suppose to edit considering it was made in the template. I'm not sure what's causing this error.

**Comment by RealWeeks** [comment]
can you post your ajax request?

**Comment by jdamiron** [comment]
```
let signUp = function(event) {
  event.preventDefault();
  let submtData = new FormData(event.target);
  $.ajax({
    url: myApp.baseUrl + '/sign-up',
    type: 'POST',
    contentType: false,
    processData: false,
    data: submtData
  }).done(function(data) {
    console.log(data);

  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};

let registrations = function() {
  $('.sign-up-button').on('click', signUp);
};
```

Is formData the issue here?

**Comment by gaand** [comment]
This

```
ActionController::ParameterMissing (param is missing or the value is empty: credentials)
```

is the problem.

**Comment by jdamiron** [comment]
@gaand is it not grabbing the data/credentials being entered in the input fields?

**Comment by gaand** [comment]
The `event.target` of a click handler is the button.

**Comment by gaand** [comment]
The `event.target` of a submit handler is the form.

**Comment by jdamiron** [comment]
@gaand oh okay I see, I changed click to submit which no longer causes an error. Instead the button is causing the page to refresh it seems like rather than doing the action. Is my ajax request incorrect?

**Comment by gaand** [comment]
What's the url after that?

**Comment by jdamiron** [comment]
@gaand if you are referring to my address bar after the click, it is localhost:8080/?, the url in the ajax request is url: myApp.baseUrl + '/sign-in',

**Comment by RealWeeks** [comment]
paste in the new ajax request, did you remember to preventDefault in the new one as well?

**Comment by jdamiron** [comment]
I didn't change the ajax request, only the button handler.

```
let signIn = function(event) {
  event.preventDefault();
  let data = new FormData(event.target);
  $.ajax({
    url: myApp.baseUrl + '/sign-in',
    type: 'POST',
    contentType: false,
    processData: false,
    data: data
  }).done(function(data) {
    console.log(data);
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};

let signInHandler = function() {
  $('.sign-in-button').on('submit', signIn);
};
```

I changed 'click' to 'submit'.

**Comment by RealWeeks** [comment]
look at the code examples of how to use on: http://api.jquery.com/on/

many of your classmates had the same issue. If after looking at examples and reading docs ask your classmates for help.  I know that Kevin had a similar issue earlier.

**Comment by gaand** [comment]
Is the form for sign up uniquely identified in the html?

**Comment by jdamiron** [comment]
Yes it is, I believe a problem could have been using single quotes around submit rather than double or not invoking the functions on the handlers. After changing those I now recieve the error:

```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined
```

**Comment by RealWeeks** [comment]
Think, what is causing that?  What is event when it is called?  What is the order of operations you currently have?

edit: what functions know about event?

**Comment by jdamiron** [comment]
event is undefined, I'm not sure where it is suppose to be defined.

**Comment by RealWeeks** [comment]
Which function has an event?

**Comment by jdamiron** [comment]
invoking signIn(), on the submit handler caused the error, I took it off but when the button is clicked I still get a page refresh, not a fail or pass.

**Comment by jdamiron** [comment]
sign up and sign in

**Comment by jrhorn424** [comment]
@J-Weeks Was this resolved?

@jdamiron Please add notes about what you discussed, and also close the issue once it's resolved. Thanks!

**Comment by RealWeeks** [comment]
@jrhorn424 resolved, @jdamiron is writing the code now and will close with a description when done.

**Comment by jdamiron** [comment]
I tried to use bootstrap but I'm still having problems.

**Comment by jdamiron** [comment]
Using these modals:

```
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModalLabel">Sign Up Here!</h4>
                      </div>
                      <div class="modal-body">
                        <form class="sign-up-form">
                          <div class="form-group">
                            <label for="credentials[email]" class="control-label">Email:</label>
                            <input type="email" class="form-control" id="email-name">
                          </div>
                          <div class="form-group">
                            <label for="credentials[password]" class="control-label">Password:</label>
                            <input type="password" class="form-control" id="password-name">
                          </div>

                        </form>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary sign-up-button">Sign Up</button>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="modal fade mode-backdrop" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModalLabel">Sign In Here!</h4>
                      </div>
                      <div class="modal-body">
                        <form class="sign-in-form">
                          <div class="form-group">
                            <label for="credentials[email]" class="control-label">Email:</label>
                            <input type="email" class="form-control" id="email-name">
                          </div>
                          <div class="form-group">
                            <label for="credentials[password]" class="control-label">Password:</label>
                            <input type="password" class="form-control" id="password-name">
                          </div>
                        </form>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary sign-in-button">Sign In</button>
                      </div>
                    </div>
                  </div>
                </div>
```

I can't get the event handlers to trigger the sign up or sign in functions. I tried targeting the form and using a submit action but nothing happens when I click the button in the modal.

**Comment by RealWeeks** [comment]
paste in the handlers please

**Comment by jdamiron** [comment]
Sign up and handler:

```
let signUp = function(event) {
  debugger;
  let submtData = new FormData(event.target);
  $.ajax({
    url: myApp.baseUrl + '/sign-up',
    type: 'POST',
    contentType: false,
    processData: false,
    data: submtData
  }).done(function(data) {
    console.log(data);
    console.log("Successfully signed up!");
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};

let registrations = function() {
  $('.sign-up-form').on("submit", function(event) {
    event.preventDefault();
    signUp(event);
  });
}
```

Sign In and handler:

```
let signIn = function(event) {
  let data = new FormData(event.target);
  $.ajax({
    url: myApp.baseUrl + '/sign-in',
    type: 'POST',
    contentType: false,
    processData: false,
    data: data
  }).done(function(data) {
    console.log(data);
    $('.sign-in-button').hide();
    $('.sign-up-button').hide();
  }).fail(function(jqxhr) {
    console.error(jqxhr);
  });
};

let signInHandler = function() {
  $('.sign-in-form').on("submit", function(event) {
    event.preventDefault();
    signIn(event);
  });
};
```

**Comment by RealWeeks** [comment]
Someone correct me if I'm wrong but the submit button has to be in a form group

**Comment by RealWeeks** [comment]
Read your HTML carefully from the tic-tac-toe project and compare it to this...

**Comment by jrhorn424** [comment]
Is this about your original error or is it something different now @jdamiron? It's difficult for me to follow and render assistance without knowing the context of the error you're getting.

**Comment by jdamiron** [comment]
The issue was the same, it is now resolved. The buttons needed to be inside the form. Also, name = credentials[email] and credentials[password], should have be in input and I had it inside the input for tags. Both of those fixed the issues.
