### ISSUE TITLE
(RAILS) GET /user Fails but GET /users Pass.

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/full-stack-project#165]
``` bash
Started GET "/user" for ::1 at 2016-02-29 14:24:42 -0500
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"

ActionController::RoutingError (No route matches [GET] "/user"):
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Sorry don't know how to fold code on here.

``` bash
rake routes

  Prefix Verb   URI Pattern                    Controller#Action
    items GET    /items(.:format)               items#index
     item GET    /items/:id(.:format)           items#show
    lists GET    /lists(.:format)               lists#index
          POST   /lists(.:format)               lists#create
     list GET    /lists/:id(.:format)           lists#show
          PATCH  /lists/:id(.:format)           lists#update
          PUT    /lists/:id(.:format)           lists#update
          DELETE /lists/:id(.:format)           lists#destroy
userlists GET    /userlists(.:format)           lists#user_lists
  sign_up POST   /sign-up(.:format)             users#signup
  sign_in POST   /sign-in(.:format)             users#signin
          DELETE /sign-out/:id(.:format)        users#signout
          PATCH  /change-password/:id(.:format) users#changepw
    users GET    /users(.:format)               users#index
     user GET    /users/:id(.:format)           users#show
```

**Comment by gaand** [comment]
Run `rake routes`

Is there a route with the path `/user`?

**Comment by RealWeeks** [comment]
@erdesi90562 please paste in raked routes

**Comment by gaand** [comment]
So, what does the output of that command tell you about routes involving the users controller?

**Comment by edesilets** [comment]
It tells me that the actions of  signup, signing, signout, changepw, index, and show actions are associated  with user.

and I TOTALY MISSED THE FACT THAT IT DOESN'T EXIST!

**Comment by RealWeeks** [comment]
`[GET] "/user"`
vs

`users GET    /users(.:format)`
