### ISSUE TITLE
(CURL) Post Request Failing. (unknown JSON structure)

### ISSUE THREAD

**Issue by edesilets** [ga-wdi-boston/full-stack-project#176]
Server Error....

``` bash
Started POST "/items" for ::1 at 2016-02-29 19:09:05 -0500
Processing by ItemsController#create as */*
  Parameters: {"item"=>[{"todo"=>"Toilet Paper", "list"=>{"category"=>"Party Gifts", "user_id"=>3}}]}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "951473cfb9adf638cb12eb994c2679e3"]]
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.2ms)

NoMethodError (undefined method `permit' for #<Array:0x007f80be93fdf0>):
  app/controllers/items_controller.rb:58:in `item_params'
  app/controllers/items_controller.rb:22:in `create'
```

Curl Request....

``` bash
#!/bin/bash
TOKEN='951473cfb9adf638cb12eb994c2679e3'
URL='http://localhost:3000'
#URL="http://httpbin.org/post"
#   POST   /lists(.:format)   lists#create
echo '-----------------------------------------'
curl ${URL}/items \
  --silent \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=${TOKEN}"\
  --data '{
    "item": [
      {
        "todo": "Toilet Paper",
        "list": {
          "category": "Party Gifts",
          "user_id": 3
        }
      }
    ]
  }' | jsonlint
  # bcat -h
  # head -n 20
  #/Users/erdesi90562/wdi/projects/toDo/backend/tmp/junk/erro.html

# --silent
echo
echo '-----------------------------------------'
echo
```

**I am out of educated guesses. I am trying to patch to items.**

Sample of JSON received from from GET /items routes. ( I hope this is helpful.)

``` bash
{
  "items": [
    {
      "id": 1,
      "todo": "Toilet Paper",
      "list": {
        "id": 1,
        "category": "Home Supplies",
        "created_at": "2011-11-11T00:00:00.000Z",
        "updated_at": "2011-11-11T00:00:00.000Z",
        "user_id": 1
      }
    },
    {
      "id": 2,
      "todo": "Dog Food",
      "list": {
        "id": 1,
        "category": "Home Supplies",
        "created_at": "2011-11-11T00:00:00.000Z",
        "updated_at": "2011-11-11T00:00:00.000Z",
        "user_id": 1
      }

```

**Comment by jrhorn424** [comment]
This error message:

```
NoMethodError (undefined method `permit' for #<Array:0x007f80be93fdf0>):
  app/controllers/items_controller.rb:58:in `item_params'
```

Indicates we need to look at the items_controller. Can you paste it?

**Comment by edesilets** [comment]
Yes Sir,
Items controller.

``` ruby
# change to ProtectedController ApplicationController
class ItemsController < ProtectedController
  before_action :set_item, only: [:show, :update, :destroy]

  def index
    @items = Item.all

    render json: @items
  end

  def show
    render json: @item
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      render json: @item, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      head :no_content
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy

    head :no_content
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:todo, :list)
    end
end
```

**Comment by jrhorn424** [comment]
If you're assigning an array to the root:

``` diff
{
-    "item": [
+    "items": [
      {
        "todo": "Toilet Paper",
        "list": {
          "category": "Party Gifts",
          "user_id": 3
        }
      }
    ]
  }
```

If it's just a single object instead of a collection:

``` diff
{
-    "item": [
-      {
+    "item":  {
        "todo": "Toilet Paper",
        "list": {
          "category": "Party Gifts",
          "user_id": 3
        }
      }
-    ]
  }
```

You probably want the second example.

**Comment by jrhorn424** [comment]
@erdesi90562 Did this work?

**Comment by edesilets** [comment]
Yes it did. Thank you.
