### ISSUE TITLE
Heroku not registering sign in or sign up

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/full-stack-project#202]
```
XMLHttpRequest cannot load https://git.heroku.com/dumplepuff.git/sign-up. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 401.
```

**Comment by dumplingpuff** [comment]
I am really bad at reading this thing but this is what I suspect was the error.

```
2016-03-02T02:59:22.009241+00:00 heroku[api]: Deploy 8aaa724 by jason.liang2012@gmail.com
2016-03-02T02:59:22.009241+00:00 heroku[api]: Release v7 created by jason.liang2012@gmail.com
2016-03-02T02:59:22.203740+00:00 heroku[slug-compiler]: Slug compilation started
2016-03-02T02:59:22.203745+00:00 heroku[slug-compiler]: Slug compilation finished
2016-03-02T03:00:14.827584+00:00 heroku[api]: Deploy ea189f4 by jason.liang2012@gmail.com
2016-03-02T03:00:14.827584+00:00 heroku[api]: Release v8 created by jason.liang2012@gmail.com
2016-03-02T03:00:14.974917+00:00 heroku[slug-compiler]: Slug compilation started
2016-03-02T03:00:14.974926+00:00 heroku[slug-compiler]: Slug compilation finished
```

**Comment by dumplingpuff** [comment]
Here is the real issue from Heroku logs

```
2016-03-02T03:20:32.962997+00:00 app[web.1]: Completed 500 Internal Server Error in 85ms (ActiveRecord: 6.5ms)
2016-03-02T03:20:32.963763+00:00 app[web.1]: 
2016-03-02T03:20:32.963770+00:00 app[web.1]: NoMethodError (undefined method `admin' for #<User:0x007f003b044ba0>):
2016-03-02T03:20:32.963771+00:00 app[web.1]:   app/controllers/users_controller.rb:9:in `signup'
```

**Comment by jrhorn424** [comment]
> app/controllers/users_controller.rb:9:in `signup'

Need to see the controller to diagnose.

**Comment by RealWeeks** [comment]
Serializer error

**Comment by RealWeeks** [comment]
My computer is auto closing the issue for some reason

**Comment by dumplingpuff** [comment]
Solved that issue, working another error with my post I think I know what it is.  Will let you know if it is not resolved.

**Comment by dumplingpuff** [comment]
It was serializer again closing issue.
