### ISSUE TITLE
Type mismatch when I push food onto meal.meal_items

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#217]
Here is what I'm typing/geting in rails c

``` bash
[1] pry(main)> food = Food.last
  Food Load (1.0ms)  SELECT  "foods".* FROM "foods"  ORDER BY "foods"."id" DESC LIMIT 1
=> #<Food:0x007fea06d43148
 id: 8789,
 desc: "TURTLE,GREEN,RAW",
 calories: 89,
 grams_per_serving: 85,
 fat_sat: 0.127,
 fat_mono: 0.088,
 fat_poly: 0.17,
 carbs: 0.0,
 sugar: 0.0,
 protein: 19.8,
 fiber: 0.0,
 sodium: 68,
 choles: 50,
 created_at: Thu, 28 Apr 2016 15:05:15 UTC +00:00,
 updated_at: Thu, 28 Apr 2016 15:05:15 UTC +00:00>
[2] pry(main)> meal = Meal.new
=> #<Meal:0x007fea02ebb330 id: nil, type: nil, created_at: nil, updated_at: nil, user_id: nil>
[3] pry(main)> meal.meal_items
=> []
[4] pry(main)> meal.meal_items << food
ActiveRecord::AssociationTypeMismatch: MealItem(#70321522989240) expected, got Food(#70321522656180)
from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/associations/association.rb:218:in `raise_on_type_mismatch!'
[5] pry(main)> 
```

and here are my models

``` bash
class Meal < ActiveRecord::Base
  belongs_to :user, inverse_of: :meal
  has_many :meal_items
  has_many :foods, through: :meal_items
end

class MealItem < ActiveRecord::Base
  belongs_to :foods, inverse_of: :meal_items
  belongs_to :meals, inverse_of: :meal_items
end

class Food < ActiveRecord::Base
  has_many :meal_items
  has_many :meals, through: :meal_items
end
```

**Comment by RealWeeks** [comment]
post your erd so i can visualize your data structure

**Comment by RealWeeks** [comment]
Can I see your schema. I want to make sure all your tables are properly connected

**Comment by RDegnen** [comment]
check the pluralization of the `belongs_to :<model>`

**Comment by louarnos** [comment]
```
ActiveRecord::Schema.define(version: 20160428150154) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "examples", force: :cascade do |t|
    t.text     "text",       null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "examples", ["user_id"], name: "index_examples_on_user_id", using: :btree

  create_table "foods", force: :cascade do |t|
    t.string   "desc"
    t.integer  "calories"
    t.integer  "grams_per_serving"
    t.float    "fat_sat"
    t.float    "fat_mono"
    t.float    "fat_poly"
    t.float    "carbs"
    t.float    "sugar"
    t.float    "protein"
    t.float    "fiber"
    t.integer  "sodium"
    t.integer  "choles"
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
  end

  create_table "meal_items", force: :cascade do |t|
    t.integer  "serv_qty"
    t.datetime "created_at",       null: false
    t.datetime "updated_at",       null: false
    t.integer  "food_for_meal_id"
    t.integer  "user_meal_id"
  end

  add_index "meal_items", ["food_for_meal_id"], name: "index_meal_items_on_food_for_meal_id", using: :btree
  add_index "meal_items", ["user_meal_id"], name: "index_meal_items_on_user_meal_id", using: :btree

  create_table "meals", force: :cascade do |t|
    t.string   "type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end

  add_index "meals", ["user_id"], name: "index_meals_on_user_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["token"], name: "index_users_on_token", unique: true, using: :btree

  add_foreign_key "examples", "users"
  add_foreign_key "meal_items", "foods", column: "food_for_meal_id"
  add_foreign_key "meal_items", "meals", column: "user_meal_id"
  add_foreign_key "meals", "users"
end
```

**Comment by louarnos** [comment]
I had this ross:

```
class MealItem < ActiveRecord::Base
  belongs_to :food, inverse_of: :meal_items
  belongs_to :meal, inverse_of: :meal_items
end
```

 and changed it to see if it would help. It didn't make a difference.

**Comment by RDegnen** [comment]
ah I think I know, try pushing to `meal.foods` instead of `meal.meal_items` 
http://api.rubyonrails.org/classes/ActiveRecord/AssociationTypeMismatch.html

**Comment by louarnos** [comment]
That gives me 

``` bash
[7] pry(main)> meal.foods<<food
ActiveRecord::UnknownAttributeError: unknown attribute 'meal_id' for MealItem.
from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-4.2.6/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
[8] pry(main)> 
```
