### ISSUE TITLE
Curl request testing

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#226]
Curl requests that were working for me this morning afternoon aren't currently despite me only having edited the back end in ways that shouldn't affect functionality (adding scripts, starting to seed data).  The server error I'm getting is

```
Started GET "/climbs" for ::1 at 2016-04-28 16:13:22 -0400

ActionController::RoutingError (uninitialized constant ClimbsController):
```

the curl request I'm using atm is

```
curl --include --request GET http://localhost:3000/climbs
```

my climbs controller is 

```
class ClimbsController < ApplicationController
  before_action :set_climb, only: [:update, :destroy]

  # GET /climbs
  # GET /climbs.json
  def index
    @climbs = Climb.all

    render json: @climbs
  end

  # GET /climbs/1
  # GET /climbs/1.json
  def show
    render json: @climb
  end

  # POST /climbs
  # POST /climbs.json
  def create
    @climb = Climb.new(climb_params)

    if @climb.save
      render json: @climb, status: :created, location: @climb_params
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /climbs/1
  # PATCH/PUT /climbs/1.json
  def update
    @climb = Climb.find(params[:id])

    if @climb.update(climb_params)
      head :no_content
    else
      render json: @climb.errors, status: :unprocessable_entity
    end
  end

  # DELETE /climbs/1
  # DELETE /climbs/1.json
  def destroy
    @climb.destroy

    head :no_content
  end

  private

  def set_climb
    @climb = Climb.find(params[:id])
  end

  def climb_params
    params.require(:climbs).permit(:route_type, :route_grade,
                                   :hold_type_of_fall, :fall_notes)
  end
end
```

**Comment by GA-MEB** [comment]
@Michael
What's the path to your ClimbsController?

**Comment by MichaelB167** [comment]
@MattB-GA-Boston 
app/controllers/climbs_controller.rb

**Comment by laurenfazah** [comment]
Is there an error from the GET request being shown in the window `rails server` is running in?

**Comment by MichaelB167** [comment]
that's the error i initially posted, the whole thing is:

```
Started GET "/climbs" for ::1 at 2016-04-28 16:26:17 -0400

ActionController::RoutingError (uninitialized constant ClimbsController):
  activesupport (4.2.6) lib/active_support/inflector/methods.rb:261:in `const_get'
  activesupport (4.2.6) lib/active_support/inflector/methods.rb:261:in `block in constantize'
  activesupport (4.2.6) lib/active_support/inflector/methods.rb:259:in `each'
  activesupport (4.2.6) lib/active_support/inflector/methods.rb:259:in `inject'
  activesupport (4.2.6) lib/active_support/inflector/methods.rb:259:in `constantize'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:60:in `controller'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:39:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_table.html.erb (0.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (29.6ms)
```

**Comment by MichaelB167** [comment]
the console error was this, followed by a ton of html

```
HTTP/1.1 404 Not Found 
Content-Type: text/html; charset=utf-8
Content-Length: 24684
X-Request-Id: 3b4ef28d-4c56-47e1-ae47-0487084462b8
X-Runtime: 0.067825
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Thu, 28 Apr 2016 20:13:22 GMT
Connection: Keep-Alive
```

**Comment by GA-MEB** [comment]
@MichaelB167 What's the output from `rake routes`?

**Comment by MichaelB167** [comment]
@MattB-GA-Boston 

```
~/wdi/projects/climb-hard-app/climb-hard-back-end (testing)$ rake routes
  Prefix Verb   URI Pattern                    Controller#Action
examples GET    /examples(.:format)            examples#index
         POST   /examples(.:format)            examples#create
 example GET    /examples/:id(.:format)        examples#show
         PATCH  /examples/:id(.:format)        examples#update
         PUT    /examples/:id(.:format)        examples#update
         DELETE /examples/:id(.:format)        examples#destroy
    gyms GET    /gyms(.:format)                gyms#index
         POST   /gyms(.:format)                gyms#create
     gym GET    /gyms/:id(.:format)            gyms#show
         PATCH  /gyms/:id(.:format)            gyms#update
         PUT    /gyms/:id(.:format)            gyms#update
         DELETE /gyms/:id(.:format)            gyms#destroy
  climbs GET    /climbs(.:format)              climbs#index
         POST   /climbs(.:format)              climbs#create
   climb GET    /climbs/:id(.:format)          climbs#show
         PATCH  /climbs/:id(.:format)          climbs#update
         PUT    /climbs/:id(.:format)          climbs#update
         DELETE /climbs/:id(.:format)          climbs#destroy
 sign_up POST   /sign-up(.:format)             users#signup
 sign_in POST   /sign-in(.:format)             users#signin
         DELETE /sign-out/:id(.:format)        users#signout
         PATCH  /change-password/:id(.:format) users#changepw
   users GET    /users(.:format)               users#index
    user GET    /users/:id(.:format)           users#show
```

**Comment by GA-MEB** [comment]
@MichaelB167 
Come over here and I'll take a look.

**Comment by MichaelB167** [comment]
restarting rails server fixed it, thanks Matt.
