### ISSUE TITLE
HTTP Token: Access Denied on Change Password CURL Request

### ISSUE THREAD

**Issue by Jcornmanhomonoff** [ga-wdi-boston/full-stack-project#240]
Having difficulty testing my sign-out and change password. When I run a curl request for sign up it comes back as 201 Created and sign-in is 200 ok. My Change password and sign out come back as HTML.

``` ruby
class DrinksController < ProtectedController
  before_action :set_drink, only: [:show, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all

    render json: @drinks
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
    render json: @drink
  end

  # POST /drinks
  # POST /drinks.json
  # Only the user can make a drink
  def create
    @drink = current_user.drinks.build(drink_params)

    if @drink.save
      render json: @drink, status: :created, location: @drink
    else
      render json: @drink.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    @drink = Drink.find(params[:id])

    if @drink.update(drink_params)
      head :no_content
    else
      render json: @drink.errors, status: :unprocessable_entity
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy

    head :no_content
  end

  private

    def set_drink
      @drink = Drink.find(params[:id])
    end

    def drink_params
      params.require(:drink).permit(:name, :ingredient, :user_id)
    end
end
```

**Comment by laurenfazah** [comment]
The HTML is usually indicative of a 401 error or the likes. Can you post your CURL request and the error you're getting?

**Comment by laurenfazah** [comment]
And is there anything wrong with your drinks routes? Noticed you posted the DrinksController.

**Comment by Jcornmanhomonoff** [comment]
``` bash
 curl --include --request PATCH http://localhost:3000/change-password/$ID \
>   --header "Authorization: Token token=$TOKEN" \
>   --header "Content-Type: application/json" \
>   --data '{
>     "passwords": {
>       "old": "jess",
>       "new": "bob"
>     }
>   }'
HTTP/1.1 404 Not Found 
Content-Type: text/html; charset=utf-8
Content-Length: 23321
X-Request-Id: 40c100a5-ce43-423c-8aa1-5ade47b9d10c
X-Runtime: 0.059905
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Fri, 29 Apr 2016 14:55:42 GMT
Connection: Keep-Alive

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Action Controller: Exception caught</title>
  <style>
    body {
      background-color: #FAFAFA;
      color: #333;
      margin: 0px;
    }

    body, p, ol, ul, td {
      font-family: helvetica, verdana, arial, sans-serif;
      font-size:   13px;
      line-height: 18px;
    }

    pre {
      font-size: 11px;
      white-space: pre-wrap;
    }

    pre.box {
      border: 1px solid #EEE;
      padding: 10px;
      margin: 0px;
      width: 958px;
    }

    header {
      color: #F0F0F0;
      background: #C52F24;
      padding: 0.5em 1.5em;
    }

    h1 {
      margin: 0.2em 0;
      line-height: 1.1em;
      font-size: 2em;
    }

    h2 {
      color: #C52F24;
      line-height: 25px;
    }

    .details {
      border: 1px solid #D0D0D0;
      border-radius: 4px;
      margin: 1em 0px;
      display: block;
      width: 978px;
    }

    .summary {
      padding: 8px 15px;
      border-bottom: 1px solid #D0D0D0;
      display: block;
    }

    .details pre {
      margin: 5px;
      border: none;
    }

    #container {
      box-sizing: border-box;
      width: 100%;
      padding: 0 1.5em;
    }

    .source * {
      margin: 0px;
      padding: 0px;
    }

    .source {
      border: 1px solid #D9D9D9;
      background: #ECECEC;
      width: 978px;
    }

    .source pre {
      padding: 10px 0px;
      border: none;
    }

    .source .data {
      font-size: 80%;
      overflow: auto;
      background-color: #FFF;
    }

    .info {
      padding: 0.5em;
    }

    .source .data .line_numbers {
      background-color: #ECECEC;
      color: #AAA;
      padding: 1em .5em;
      border-right: 1px solid #DDD;
      text-align: right;
    }

    .line {
      padding-left: 10px;
    }

    .line:hover {
      background-color: #F6F6F6;
    }

    .line.active {
      background-color: #FFCCCC;
    }

    .hidden {
      display: none;
    }

    a { color: #980905; }
    a:visited { color: #666; }
    a.trace-frames { color: #666; }
    a:hover { color: #C52F24; }
    a.trace-frames.selected { color: #C52F24 }

      #route_table {
    margin: 0;
    border-collapse: collapse;
  }

  #route_table thead tr {
    border-bottom: 2px solid #ddd;
  }

  #route_table thead tr.bottom {
    border-bottom: none;
  }

  #route_table thead tr.bottom th {
    padding: 10px 0;
    line-height: 15px;
  }

  #route_table tbody tr {
    border-bottom: 1px solid #ddd;
  }

  #route_table tbody tr:nth-child(odd) {
    background: #f2f2f2;
  }

  #route_table tbody.exact_matches,
  #route_table tbody.fuzzy_matches {
    background-color: LightGoldenRodYellow;
    border-bottom: solid 2px SlateGrey;
  }

  #route_table tbody.exact_matches tr,
  #route_table tbody.fuzzy_matches tr {
    background: none;
    border-bottom: none;
  }

  #route_table td {
    padding: 4px 30px;
  }

  #path_search {
    width: 80%;
    font-size: inherit;
  }

  </style>

  <script>
    var toggle = function(id) {
      var s = document.getElementById(id).style;
      s.display = s.display == 'none' ? 'block' : 'none';
      return false;
    }
    var show = function(id) {
      document.getElementById(id).style.display = 'block';
    }
    var hide = function(id) {
      document.getElementById(id).style.display = 'none';
    }
    var toggleTrace = function() {
      return toggle('blame_trace');
    }
    var toggleSessionDump = function() {
      return toggle('session_dump');
    }
    var toggleEnvDump = function() {
      return toggle('env_dump');
    }
  </script>
</head>
<body>

<header>
  <h1>Routing Error</h1>
</header>
<div id="container">
  <h2>No route matches [PATCH] &quot;/change-password&quot;</h2>


<p><code>Rails.root: /Users/Jessica1/wdi/projects/project-2/drink_backend</code></p>

<div id="traces">
    <a href="#" onclick="hide(&#39;Framework-Trace&#39;);hide(&#39;Full-Trace&#39;);show(&#39;Application-Trace&#39;);; return false;">Application Trace</a> |
    <a href="#" onclick="hide(&#39;Application-Trace&#39;);hide(&#39;Full-Trace&#39;);show(&#39;Framework-Trace&#39;);; return false;">Framework Trace</a> |
    <a href="#" onclick="hide(&#39;Application-Trace&#39;);hide(&#39;Framework-Trace&#39;);show(&#39;Full-Trace&#39;);; return false;">Full Trace</a> 

    <div id="Application-Trace" style="display: block;">
      <pre><code></code></pre>
    </div>
    <div id="Framework-Trace" style="display: none;">
      <pre><code><a class="trace-frames" data-frame-id="0" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call&#39;</a><br><a class="trace-frames" data-frame-id="1" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call&#39;</a><br><a class="trace-frames" data-frame-id="2" href="#">railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app&#39;</a><br><a class="trace-frames" data-frame-id="3" href="#">railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call&#39;</a><br><a class="trace-frames" data-frame-id="4" href="#">activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged&#39;</a><br><a class="trace-frames" data-frame-id="5" href="#">activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged&#39;</a><br><a class="trace-frames" data-frame-id="6" href="#">activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged&#39;</a><br><a class="trace-frames" data-frame-id="7" href="#">railties (4.2.6) lib/rails/rack/logger.rb:20:in `call&#39;</a><br><a class="trace-frames" data-frame-id="8" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;</a><br><a class="trace-frames" data-frame-id="9" href="#">rack (1.6.4) lib/rack/runtime.rb:18:in `call&#39;</a><br><a class="trace-frames" data-frame-id="10" href="#">activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call&#39;</a><br><a class="trace-frames" data-frame-id="11" href="#">rack (1.6.4) lib/rack/lock.rb:17:in `call&#39;</a><br><a class="trace-frames" data-frame-id="12" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call&#39;</a><br><a class="trace-frames" data-frame-id="13" href="#">railties (4.2.6) lib/rails/engine.rb:518:in `call&#39;</a><br><a class="trace-frames" data-frame-id="14" href="#">railties (4.2.6) lib/rails/application.rb:165:in `call&#39;</a><br><a class="trace-frames" data-frame-id="15" href="#">rack (1.6.4) lib/rack/lock.rb:17:in `call&#39;</a><br><a class="trace-frames" data-frame-id="16" href="#">rack (1.6.4) lib/rack/content_length.rb:15:in `call&#39;</a><br><a class="trace-frames" data-frame-id="17" href="#">rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service&#39;</a><br><a class="trace-frames" data-frame-id="18" href="#">/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service&#39;</a><br><a class="trace-frames" data-frame-id="19" href="#">/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run&#39;</a><br><a class="trace-frames" data-frame-id="20" href="#">/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread&#39;</a><br></code></pre>
    </div>
    <div id="Full-Trace" style="display: none;">
      <pre><code><a class="trace-frames" data-frame-id="0" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call&#39;</a><br><a class="trace-frames" data-frame-id="1" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call&#39;</a><br><a class="trace-frames" data-frame-id="2" href="#">railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app&#39;</a><br><a class="trace-frames" data-frame-id="3" href="#">railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call&#39;</a><br><a class="trace-frames" data-frame-id="4" href="#">activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged&#39;</a><br><a class="trace-frames" data-frame-id="5" href="#">activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged&#39;</a><br><a class="trace-frames" data-frame-id="6" href="#">activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged&#39;</a><br><a class="trace-frames" data-frame-id="7" href="#">railties (4.2.6) lib/rails/rack/logger.rb:20:in `call&#39;</a><br><a class="trace-frames" data-frame-id="8" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;</a><br><a class="trace-frames" data-frame-id="9" href="#">rack (1.6.4) lib/rack/runtime.rb:18:in `call&#39;</a><br><a class="trace-frames" data-frame-id="10" href="#">activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call&#39;</a><br><a class="trace-frames" data-frame-id="11" href="#">rack (1.6.4) lib/rack/lock.rb:17:in `call&#39;</a><br><a class="trace-frames" data-frame-id="12" href="#">actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call&#39;</a><br><a class="trace-frames" data-frame-id="13" href="#">railties (4.2.6) lib/rails/engine.rb:518:in `call&#39;</a><br><a class="trace-frames" data-frame-id="14" href="#">railties (4.2.6) lib/rails/application.rb:165:in `call&#39;</a><br><a class="trace-frames" data-frame-id="15" href="#">rack (1.6.4) lib/rack/lock.rb:17:in `call&#39;</a><br><a class="trace-frames" data-frame-id="16" href="#">rack (1.6.4) lib/rack/content_length.rb:15:in `call&#39;</a><br><a class="trace-frames" data-frame-id="17" href="#">rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service&#39;</a><br><a class="trace-frames" data-frame-id="18" href="#">/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service&#39;</a><br><a class="trace-frames" data-frame-id="19" href="#">/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run&#39;</a><br><a class="trace-frames" data-frame-id="20" href="#">/usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread&#39;</a><br></code></pre>
    </div>

  <script type="text/javascript">
    var traceFrames = document.getElementsByClassName('trace-frames');
    var selectedFrame, currentSource = document.getElementById('frame-source-0');

    // Add click listeners for all stack frames
    for (var i = 0; i < traceFrames.length; i++) {
      traceFrames[i].addEventListener('click', function(e) {
        e.preventDefault();
        var target = e.target;
        var frame_id = target.dataset.frameId;

        if (selectedFrame) {
          selectedFrame.className = selectedFrame.className.replace("selected", "");
        }

        target.className += " selected";
        selectedFrame = target;

        // Change the extracted source code
        changeSourceExtract(frame_id);
      });

      function changeSourceExtract(frame_id) {
        var el = document.getElementById('frame-source-' + frame_id);
        if (currentSource && el) {
          currentSource.className += " hidden";
          el.className = el.className.replace(" hidden", "");
          currentSource = el;
        }
      }
    }
  </script>
</div>


    <h2>
      Routes
    </h2>

    <p>
      Routes match in priority from top to bottom
    </p>


<table id='route_table' class='route_table'>
  <thead>
    <tr>
      <th>Helper</th>
      <th>HTTP Verb</th>
      <th>Path</th>
      <th>Controller#Action</th>
    </tr>
    <tr class='bottom'>
      <th>
        <a data-route-helper="_path" title="Returns a relative path (without the http or domain)" href="#">Path</a> /
        <a data-route-helper="_url" title="Returns an absolute url (with the http and domain)" href="#">Url</a>
      </th>
      <th>
      </th>
      <th>
        <input id="search" placeholder="Path Match" type="search" name="path[]" />
      </th>
      <th>
      </th>
    </tr>
  </thead>
  <tbody class='exact_matches' id='exact_matches'>
  </tbody>
  <tbody class='fuzzy_matches' id='fuzzy_matches'>
  </tbody>
  <tbody>
    <tr class='route_row' data-helper='path'>
  <td data-route-name='drinks'>
      drinks<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/drinks(.:format)' data-regexp='^\/drinks(?:\.([^\/.?]+))?$'>
    /drinks(.:format)
  </td>
  <td data-route-reqs='drinks#index'>
    drinks#index
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/drinks(.:format)' data-regexp='^\/drinks(?:\.([^\/.?]+))?$'>
    /drinks(.:format)
  </td>
  <td data-route-reqs='drinks#create'>
    drinks#create
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='drink'>
      drink<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/drinks/:id(.:format)' data-regexp='^\/drinks\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /drinks/:id(.:format)
  </td>
  <td data-route-reqs='drinks#show'>
    drinks#show
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='PATCH'>
    PATCH
  </td>
  <td data-route-path='/drinks/:id(.:format)' data-regexp='^\/drinks\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /drinks/:id(.:format)
  </td>
  <td data-route-reqs='drinks#update'>
    drinks#update
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='PUT'>
    PUT
  </td>
  <td data-route-path='/drinks/:id(.:format)' data-regexp='^\/drinks\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /drinks/:id(.:format)
  </td>
  <td data-route-reqs='drinks#update'>
    drinks#update
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='DELETE'>
    DELETE
  </td>
  <td data-route-path='/drinks/:id(.:format)' data-regexp='^\/drinks\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /drinks/:id(.:format)
  </td>
  <td data-route-reqs='drinks#destroy'>
    drinks#destroy
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='examples'>
      examples<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/examples(.:format)' data-regexp='^\/examples(?:\.([^\/.?]+))?$'>
    /examples(.:format)
  </td>
  <td data-route-reqs='examples#index'>
    examples#index
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/examples(.:format)' data-regexp='^\/examples(?:\.([^\/.?]+))?$'>
    /examples(.:format)
  </td>
  <td data-route-reqs='examples#create'>
    examples#create
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='example'>
      example<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/examples/:id(.:format)' data-regexp='^\/examples\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /examples/:id(.:format)
  </td>
  <td data-route-reqs='examples#show'>
    examples#show
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='PATCH'>
    PATCH
  </td>
  <td data-route-path='/examples/:id(.:format)' data-regexp='^\/examples\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /examples/:id(.:format)
  </td>
  <td data-route-reqs='examples#update'>
    examples#update
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='PUT'>
    PUT
  </td>
  <td data-route-path='/examples/:id(.:format)' data-regexp='^\/examples\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /examples/:id(.:format)
  </td>
  <td data-route-reqs='examples#update'>
    examples#update
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='DELETE'>
    DELETE
  </td>
  <td data-route-path='/examples/:id(.:format)' data-regexp='^\/examples\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /examples/:id(.:format)
  </td>
  <td data-route-reqs='examples#destroy'>
    examples#destroy
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='sign_up'>
      sign_up<span class='helper'>_path</span>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/sign-up(.:format)' data-regexp='^\/sign\-up(?:\.([^\/.?]+))?$'>
    /sign-up(.:format)
  </td>
  <td data-route-reqs='users#signup'>
    users#signup
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='sign_in'>
      sign_in<span class='helper'>_path</span>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/sign-in(.:format)' data-regexp='^\/sign\-in(?:\.([^\/.?]+))?$'>
    /sign-in(.:format)
  </td>
  <td data-route-reqs='users#signin'>
    users#signin
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='DELETE'>
    DELETE
  </td>
  <td data-route-path='/sign-out/:id(.:format)' data-regexp='^\/sign\-out\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /sign-out/:id(.:format)
  </td>
  <td data-route-reqs='users#signout'>
    users#signout
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='PATCH'>
    PATCH
  </td>
  <td data-route-path='/change-password/:id(.:format)' data-regexp='^\/change\-password\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /change-password/:id(.:format)
  </td>
  <td data-route-reqs='users#changepw'>
    users#changepw
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='users'>
      users<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/users(.:format)' data-regexp='^\/users(?:\.([^\/.?]+))?$'>
    /users(.:format)
  </td>
  <td data-route-reqs='users#index'>
    users#index
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='user'>
      user<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/users/:id(.:format)' data-regexp='^\/users\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /users/:id(.:format)
  </td>
  <td data-route-reqs='users#show'>
    users#show
  </td>
</tr>

  </tbody>
</table>

<script type='text/javascript'>
  // Iterates each element through a function
  function each(elems, func) {
    if (!elems instanceof Array) { elems = [elems]; }
    for (var i = 0, len = elems.length; i < len; i++) {
      func(elems[i]);
    }
  }

  // Sets innerHTML for an element
  function setContent(elem, text) {
    elem.innerHTML = text;
  }

  // Enables path search functionality
  function setupMatchPaths() {
    // Check if the user input (sanitized as a path) matches the regexp data attribute
    function checkExactMatch(section, elem, value) {
      var string = sanitizePath(value),
          regexp = elem.getAttribute("data-regexp");

      showMatch(string, regexp, section, elem);
    }

    // Check if the route path data attribute contains the user input
    function checkFuzzyMatch(section, elem, value) {
      var string = elem.getAttribute("data-route-path"),
          regexp = value;

      showMatch(string, regexp, section, elem);
    }

    // Display the parent <tr> element in the appropriate section when there's a match
    function showMatch(string, regexp, section, elem) {
      if(string.match(RegExp(regexp))) {
        section.appendChild(elem.parentNode.cloneNode(true));
      }
    }

    // Check if there are any matched results in a section
    function checkNoMatch(section, defaultText, noMatchText) {
      if (section.innerHTML === defaultText) {
        setContent(section, defaultText + noMatchText);
      }
    }

    // Ensure path always starts with a slash "/" and remove params or fragments
    function sanitizePath(path) {
      var path = path.charAt(0) == '/' ? path : "/" + path;
      return path.replace(/\#.*|\?.*/, '');
    }

    var regexpElems     = document.querySelectorAll('#route_table [data-regexp]'),
        searchElem      = document.querySelector('#search'),
        exactMatches    = document.querySelector('#exact_matches'),
        fuzzyMatches    = document.querySelector('#fuzzy_matches');

    // Remove matches when no search value is present
    searchElem.onblur = function(e) {
      if (searchElem.value === "") {
        setContent(exactMatches, "");
        setContent(fuzzyMatches, "");
      }
    }

    // On key press perform a search for matching paths
    searchElem.onkeyup = function(e){
      var userInput         = searchElem.value,
          defaultExactMatch = '<tr><th colspan="4">Paths Matching (' + escape(sanitizePath(userInput)) +'):</th></tr>',
          defaultFuzzyMatch = '<tr><th colspan="4">Paths Containing (' + escape(userInput) +'):</th></tr>',
          noExactMatch      = '<tr><th colspan="4">No Exact Matches Found</th></tr>',
          noFuzzyMatch      = '<tr><th colspan="4">No Fuzzy Matches Found</th></tr>';

      // Clear out results section
      setContent(exactMatches, defaultExactMatch);
      setContent(fuzzyMatches, defaultFuzzyMatch);

      // Display exact matches and fuzzy matches
      each(regexpElems, function(elem) {
        checkExactMatch(exactMatches, elem, userInput);
        checkFuzzyMatch(fuzzyMatches, elem, userInput);
      })

      // Display 'No Matches' message when no matches are found
      checkNoMatch(exactMatches, defaultExactMatch, noExactMatch);
      checkNoMatch(fuzzyMatches, defaultFuzzyMatch, noFuzzyMatch);
    }
  }

  // Enables functionality to toggle between `_path` and `_url` helper suffixes
  function setupRouteToggleHelperLinks() {

    // Sets content for each element
    function setValOn(elems, val) {
      each(elems, function(elem) {
        setContent(elem, val);
      });
    }

    // Sets onClick event for each element
    function onClick(elems, func) {
      each(elems, function(elem) {
        elem.onclick = func;
      });
    }

    var toggleLinks = document.querySelectorAll('#route_table [data-route-helper]');
    onClick(toggleLinks, function(){
      var helperTxt   = this.getAttribute("data-route-helper"),
          helperElems = document.querySelectorAll('[data-route-name] span.helper');

      setValOn(helperElems, helperTxt);
    });
  }

  setupMatchPaths();
  setupRouteToggleHelperLinks();
</script>




<h2 style="margin-top: 30px">Request</h2>
<p><b>Parameters</b>:</p> <pre>{&quot;passwords&quot;=&gt;&quot;[FILTERED]&quot;}</pre>

<div class="details">
  <div class="summary"><a href="#" onclick="return toggleSessionDump()">Toggle session dump</a></div>
  <div id="session_dump" style="display:none"><pre></pre></div>
</div>

<div class="details">
  <div class="summary"><a href="#" onclick="return toggleEnvDump()">Toggle env dump</a></div>
  <div id="env_dump" style="display:none"><pre>GATEWAY_INTERFACE: &quot;CGI/1.1&quot;
HTTP_ACCEPT: &quot;*/*&quot;
REMOTE_ADDR: &quot;::1&quot;
REMOTE_HOST: &quot;::1&quot;
SERVER_NAME: &quot;localhost&quot;
SERVER_PROTOCOL: &quot;HTTP/1.1&quot;</pre></div>
</div>

<h2 style="margin-top: 30px">Response</h2>
<p><b>Headers</b>:</p> <pre>None</pre>

</div>


</body>
</html>
```

**Comment by Jcornmanhomonoff** [comment]
Do i need to pass in the token and ID that it gives me?

**Comment by RDegnen** [comment]
you need to pass the token in

**Comment by laurenfazah** [comment]
$ID and $TOKEN in your CURL request are variables that you need to define (pass in) before the request

**Comment by GA-MEB** [comment]
@Jcornmanhomonoff 
For future reference, those HTML errors are basically useless. When you see one, don't bother trying to read it - go to the terminal window running your Rails server and read the error shown there.

**Comment by RealWeeks** [comment]
Please see #234

**Comment by Jcornmanhomonoff** [comment]
So I did that. I checked my user ID and token in rails and inserted that into my curl request and I'm still getting back 404.

``` js
HTTP/1.1 401 Unauthorized 
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
WWW-Authenticate: Token realm="Application"
Content-Type: text/html; charset=utf-8
Vary: Origin
Cache-Control: no-cache
X-Request-Id: ff6c3ed7-30f9-4dc3-a95d-c45c4d0e9f92
X-Runtime: 0.002903
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Fri, 29 Apr 2016 15:07:13 GMT
Content-Length: 27
Connection: Keep-Alive

HTTP Token: Access denied.

```

Here's what I'm using for my curl request:

``` js
curl --include --request PATCH http://localhost:3000/change-password/2 \
  --header "Authorization: Token token=946c886a043097b9b19ca84820a9fa24" \
  --header "Content-Type: application/json" \
  --data '{
    "passwords": {
      "old": "jess",
      "new": "bob"
    }
  }'
```

Based off of this:

``` js
#<User:0x007f81049c2c78
  id: 2,
  email: "jess@jess.com",
  token: "a9f45665e383dc02908bbbf12d350e9b",
  password_digest: "$2a$10$XCGUJ8t4UmR7ZoPcYwu8EedAhYB/YmJYs0.mhJoUVjnzG.Xg3DJTi",
  created_at: Fri, 29 Apr 2016 13:43:11 UTC +00:00,
  updated_at: Fri, 29 Apr 2016 15:04:18 UTC +00:00>]
```

**Comment by laurenfazah** [comment]
Those tokens look different. New ones are generated upon each sign-in.

**Comment by Jcornmanhomonoff** [comment]
Sorry Lauren, I didn't realize I put in my controller and not routes.

``` js
Rails.application.routes.draw do
  resources :drinks, except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

**Comment by Jcornmanhomonoff** [comment]
I keep changing the token but it's not working.

**Comment by RDegnen** [comment]
what token do you get back when you sign in with that user?

**Comment by gaand** [comment]
The token has to be what sign-in returns, not what's in the database.

**Comment by Jcornmanhomonoff** [comment]
I was getting the token generated by going into rails and doing User.all and taking the token from there instead of the one generated in the console.
