### ISSUE TITLE
Editing controller for authentication

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#250]
I had curl requests working for all actions in both of my tables and was just finished getting posts of gyms and climbs to work in the browser but realized that I had set up my controller improperly and the actions weren't being authenticated.  I'm just working on sending post requests to my gyms controller for now and having been testing with both curl requests and through the browser but am getting 400 errors.  This is the error via browser testing, I realize it's pointing to my gym parameters but they are unchanged from the previous controller version in which requests were working.  

```
Started POST "/gyms" for ::1 at 2016-04-29 15:18:53 -0400
Processing by GymsController#create as HTML
  Parameters: {"gyms"=>{"name"=>"Central Rock", "location"=>"Watertown", "date_visited"=>"2016-04-07"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "9dd151fa5f8790ef3d6043a6e228994c"]]
Completed 400 Bad Request in 11ms (ActiveRecord: 0.8ms)

ActionController::ParameterMissing (param is missing or the value is empty: gym):
  app/controllers/gyms_controller.rb:58:in `gym_params'
  app/controllers/gyms_controller.rb:22:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (36.4ms)
```

**Comment by MichaelB167** [comment]
this is the gyms controller 

```
class GymsController < ProtectedController
  before_action :set_gym, only: [:update, :destroy]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = current_user.gyms

    render json: @gyms
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
    render json: Gym.find(params[:id])
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = current_user.gyms.build(gym_params)

    if @gym.save
      render json: @gym, status: :created, location: @gym
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    @gym = Gym.find(params[:id])

    if @gym.update(gym_params)
      head :no_content
    else
      render json: @gym.errors, status: :unprocessable_entity
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy

    head :no_content
  end

  private

  def set_gym
    @gym = current_user.gyms.find(params[:id])
  end

  def gym_params
    params.require(:gym).permit(:name, :location, :date_visited)
  end

  private :set_gym, :gym_params
end
```

**Comment by laurenfazah** [comment]
Looks like the data you're sending has a slightly different root key than what your controller is looking for. Refer to 

```
  def gym_params
    params.require(:gym).permit(:name, :location, :date_visited)
  end
```

when structuring your request.

**Comment by RealWeeks** [comment]
See #243

**Comment by MichaelB167** [comment]
Thanks Jason and Lauren, I'll check 243 and see if I get it.
