### ISSUE TITLE
console logging my data in ajax call returns empty object

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#251]
I am trying to sign in and getting

```
jquery.js:9203 POST http://localhost:3000/sign-up/ send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684signUp @ api.js:10(anonymous function) @ event-handlers.js:23jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
:8080/?#:1 XMLHttpRequest cannot load http://localhost:3000/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:21 Object {readyState: 0, status: 0, statusText: "error"}
```

When I console.log the data inside the ajax call I get an empty object. Not sure what I'm doing wrong.

**Comment by laurenfazah** [comment]
Sign up or sign in? What does the data object you're sending look like?

**Comment by RealWeeks** [comment]
paste your server error and ajax

**Comment by louarnos** [comment]
@laurenfazah The data object looks like 

```
object {}
```

@J-Weeks 

```
Started POST "/sign-up/" for ::1 at 2016-04-29 15:26:47 -0400
Processing by UsersController#signup as */*
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/users_controller.rb:63:in `user_creds'
  app/controllers/users_controller.rb:7:in `signup'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.5ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (56.4ms)

```

I know the credentials are empty because the object is empty...
Here is my ajax:

```
const signUp = (success, failure, data) => {
  console.log(data);
  debugger;
  $.ajax({
    method: 'POST',
    url: app.api + 'sign-up/',
    data,
  })
  .done(success)
  .fail(failure);
};
```

**Comment by louarnos** [comment]
It might be how I am assigning my names in my html:

```
<form class="form auth-form">
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail3">Email address</label>
    <input type="email"  name="credentials[email]" class="form-control" id="exampleInputEmail3" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label class="sr-only" for="exampleInputPassword3">Password</label>
    <input type="password" name="credentials[password]" class="form-control" id="exampleInputPassword3" placeholder="Password">
  </div>
  <div class="form-group">
    <label class="sr-only"  for="exampleInputPassword3">Confirm Password</label>
    <input type="password" name="credentials[password]" class="form-control" id="exampleInputPassword3" placeholder="Confirm Password">
  </div>
  <button type="submit" class="btn btn-primary" id="ajax-sign-up-temp-btn">Sign Up</button>
</form>
```

**Comment by RealWeeks** [comment]
this is your issue 

``` bash
(param is missing or the value is empty: credentials)
```

**Comment by louarnos** [comment]
I know that jasoN!!!!! =P

**Comment by laurenfazah** [comment]
Is the empty object coming back from the `console.log(data)` in your AJAX call?

Also I think the name for pw confirmation needs to be `credentials[password_confirmation]`

**Comment by louarnos** [comment]
I think it could be jquery...   

```
$('.content1').on('submit', function (event) {
    let data = getFormFields(this);
    event.preventDefault();
    authApi.signUp(authUi.success, authUi.failure, data);
  });
};
```

Here 'this' is referring to content1, when it should be referring to the form inside content one. This traces back to the issue I was just working on with Lauren

**Comment by RealWeeks** [comment]
it's probably your jquery

**Comment by louarnos** [comment]
Does that make sense?

**Comment by laurenfazah** [comment]
Is your event handler for `<form class="form auth-form">` sending formdata to your AJAX call?

**Comment by laurenfazah** [comment]
So on submit can only be used for form submissions...you'd want to target this sign up form more directly.

**Comment by louarnos** [comment]
can I do this."something?"

**Comment by louarnos** [comment]
i had to target content1 because it wasn't working when I targetted the id defined within the template

**Comment by laurenfazah** [comment]
Rather than targeting the id of the submit button, apply a unique id to the sign in form tag itself and capture that on submit

**Comment by louarnos** [comment]
made it target the form id. Rails server says:

```
Started POST "/sign-up/" for ::1 at 2016-04-29 15:55:45 -0400
Processing by UsersController#signup as */*
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/users_controller.rb:63:in `user_creds'
  app/controllers/users_controller.rb:7:in `signup'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (7.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
```

and console says :

```
jquery.js:9203 POST http://localhost:3000/sign-up/ send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684signUp @ api.js:10(anonymous function) @ event-handlers.js:23jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
:8080/?credentials%5Bemail%5D=kkk%40kkk.com&credentials%5Bpassword%5D=kkk&credentials%5Bpassword%5D=kkk#:1 XMLHttpRequest cannot load http://localhost:3000/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
```

It looks like the credentials are in the string in the console response, so I'm unsure whats happeneing exactly. It is calling password confirmation just password even thought I changed it in my HTML

**Comment by laurenfazah** [comment]
Can you post what's printing from `console.log(data);` in your sign up AJAX function?

**Comment by louarnos** [comment]
its saying: 

```
Object {}
jquery.js:9203 POST http://localhost:3000/sign-up/ send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684signUp @ api.js:10(anonymous function) @ event-handlers.js:23jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
:8080/?credentials%5Bemail%5D=kkk%40kkk.com&credentials%5Bpassword%5D=kkk&credentials%5Bpassword%5D=kkk#:1 XMLHttpRequest cannot load http://localhost:3000/sign-up/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
ui.js:21 Object {readyState: 0, status: 0, statusText: "error"}
```

**Comment by louarnos** [comment]
Its just an empty object.

**Comment by laurenfazah** [comment]
Hmm. What does your updated event handler look like? Something along the lines of:

```
$('#sign-up-form').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields(this);
    authApi.signUp(authUi.success, authUi.failure, data);
  });
};
```

?

**Comment by RealWeeks** [comment]
I'm going to assign this

**Comment by louarnos** [comment]
```
  $('.content1').on('submit', function (event) {
    event.preventDefault();
    let data = getFormFields($(this).children('#sign-up-form')[0]);
    authApi.signUp(authUi.success, authUi.failure, data);
  });
```

This works. We accessed the child of content1, which is the form and unwrapped the dom element to get the actual form.
