### ISSUE TITLE
404 not found when posting

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/full-stack-project#268]
I'm getting a 404 not found when I try to post my story. The object is being created, but it wont post to the database. Also, I noticed that the object has no ID

This is the object: 

``` console
data
Object {stories: Object, submit: "Submit"}stories: Objectbody: "asdasdad"title: "asdasd"__proto__: Objectsubmit: "Submit"__proto__: Object
```

This is the error:

``` console
jquery.js:9203 POST http://localhost:3000/stories/ 404 (Not Found)send @ jquery.js:9203jQuery.extend.ajax @ jquery.js:8684createStory @ api.js:67(anonymous function) @ events.js:42jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
ui.js:11 Object {readyState: 4, responseText: "{"error":{"message":"Not Found"}}", responseJSON: Object, status: 404, statusText: "Not Found"}failure @ ui.js:11fire @ jquery.js:3187self.fireWith @ jquery.js:3317done @ jquery.js:8787(anonymous function) @ jquery.js:9151
```

My AJAX request:

``` js
const createStory = (success, failure, data) => {
  debugger;
  console.log(appURL.data);
  $.ajax({
    method: 'POST',
    url: appURL.link + '/stories/',
    data,
    headers: {
      Authorization: 'Token token=' + appURL.user.token,
    },
  }).done(success)
    .fail(failure);
};
```

my event handler:

``` js
  $('#submit-story-form').on('submit', function(event){
      event.preventDefault();
      let data = getFormFields(this);
      authApi.createStory(authUi.createStorySuccess, authUi.failure, data);
  });
```

my controller:

``` ruby
class StoriesController < ApplicationController
  before_action :set_story, only: [:create, :show, :update, :destroy]

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    if @story.save
      render json: @story, status: :created, location: @story
    else
      render json: @story.errors, status: :unprocessable_entity
    end
  end
```

**Comment by RDegnen** [comment]
What is your server saying in the console when you try to make the request?

**Comment by V4Vince** [comment]
Completed 404

``` console
Started POST "/stories/" for ::1 at 2016-05-02 10:10:59 -0400
Processing by StoriesController#create as */*
  Parameters: {"stories"=>{"title"=>"qweqe", "body"=>"qweqweqe"}, "submit"=>"Submit"}
  Story Load (0.4ms)  SELECT  "stories".* FROM "stories" WHERE "stories"."id" = $1 LIMIT 1  [["id", nil]]
Completed 404 Not Found in 4ms (Views: 1.6ms | ActiveRecord: 0.4ms)
```

**Comment by laurenfazah** [comment]
You're going to want to remove `:create` from `before_action :set_story, only: [:create, :show, :update, :destroy]` in your StoriesController. There's no story to set before you create it :)

**Comment by RDegnen** [comment]
@laurenfazah Ah yes thats it. set_story looks for a story before running any of those actoins, and when you create there is no story to look for.

**Comment by V4Vince** [comment]
@laurenfazah I had it without create originally and it gives me a 500 error :(

``` console
Started POST "/stories/" for ::1 at 2016-05-02 10:19:13 -0400
Processing by StoriesController#create as */*
  Parameters: {"stories"=>{"title"=>"qweqe", "body"=>"qweqweqe"}, "submit"=>"Submit"}
Completed 500 Internal Server Error in 25ms (ActiveRecord: 11.1ms)

ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  app/controllers/stories_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (11.3ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.3ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (55.6ms)
```

``` ruby
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :update, :destroy]

  # POST /stories
  # POST /stories.json
 def create
    @story = Story.new(story_params)

    if @story.save
      render json: @story, status: :created, location: @story
    else
      render json: @story.errors, status: :unprocessable_entity
    end
  end

private

    def set_story
      @story = Story.find(params[:id])
    end
    # added this line
    def story_params
      params[:stories]
    end
end
```

Do you think theres something wrong with my params? The stories are supposed to take two params: title and body

**Comment by laurenfazah** [comment]
Can I see your private `story_params` method in your StoriesController?

**Comment by V4Vince** [comment]
@laurenfazah The private story params method I have in my StoriesController is 

``` ruby
private

    def set_story
      @story = Story.find(params[:id])
    end
    def story_params
      params[:stories]
    end
end
```

**Comment by laurenfazah** [comment]
In theory that method should look something like 

``` ruby
def story_params
  params.require(:story).permit(:title, :body)
end
```

So right now you're supplying `title` and `body`, but because your controller isn't expecting them, you're getting `ActiveModel::ForbiddenAttributesError`. This makes me think something might be wrong with your migrations. Could you post your stories migration and any change migrations you may have created afterwards?

**Comment by gaand** [comment]
ActiveModel won't allow request body data without the require/permit syntax.

**Comment by V4Vince** [comment]
So I just added the require/permit syntax and I'm getting a 400 error

I added 

``` ruby
  private

    def set_story
      @story = Story.find(params[:id])
    end
    # added this line
    def story_params
      params.require(:story).permit(:title, :body)
    end
end
```

My new error

``` console
Started POST "/stories" for ::1 at 2016-05-02 10:45:34 -0400
Processing by StoriesController#create as */*
  Parameters: {"stories"=>{"title"=>"Example Title", "body"=>"An exmaple story"}}
Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: story):
  app/controllers/stories_controller.rb:57:in `story_params'
  app/controllers/stories_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (45.7ms)

```

I also restarted the rails server

**Comment by laurenfazah** [comment]
Cool, so looks like you're getting closer. This is saying that your controller is looking for a `story` key in the data you're sending. Looks like you're sending `stories` instead.

**Comment by V4Vince** [comment]
Ok, I changed my controller to look for `md stories` instead of `md story`` with:

``` ruby
private

    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:stories).permit(:title, :body)
    end
end
```

but I'm getting an undefinied method of text in my stories controller. Does that mean I have to create a text method?

``` console
Started POST "/stories/" for ::1 at 2016-05-02 11:11:54 -0400
Processing by StoriesController#create as */*
  Parameters: {"stories"=>{"title"=>"asdasdasdasdasd", "body"=>"asdasdasda"}, "submit"=>"Submit"}
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.3ms)

NoMethodError (undefined method `text' for #<Story:0x007fc117a7e100>):
  app/controllers/stories_controller.rb:23:in `create'
```

**Comment by RDegnen** [comment]
assigning myself to look at it in person

**Comment by gaand** [comment]
@RDegnen @V4Vince POST should use singular names:  `:story` and `"story"` unless you're creating more than one item with a single POST.

**Comment by V4Vince** [comment]
Removed `ruby validates :text` from my stories model and restarted the grunt server.

For some reason it works with the :stories and not with the :story

**Comment by V4Vince** [comment]
@RDegnen Thanks, Ross!

**Comment by gaand** [comment]
@V4Vince it works, but is unsemantic.
