### ISSUE TITLE
Getting 400 when posting from the front end. Curl request works fine.

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#271]
When I try to create a meal from the front end I am getting a 400. The curl request I am sending from the console works find, so I dont think its my controller...

Here is my ajax request:

``` bash
const createMeal = (success, failure) => {
  $.ajax({
    method: 'POST',
    url: app.api + 'meals/',
    headers: {
      Authorization: 'Token token=' + user1.user.token,
    },
  })
  .done(success)
  .fail(failure);
};

```

This is my controller:

``` bash
class MealsController < ProtectedController
  before_action :set_meal, only: [:show, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = current_user.meals
    render json: @meals
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    render json: Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    # binding.pry
    @meal = current_user.meals.build(meal_params)

    if @meal.save
      render json: @meal, status: :created, location: @meal
    else
      render json: @meal.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      render json: @meal, status: :ok
    else
      render json: @meal.errors, status: :unprocessable_entity
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy

    head :no_content
  end

  def set_meal
    @meal = current_user.meals.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:meal_type, :meal_items, :food_for_meals)
  end

  private :set_meal, :meal_params
end

```

and this is what the console is saying:

``` bash
Started POST "/meals/" for ::1 at 2016-05-02 10:54:52 -0400
Processing by MealsController#create as */*
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f92e7b177809622bbcdf9a5eecc9c1ca"]]
Completed 400 Bad Request in 105ms (ActiveRecord: 1.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: meal):
  app/controllers/meals_controller.rb:55:in `meal_params'
  app/controllers/meals_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (54.2ms)

```

It looks like it doesn't know what meal is when i set the meal params on line 55. I find it odd its working through curl, but not through ajax.

**Comment by laurenfazah** [comment]
Are you sending data with your AJAX request?

**Comment by louarnos** [comment]
just the user token. My curl request has no data and works fine.

**Comment by louarnos** [comment]
wait I lied... my curl does have data.

**Comment by laurenfazah** [comment]
Yeah that would have been strange if it was working through cURL without data. Your rails error is:

`ActionController::ParameterMissing (param is missing or the value is empty: meal):`

so try adding that data in and see if it works.

**Comment by louarnos** [comment]
It works... thanks.
