### ISSUE TITLE
Getting html error when I Patch, even through curl now. Was working earlier.

### ISSUE THREAD

**Issue by louarnos** [ga-wdi-boston/full-stack-project#272]
Here is my curl request:

``` bash
TOKEN='BAhJIiUxMjY1MDgzNjdjNWNlOGMzMzY1ZDJhZTUzN2JlOTQ0ZQY6BkVG--edd687d8c06cd90865db6c30781afc0940fa4008'
ID ='12'

curl --include --request PATCH http://localhost:3000/meals/$ID \
  --header "Authorization: Token token=$TOKEN" \
  --header "Content-Type: application/json" \
  --data '{
    "meal" : {
    "food_for_meals" : [1,2,3,4,5]
  }
}'
```

Here is my controller:

``` bash

class MealsController < ProtectedController
  before_action :set_meal, only: [:show, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = current_user.meals
    render json: @meals
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    render json: Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    # binding.pry
    @meal = current_user.meals.build(meal_params)

    if @meal.save
      render json: @meal, status: :created, location: @meal
    else
      render json: @meal.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    if @meal.update(meal_params)
      render json: @meal, status: :ok
    else
      render json: @meal.errors, status: :unprocessable_entity
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy

    head :no_content
  end

  def set_meal
    @meal = current_user.meals.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:meal_type, :meal_items, :food_for_meals)
  end

  private :set_meal, :meal_params
end
```

console says:

``` bash

Started PATCH "/meals/" for ::1 at 2016-05-02 11:31:59 -0400

ActionController::RoutingError (No route matches [PATCH] "/meals"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_route.html.erb (2.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_table.html.erb (7.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (93.8ms)

```

Its saying there's no route for patch. Here are my routes:

``` bash
Rails.application.routes.draw do
  resources :meal_items, except: [:new, :edit]
  resources :meals, except: [:new, :edit]
  resources :foods, except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

Was working before, so I'm not sure whats changed.

**Comment by louarnos** [comment]
Do I need to make use of current user in patch?

**Comment by louarnos** [comment]
Or update rather..

**Comment by laurenfazah** [comment]
What does `rake routes` output?

**Comment by louarnos** [comment]
``` bash
meal_items GET    /meal_items(.:format)          meal_items#index
           POST   /meal_items(.:format)          meal_items#create
 meal_item GET    /meal_items/:id(.:format)      meal_items#show
           PATCH  /meal_items/:id(.:format)      meal_items#update
           PUT    /meal_items/:id(.:format)      meal_items#update
           DELETE /meal_items/:id(.:format)      meal_items#destroy
     meals GET    /meals(.:format)               meals#index
           POST   /meals(.:format)               meals#create
      meal GET    /meals/:id(.:format)           meals#show
           PATCH  /meals/:id(.:format)           meals#update
           PUT    /meals/:id(.:format)           meals#update
           DELETE /meals/:id(.:format)           meals#destroy
     foods GET    /foods(.:format)               foods#index
           POST   /foods(.:format)               foods#create
      food GET    /foods/:id(.:format)           foods#show
           PATCH  /foods/:id(.:format)           foods#update
           PUT    /foods/:id(.:format)           foods#update
           DELETE /foods/:id(.:format)           foods#destroy
  examples GET    /examples(.:format)            examples#index
           POST   /examples(.:format)            examples#create
   example GET    /examples/:id(.:format)        examples#show
           PATCH  /examples/:id(.:format)        examples#update
           PUT    /examples/:id(.:format)        examples#update
           DELETE /examples/:id(.:format)        examples#destroy
   sign_up POST   /sign-up(.:format)             users#signup
   sign_in POST   /sign-in(.:format)             users#signin
           DELETE /sign-out/:id(.:format)        users#signout
           PATCH  /change-password/:id(.:format) users#changepw
           PATCH  /meals/:id(.:format)           meals#update
     users GET    /users(.:format)               users#index
      user GET    /users/:id(.:format)           users#show
```

**Comment by louarnos** [comment]
it looks like i should be using the singular not plural

**Comment by louarnos** [comment]
I changed meals => meal in my curl and got the same error.

**Comment by laurenfazah** [comment]
Hmm why are there two PATCH /meals/:id routes mapped to `meals#update`?

**Comment by laurenfazah** [comment]
And no you don't need to set current user in the update method, your `before_action` is taking care of that for you.

**Comment by louarnos** [comment]
You mean put and patch?

**Comment by laurenfazah** [comment]
No, there's a second PATCH route towards the bottom of the list.

**Comment by louarnos** [comment]
Oh i tried to manually put one in to see if it fixed it. Ive since deleted it. Should prob make sure i saved and restarted the server

**Comment by louarnos** [comment]
``` bash
    Prefix Verb   URI Pattern                    Controller#Action
meal_items GET    /meal_items(.:format)          meal_items#index
           POST   /meal_items(.:format)          meal_items#create
 meal_item GET    /meal_items/:id(.:format)      meal_items#show
           PATCH  /meal_items/:id(.:format)      meal_items#update
           PUT    /meal_items/:id(.:format)      meal_items#update
           DELETE /meal_items/:id(.:format)      meal_items#destroy
     meals GET    /meals(.:format)               meals#index
           POST   /meals(.:format)               meals#create
      meal GET    /meals/:id(.:format)           meals#show
           PATCH  /meals/:id(.:format)           meals#update
           PUT    /meals/:id(.:format)           meals#update
           DELETE /meals/:id(.:format)           meals#destroy
     foods GET    /foods(.:format)               foods#index
           POST   /foods(.:format)               foods#create
      food GET    /foods/:id(.:format)           foods#show
           PATCH  /foods/:id(.:format)           foods#update
           PUT    /foods/:id(.:format)           foods#update
           DELETE /foods/:id(.:format)           foods#destroy
  examples GET    /examples(.:format)            examples#index
           POST   /examples(.:format)            examples#create
   example GET    /examples/:id(.:format)        examples#show
           PATCH  /examples/:id(.:format)        examples#update
           PUT    /examples/:id(.:format)        examples#update
           DELETE /examples/:id(.:format)        examples#destroy
   sign_up POST   /sign-up(.:format)             users#signup
   sign_in POST   /sign-in(.:format)             users#signin
           DELETE /sign-out/:id(.:format)        users#signout
           PATCH  /change-password/:id(.:format) users#changepw
     users GET    /users(.:format)               users#index
      user GET    /users/:id(.:format)           users#show
```

**Comment by louarnos** [comment]
ok so its gone, still got the same error when i patched.

**Comment by laurenfazah** [comment]
Hmm. I think you don't want that `@meal = Meal.find(params[:id])` line in your update method because of your `before_action`. Is that new? That might also not be the source of this error... no route for PATCH /meals isn't the most descriptive error message in this situation.

**Comment by louarnos** [comment]
Ill take it out

**Comment by louarnos** [comment]
Its giving the same error w or w/o it.

**Comment by laurenfazah** [comment]
@gaand or @MattB-GA-Boston do you have any insight here? A similar issue is also happening with #274

**Comment by RealWeeks** [comment]
Does the explicit route work? controller#action?

**Comment by louarnos** [comment]
i tried that earlier. It didnt seem to make a difference. I can try again to be sure I did it correctly.

**Comment by RealWeeks** [comment]
so resource routes and explicit routes don't work.  Hmmm.

**Comment by louarnos** [comment]
@J-Weeks I haven't tried again yet, was working on the other problem.

**Comment by louarnos** [comment]
My routes now look like:

```
Prefix Verb   URI Pattern                    Controller#Action
meal_items GET    /meal_items(.:format)          meal_items#index
           POST   /meal_items(.:format)          meal_items#create
 meal_item GET    /meal_items/:id(.:format)      meal_items#show
           PATCH  /meal_items/:id(.:format)      meal_items#update
           PUT    /meal_items/:id(.:format)      meal_items#update
           DELETE /meal_items/:id(.:format)      meal_items#destroy
     meals GET    /meals(.:format)               meals#index
           POST   /meals(.:format)               meals#create
      meal GET    /meals/:id(.:format)           meals#show
           PATCH  /meals/:id(.:format)           meals#update
           PUT    /meals/:id(.:format)           meals#update
           DELETE /meals/:id(.:format)           meals#destroy
     foods GET    /foods(.:format)               foods#index
           POST   /foods(.:format)               foods#create
      food GET    /foods/:id(.:format)           foods#show
           PATCH  /foods/:id(.:format)           foods#update
           PUT    /foods/:id(.:format)           foods#update
           DELETE /foods/:id(.:format)           foods#destroy
  examples GET    /examples(.:format)            examples#index
           POST   /examples(.:format)            examples#create
   example GET    /examples/:id(.:format)        examples#show
           PATCH  /examples/:id(.:format)        examples#update
           PUT    /examples/:id(.:format)        examples#update
           DELETE /examples/:id(.:format)        examples#destroy
   sign_up POST   /sign-up(.:format)             users#signup
   sign_in POST   /sign-in(.:format)             users#signin
           DELETE /sign-out/:id(.:format)        users#signout
           PATCH  /change-password/:id(.:format) users#changepw
           PATCH  /meals/:id(.:format)           meals#update
     users GET    /users(.:format)               users#index
      user GET    /users/:id(.:format)           users#show
```

and its still giving me the same error.

**Comment by gaand** [comment]
When you run the curl request, do you get an error?  It looks like there's a space between `ID` and `=` (the equals sign) (unless there's a copy/paste error).  I don't think that's allowed.

**Comment by louarnos** [comment]
if thats it im gonna cry...

**Comment by louarnos** [comment]
officially crying. @gaand thank you
