### ISSUE TITLE
Existing Parameter Considered Missing

### ISSUE THREAD

**Issue by susandaiute** [ga-wdi-boston/full-stack-project#273]
When I go to submit a question, I'm getting the error that the param "question" is missing even though the rails server notes the question parameter as having value "sdfsdf" which is the nonsense I typed into that field.

```
Started POST "/questions" for ::1 at 2016-05-02 11:42:18 -0400
Processing by QuestionsController#create as */*
  Parameters: {"questions"=>{"question"=>"sdfsdf", "answer1"=>"sdfsdf", "answer2"=>"sdfsdf", "answer3"=>"sdfsdf"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "3089a305a77bb9893c3f3719d33d4c50"]]
Completed 400 Bad Request in 5ms (ActiveRecord: 0.8ms)

ActionController::ParameterMissing (param is missing or the value is empty: question):
  app/controllers/questions_controller.rb:54:in `question_params'
  app/controllers/questions_controller.rb:22:in `create'
```

**Comment by susandaiute** [comment]
The browser console error is:

```
XMLHttpRequest cannot load http://localhost:3000/questions. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.
```

**Comment by laurenfazah** [comment]
Can you post what your private `question_params` method looks like in your QuestionsController?

**Comment by susandaiute** [comment]
There was a typo which  I fixed, but now I'm getting in the rails server:

```
Started POST "/questions" for ::1 at 2016-05-02 11:53:24 -0400
Processing by QuestionsController#create as */*
  Parameters: {"questions"=>{"question"=>"sdfsf", "answer1"=>"sdfsdf", "answer2"=>"sdsdf", "answer3"=>"sdsf"}}
  User Load (1.0ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "c4a0a3c2891b97a51f0007445640f53c"]]
Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.5ms)

ActiveRecord::UnknownAttributeError (unknown attribute 'question' for Question.):
  app/controllers/questions_controller.rb:22:in `create'
```

**Comment by gaand** [comment]
Please post the controller method that contains the require/permit for the question parameters.

Also, the data you're sending should probably have a singular root key, `"question"`.

**Comment by RealWeeks** [comment]
Can you paste in your strong params?

**Comment by susandaiute** [comment]
```
  def question_params
    params.require(:questions).permit(:question, :answer1, :answer2, :answer3)
  end
end
```

I'm thinking of changing the "questions" root key to "submitquestion" or maybe just "submit"

**Comment by RealWeeks** [comment]
Don't make that change Susan

**Comment by laurenfazah** [comment]
What does your updated questions migration look like?

**Comment by susandaiute** [comment]
```
class CreateQuestions < ActiveRecord::Migration
  def change
    create_table :questions do |t|
      t.string :question, null: false
      t.string :answer1, null: false
      t.string :answer2, null: false
      t.string :answer3, null: false

      t.references :user, index: true, foreign_key: true, null: false

      t.timestamps null: false
    end
  end
end

```

**Comment by laurenfazah** [comment]
I'm thinking with this change, your params should actually be:

```
  def question_params
    params.require(:question).permit(:question, :answer1, :answer2, :answer3)
  end
```

which would then get confusing with a question within a question. 

I can self assign to walk through in person.

**Comment by susandaiute** [comment]
Summary: We changed the "questions" root key to "question" and the "question" parameter to "title".  Also, the models were a bit messy - I had user being called creator which overcomplicated/broke things.
