### ISSUE TITLE
Attaching climb ID to patch method

### ISSUE THREAD

**Issue by MichaelB167** [ga-wdi-boston/full-stack-project#274]
I'm working on patching a climb but as far as I can tell the request isn't sending with an ID attached.  The rake routes output for patch is `PATCH  /climbs/:id(.:format)          climbs#update` and the error I'm getting in rails server is:

```
Started PATCH "/climbs/" for ::1 at 2016-05-02 11:43:03 -0400

ActionController::RoutingError (No route matches [PATCH] "/climbs"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_table.html.erb (0.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (45.3ms)

```

Climb patch api:

```
const updateClimb = (success, failure, data, climb_id) => {
  $.ajax({
    method: "PATCH",
    url: app.api + '/climbs/' + climb_id,
    data,
    headers: {
      Authorization: 'Token token='+ app.user.token,
    },
  })
  .done(success)
  .fail(failure);
};
```

Event handlers:

```
$('#updateClimbModal').on('submit', function (event) {
      event.preventDefault();
      let id = $(".update-climb-btn").attr("data-climb-id");
      let data = getFormFields(event.target);
      //get data, prevents default
      authClimbApi.updateClimb(authClimbUi.updateClimbSuccess, authUi.failure, data, id);
  });

  // add climb id to update submit button

  $('.content-display').on('click', '.update-climb', function(event){
      event.preventDefault();
      let id = $(event.target).attr("data-climb-id");
      $(".update-climb-btn").attr("data-climb-id", id);
  });
```

I wrote the last bit to attach the climb ID to each patch modal as I'm listing climbs via handlebars and each has a nested patch modal and delete button.  Is this a viable way to pass the id or do I need to somehow define it in the api?

**Comment by RealWeeks** [comment]
Can you past in your routes

**Comment by RealWeeks** [comment]
looks like its passing to climbs but not an ID is why I ask

**Comment by MichaelB167** [comment]
```
Rails.application.routes.draw do
  resources :examples, except: [:new, :edit]
  resources :gyms, except: [:new, :edit]
  resources :climbs, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

**Comment by RealWeeks** [comment]
sorry rake routes output

**Comment by MichaelB167** [comment]
```
~/wdi/projects/climb-buddy-app/climb-buddy-back-end (testing)$ rake routes
  Prefix Verb   URI Pattern                    Controller#Action
examples GET    /examples(.:format)            examples#index
         POST   /examples(.:format)            examples#create
 example GET    /examples/:id(.:format)        examples#show
         PATCH  /examples/:id(.:format)        examples#update
         PUT    /examples/:id(.:format)        examples#update
         DELETE /examples/:id(.:format)        examples#destroy
    gyms GET    /gyms(.:format)                gyms#index
         POST   /gyms(.:format)                gyms#create
     gym GET    /gyms/:id(.:format)            gyms#show
         PATCH  /gyms/:id(.:format)            gyms#update
         PUT    /gyms/:id(.:format)            gyms#update
         DELETE /gyms/:id(.:format)            gyms#destroy
  climbs GET    /climbs(.:format)              climbs#index
         POST   /climbs(.:format)              climbs#create
   climb GET    /climbs/:id(.:format)          climbs#show
         PATCH  /climbs/:id(.:format)          climbs#update
         PUT    /climbs/:id(.:format)          climbs#update
         DELETE /climbs/:id(.:format)          climbs#destroy
 sign_up POST   /sign-up(.:format)             users#signup
 sign_in POST   /sign-in(.:format)             users#signin
         DELETE /sign-out/:id(.:format)        users#signout
         PATCH  /change-password/:id(.:format) users#changepw
   users GET    /users(.:format)               users#index
    user GET    /users/:id(.:format)           users#show
```

**Comment by MichaelB167** [comment]
I know they're not nested for now but trying to get CRUD working then going back and seeing if I can nest properly.

**Comment by MichaelB167** [comment]
Issueception.  I'm also testing patch via curl and although I'm almost certain it was working before it isn't now so my problem may be on the back end as well.  Curl script-

```
TOKEN='BAhJIiU1YzVhNjZlNDg4NmIyMmQ1ODY4MmRjOTZiODRmNjU4YQY6BkVG--4609a3d28e6b6dc1c21a79f5f1d30bab6dd7fa18'
  curl --include --request PATCH http://localhost:3000/climbs/11 \
    --header "Authorization: Token token=$TOKEN" \
    --header "Content-Type: application/json" \
    --data '{
      "climbs": {
        "route_type": "Lead",
        "route_grade": "9",
        "hold_type_of_fall": "Sloper",
        "fall_notes": "asdflk"
      }
    }'
```

**Comment by louarnos** [comment]
@MichaelB167 you find a solution?

**Comment by MichaelB167** [comment]
@louarnos nah going back and forth between patch and delete, trying to get delete atm.  hbu?

**Comment by RDegnen** [comment]
Did you pass an id for the climb you want to patch?

**Comment by MichaelB167** [comment]
That seems to be the source of the error for now, ya. I'm trying to figure out why the function that's meant to set the id through handlebars isn't doing so.

**Comment by gaand** [comment]
Did you get the curl request to work?  If that's not working, then I'd focus there until it is.

Also, `"climb"` unless you're updating multiple climbs at the same time.

**Comment by MichaelB167** [comment]
Ya working on the curl request currently, will change to 'climb'.

**Comment by MichaelB167** [comment]
YES.  Curl requests working again, thank you Antony.  Back to diagnosing through the browser.

**Comment by RDegnen** [comment]
ok. Post the error that pops up in the browser when you get to it

**Comment by MichaelB167** [comment]
```
XMLHttpRequest cannot load http://localhost:3000/climbs/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.
```

experimenting with debuggers

**Comment by RDegnen** [comment]
What is your serever log saying?

**Comment by MichaelB167** [comment]
Good point:

```
ActionController::RoutingError (No route matches [PATCH] "/climbs"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_table.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (48.0ms)
```

so it seems like it's lacking an id, i.e not compatible with `PATCH  /climbs/:id(.:format)          climbs#update`

**Comment by gaand** [comment]
Please add a console log of the climb_id.  I'm guessing it's an empty string.

**Comment by MichaelB167** [comment]
Trying, not getting it to log anything at the moment but I see how that is likely the root of the problem.

**Comment by RDegnen** [comment]
assigning myself

**Comment by MichaelB167** [comment]
TY Ross. Front end functions were functioning properly but I didn't add ID to the serializer so it wasn't attaching id's to climbs. ARGH
