### ISSUE TITLE
Object is only displaying ID in browser console

### ISSUE THREAD

**Issue by V4Vince** [ga-wdi-boston/full-stack-project#279]
My request is being posted into the backend database, however when I log the story object, its only showing an ID, no title or body. 

``` console
Object {story: Object}
story
:
Object
id
:
23
```

my ui

``` js
const createStorySuccess = (data) => {
    debugger;
  //storyData.storyId = data.stories;
  console.log(data);
  console.log("You created a story");
};
```

my ajax

``` js
const createStory = (success, failure, data) => {
  console.log(appURL.data);
  $.ajax({
    method: 'POST',
    url: appURL.link + '/stories/',
    data,
    headers: {
      Authorization: 'Token token=' + appURL.user.token,
    },
  }).done(success)
    .fail(failure);
};
```

and my event handler

``` js
$('#submit-story-form').on('submit', function(event){
      event.preventDefault();
      let data = getFormFields(this);
      authApi.createStory(authUi.createStorySuccess, authUi.failure, data);
  });
```

My story is being posted to the database correctly so I'm not sure on what to check

``` console
Started POST "/stories/" for ::1 at 2016-05-02 15:11:27 -0400
Processing by StoriesController#create as */*
  Parameters: {"stories"=>{"title"=>"qqqqqqqqqq", "body"=>"qqqqqqqqqqqqqqq"}, "submit"=>"Submit"}
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "db1a6aeca1aa5ead1f1a8bfc0bdfa819"]]
   (0.2ms)  BEGIN
  SQL (7.5ms)  INSERT INTO "stories" ("title", "body", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["title", "qqqqqqqqqq"], ["body", "qqqqqqqqqqqqqqq"], ["user_id", 21], ["created_at", "2016-05-02 19:11:27.248767"], ["updated_at", "2016-05-02 19:11:27.248767"]]
   (9.8ms)  COMMIT
[active_model_serializers] Rendered StorySerializer with ActiveModel::Serializer::Adapter::Json (0.41ms)
Completed 201 Created in 29ms (Views: 1.3ms | ActiveRecord: 18.3ms)
```

**Comment by laurenfazah** [comment]
What does your `stories#create` StoriesController method look like?

**Comment by GA-MEB** [comment]
@V4Vince 
Building off of @laurenfazah 's comment, can you paste the `story_params` method as well?

**Comment by V4Vince** [comment]
Is it because my stories param is plural? 

``` ruby
def create
    @story = current_user.stories.build(story_params)

    if @story.save
      render json: @story, status: :created, location: @story
    else
      render json: @story.errors, status: :unprocessable_entity
    end
  end

  private

    def set_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:stories).permit(:title, :body)
    end
end
```

**Comment by GA-MEB** [comment]
@V4Vince : In `story_params`, that should be `require(:story)`, not `require(:stories)`. 

The reason is that the params you are passing through `story_params` pertain to a single story, not a collection of stories.

**Comment by laurenfazah** [comment]
This circles back to the issue you were having this morning - your data from your AJAX request should have been altered vs altering `story_params` ( #268 )

**Comment by gaand** [comment]
What's in your serializer?

**Comment by V4Vince** [comment]
@laurenfazah I should be altering the data from my AJAX request? Do you mean passing a story ID in my request?
 This is the same error I got this morning: 

``` console
Started POST "/stories/" for ::1 at 2016-05-02 15:32:14 -0400
Processing by StoriesController#create as */*
  Parameters: {"stories"=>{"title"=>"Another exmaple story2", "body"=>"wwwwwwwwwwwwwwwwwwwwwwww"}, "submit"=>"Submit"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "4f340e2704678d8a0626585d28b05336"]]
Completed 400 Bad Request in 12ms (ActiveRecord: 4.9ms)

ActionController::ParameterMissing (param is missing or the value is empty: story):
  app/controllers/stories_controller.rb:59:in `story_params'
  app/controllers/stories_controller.rb:23:in `create'
```

Does it want me to add data params to my AJAX request like so:

``` js
const createStory = (success, failure, data) => {
  console.log(appURL.data);
  $.ajax({
    method: 'POST',
    url: appURL.link + '/stories/',
    data: {
        "story": {
          "title": data.stories.title
          "body": data.stories.body
      },
    headers: {
      Authorization: 'Token token=' + appURL.user.token,
    },
  }).done(success)
    .fail(failure);
};
```

**Comment by V4Vince** [comment]
@gaand Do I have to add :title and :body to attributes? 

``` ruby
class StorySerializer < ActiveModel::Serializer
  attributes :id
end
```

**Comment by laurenfazah** [comment]
So yes, if you edit the name attributes on your form for this to match `story` singular, it should pass into your AJAX function correctly, then onto your rails controller correctly.

**Comment by V4Vince** [comment]
@laurenfazah ok cool. But now its back to my first problem; I'm logging the object in the browser console, but it wont show the title or body. The title and body is posting in rails server just fine

``` console
Started POST "/stories/" for ::1 at 2016-05-02 15:56:17 -0400
Processing by StoriesController#create as */*
  Parameters: {"story"=>{"title"=>"1212321312412312312312312312", "body"=>"asdkjagsdjasgjdbjahsfvhjasbfdasdasdasd"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "2bebd8046db213f14a8bd7b38ef715e7"]]
   (0.2ms)  BEGIN
  SQL (0.9ms)  INSERT INTO "stories" ("title", "body", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["title", "1212321312412312312312312312"], ["body", "asdkjagsdjasgjdbjahsfvhjasbfdasdasdasd"], ["user_id", 21], ["created_at", "2016-05-02 19:56:17.339214"], ["updated_at", "2016-05-02 19:56:17.339214"]]
   (6.2ms)  COMMIT
[active_model_serializers] Rendered StorySerializer with ActiveModel::Serializer::Adapter::Json (0.58ms)
Completed 201 Created in 41ms (Views: 3.5ms | ActiveRecord: 11.7ms)
```

**Comment by V4Vince** [comment]
So i placed two debuggers; 1 in the AJAX request and 1 in the success function. When I log data in the AJAX, it returns title and body but no ID. when I log data in the success function, it returns only ID. 

``` js
const createStory = (success, failure, data) => {
  debugger;
  console.log(appURL.data);
  $.ajax({
    method: 'POST',
    url: appURL.link + '/stories/',
    data: {
        "story": {
          "title": data.story.title,
          "body": data.story.body
      }
    },
    headers: {
      Authorization: 'Token token=' + appURL.user.token,
    },
  }).done(success)
    .fail(failure);
};
```

``` js
const createStorySuccess = (data) => {
    debugger;
  console.log(data);
  console.log("You created a story");
};
```

Any ideas as to why its doing that?

**Comment by laurenfazah** [comment]
I believe that is because your serializer is only returning `id`

**Comment by V4Vince** [comment]
@laurenfazah Serializer needs all params. Thank you!!
