### ISSUE TITLE
create ajax request isn't connecting to backend controller

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#29]
Can't quite figure out what's wrong with my createWord method. I keep getting the following error:

```
Started POST "/words" for ::1 at 2015-11-10 16:07:35 -0500
Processing by WordsController#create as HTML
  Parameters: {"words"=>"hi"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "5eff73f3f4efebaf181524701fe03f6f"]]
Completed 400 Bad Request in 1ms (ActiveRecord: 0.2ms)

ActionController::ParameterMissing (param is missing or the value is empty: word):
  app/controllers/words_controller.rb:42:in `word_params'
  app/controllers/words_controller.rb:17:in `create'


  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.6ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.9ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (42.8ms)
```

**Comment by GA-MEB** [comment]
What's inside your `create` method for `WordsController`?

**Comment by baz1389** [comment]
```
def create
    word = Word.create(word_params)
    if word.save
      render json: word, status: :created
    else
      render json: word.errors, status: :unprocessable_entity
    end
  end
```

**Comment by GA-MEB** [comment]
Can you also post the `word_params` method?

**Comment by baz1389** [comment]
```
def word_params
    params.require(:word).permit([:name, :definition, :sample_sentence, :user_id])
  end
```

**Comment by GA-MEB** [comment]
According to `word_params`, your data should look like this:

```
{"word": {
  "name": "...",
  "definition": "...",
  // etc
}}
```

But it doesn't look like that's the case in the request.

**Comment by GA-MEB** [comment]
Closing this issue; the problem was malformed data in the AJAX request.
