### ISSUE TITLE
Loading example data aborting because subclasses confused

### ISSUE THREAD

**Issue by shireen-bean** [ga-wdi-boston/full-stack-project#320]
I generated scaffolding, realized that's not what I wanted so I destroyed the scaffolding. generated scaffolding again, destroyed again, and generated it again.

I think now it is confused about the class attributes. It is actively represented in the database with the correct column names and number of columns (i have 7), but it only allows me to add up to 5 inputs (probably the number of attributes aI had on my original scaffold.

This is my database 

```
   Column    |            Type             |                      Modifiers                       
-------------+-----------------------------+------------------------------------------------------
 id          | integer                     | not null default nextval('bottoms_id_seq'::regclass)
 bottom_name | character varying           | 
 brand       | character varying           | 
 color       | character varying           | 
 business    | boolean                     | 
 leg_length  | character varying           | 
 type        | character varying           | 
 image       | character varying           | 
 created_at  | timestamp without time zone | not null
 updated_at  | timestamp without time zone | not null
Indexes:
    "bottoms_pkey" PRIMARY KEY, btree (id)
```

and this is the csv I am trying to seed:

```
bottom_name,brand,color,business,leg_length,type,image
'flowy skirt','Brandy Melville','white',true,'mid','content1','content2'
'high wasted shorts','Top Shop','blue',true,'mid','content3','content4'
```

it works if I get rid of the last two inputs of each lines like this:

```
bottom_name,brand,color,business,leg_length,type,image
'flowy skirt','Brandy Melville','white',true,'mid'
'high wasted shorts','Top Shop','blue',true,'mid'
```

but leaves the last two columns blank in the database.

This is the error i get when nuke_pave

```
rake aborted!
ActiveRecord::SubclassNotFound: Invalid single-table inheritance type: 'content' is not a subclass of Bottom
/Users/ShireenKheradpey/wdi/projects/full-stack-project/full-stack-backend/db/examples.rb:17:in `block (2 levels) in <top (required)>'
/Users/ShireenKheradpey/wdi/projects/full-stack-project/full-stack-backend/db/examples.rb:16:in `block in <top (required)>'
/Users/ShireenKheradpey/wdi/projects/full-stack-project/full-stack-backend/db/examples.rb:15:in `<top (required)>'
/Users/ShireenKheradpey/wdi/projects/full-stack-project/full-stack-backend/lib/tasks/db.rake:4:in `require_relative'
/Users/ShireenKheradpey/wdi/projects/full-stack-project/full-stack-backend/lib/tasks/db.rake:4:in `block (2 levels) in <top (required)>'
/usr/local/var/rbenv/versions/2.3.0/bin/bundle:23:in `load'
/usr/local/var/rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => db:nuke_pave => db:examples
(See full trace by running task with --trace)
```

**Comment by shireen-bean** [comment]
Solution:

Cannot assign "type" as a column name.
Column name re-named to description and eveything works completely fine now.
See below:

```
   Column    |            Type             |                      Modifiers                       
-------------+-----------------------------+------------------------------------------------------
 id          | integer                     | not null default nextval('bottoms_id_seq'::regclass)
 bottom_name | character varying           | 
 brand       | character varying           | 
 color       | character varying           | 
 business    | boolean                     | 
 leg_length  | character varying           | 
 description | character varying           | 
 image       | character varying           | 
 created_at  | timestamp without time zone | not null
 updated_at  | timestamp without time zone | not null
Indexes:
    "bottoms_pkey" PRIMARY KEY, btree (id)
```

Thanks, Brian!

**Comment by berziiii** [comment]
Type is something that rails/postgres doesn't like so renamed Type to description in the bottoms table. Worked. Please close if resolved @shkherad
