### ISSUE TITLE
POST curl request giving error

### ISSUE THREAD

**Issue by gabescarbrough** [ga-wdi-boston/full-stack-project#356]
I have successfully tested my palettes#index, palettes#show, and palettes#destroy controller actions using curl requests.

I have successfully created palettes using ActiveRecord.

I am currently trying to test my palettes#create action using curl and am receiving an error.

When I run 

``` sh
curl --include --request POST "http://localhost:3000/palettes" \
  --header "Content-Type: application/json" \
  --data '{
    "palette": {
      "palette_name": "Another Test",
      "color1": "hsl(0, 50%, 50%)",
      "color2": "hsl(10, 50%, 50%)",
      "color3": "hsl(20, 50%, 50%)",
      "color4": "hsl(30, 50%, 50%)",
      "color5": "hsl(40, 50%, 50%)",
    }
  }'
```

I get a Rails server error that says:

```
Started POST "/palettes" for ::1 at 2016-08-17 11:20:05 -0400
Error occurred while parsing request parameters.
Contents:

{
    "palette": {
      "palette_name": "Another Test",
      "color1": "hsl(0, 50%, 50%)",
      "color2": "hsl(10, 50%, 50%)",
      "color3": "hsl(20, 50%, 50%)",
      "color4": "hsl(30, 50%, 50%)",
      "color5": "hsl(40, 50%, 50%)",
    }
  }

ActionDispatch::ParamsParser::ParseError (822: unexpected token at '{
    "palette": {
      "palette_name": "Another Test",
      "color1": "hsl(0, 50%, 50%)",
      "color2": "hsl(10, 50%, 50%)",
      "color3": "hsl(20, 50%, 50%)",
      "color4": "hsl(30, 50%, 50%)",
      "color5": "hsl(40, 50%, 50%)",
    }
  }'):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:53:in `rescue in parse_formatted_parameters'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:32:in `parse_formatted_parameters'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:23:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (39.2ms)
```

Is there something wrong with my curl request formatting?

**Comment by RealWeeks** [comment]
Can you paste in your strong params from your palettes controller?

**Comment by gabescarbrough** [comment]
``` ruby
    def palette_params
      params.require(:palette).permit(:palette_name, :color1, :color2, :color3, :color4, :color5)
    end
```

**Comment by gaand** [comment]
Is the data you are sending valid JSON?

**Comment by gabescarbrough** [comment]
Aaaaah. Very simple mistake.

Should have been

``` sh
curl --include --request POST "http://localhost:3000/palettes" \
  --header "Content-Type: application/json" \
  --data '{
    "palette": {
      "palette_name": "Another Test",
      "color1": "hsl(0, 50%, 50%)",
      "color2": "hsl(10, 50%, 50%)",
      "color3": "hsl(20, 50%, 50%)",
      "color4": "hsl(30, 50%, 50%)",
      "color5": "hsl(40, 50%, 50%)"
    }
  }'
```

Last curl request had a comma trailing color5 which isn't valid JSON.
