### ISSUE TITLE
Still can't figure out what is wrong with my data structure for a create ajax request

### ISSUE THREAD

**Issue by baz1389** [ga-wdi-boston/full-stack-project#36]
Still getting the following error:

```


Started OPTIONS "/words" for ::1 at 2015-11-11 09:42:15 -0500


Started POST "/words" for ::1 at 2015-11-11 09:43:41 -0500
Processing by WordsController#create as HTML
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "a450ec1665e8e449bcd43e3e4c10cdbd"]]
Completed 400 Bad Request in 1ms (ActiveRecord: 0.3ms)

ActionController::ParameterMissing (param is missing or the value is empty: word):
  app/controllers/words_controller.rb:42:in `word_params'
  app/controllers/words_controller.rb:17:in `create'


  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.5ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.8ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (45.2ms)


```

**Comment by srhoulam** [comment]
Paste your AJAX call, Ben.

**Comment by baz1389** [comment]
```
$('#createNew').on('submit', function(e) {
    var word = {
      name: $('#exampleWordInput').val(),
      definition: $('#exampleDefinition').val(),
      sample_sentence: $('#exampleSentence').val(),
      user_id: user.id
    };
    debugger;
    var token = user.token;
    // var data = wrap('w', wordObj);
    // {"word" : { ... } }
    mwbapi.createWord(word, token, callback);
    debugger;
    e.preventDefault();
  });
```

```
createWord: function (word, token, callback) {
    this.ajax({
      method: 'POST',
      url: this.mwb + '/words',
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/  json; charset=utf-8',
      data: JSON.stringify(word),
      dataType: 'json',
    }, callback);
  }
```

**Comment by srhoulam** [comment]
Remove the space(s) between `'application/` and `json; charset=utf-8'`. `application/json` is one word.

**Comment by baz1389** [comment]
Even with that change, I'm still getting the original error (see above).

**Comment by srhoulam** [comment]
I'll come help.

**Comment by baz1389** [comment]
Problem has been solved. 

```
var word = {
      word : {
      name: $('#exampleWordInput').val(),
      definition: $('#exampleDefinition').val(),
      sample_sentence: $('#exampleSentence').val(),
      user_id: user.id
      }
```

the variable word needed an object key named word with a value of an object
