### ISSUE TITLE
AJAX POST request to Join Table not getting data

### ISSUE THREAD

**Issue by jordanallain** [ga-wdi-boston/full-stack-project#382]
i think i'm close to getting this, searched a lot of the closed issues but couldn't quite get there. i have a join table that i am trying to post to. the request goes through but it doesn't get the player_id for some reason. here is the response from the server

``` sh
Started POST "/favorites" for ::1 at 2016-08-21 23:54:46 -0400
Processing by FavoritesController#create as */*
  Parameters: {"favorite"=>{"player_id"=>"8"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "f90c3dc24927a3d000ad1610adbb91e9"]]
   (0.1ms)  BEGIN
  SQL (0.2ms)  INSERT INTO "favorites" ("user_id", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["user_id", 4], ["created_at", "2016-08-22 03:54:46.420054"], ["updated_at", "2016-08-22 03:54:46.420054"]]
   (1.3ms)  COMMIT
[active_model_serializers] Rendered FavoriteSerializer with ActiveModelSerializers::Adapter::Json (0.37ms)
Completed 201 Created in 6ms (Views: 0.9ms | ActiveRecord: 1.8ms)
```

the table is 'favorites', it is getting the correct user_id. it says 

``` sh
'Parameters: {"favorite" =>{"player_id=>"8"}}
```

which is the correct player_id but it also says

``` sh
SQL (0.2ms)  INSERT INTO "favorites" ("user_id", "created_at", "updated_at")
```

and checking in the database confirms that it has player_id: null

here is my ajax request

``` js
const addPlayer = (data) => {
  console.log("addPlayer data = " + data);
  return $.ajax({
    url: app.api + 'favorites',
    method: "POST",
    headers: {
      Authorization: 'Token token=' + app.user.token,
    },
    data: {
      favorite: {
        player_id: data
      }
  }});
};
```

i have tried a few different configurations of this but can't seem to get it. could i get a nudge in the right direction? let me know what other code you need from me.

**Comment by laurenfazah** [comment]
Can you post your Rails models?

**Comment by jordanallain** [comment]
``` js
class Favorite < ActiveRecord::Base
  belongs_to :user, inverse_of: :favorites
  belongs_to :player, inverse_of: :favorites
end
```

``` js
class Player < ActiveRecord::Base
  has_many :users, through: :favorites
  has_many :favorites
end
```

``` js
class User < ActiveRecord::Base
  include Authentication
  has_many :players, through: :favorites
  has_many :favorites
end
```

also i think i should mention i used that line of code that you told cliff to remove from his controller.

``` js
if params[:favorites]
```

when i delete this from the controller i get a 500 error response from my server

``` sh
ArgumentError (wrong number of arguments (given 3, expected 1)):
  app/controllers/favorites_controller.rb:57:in `favorite_params'
  app/controllers/favorites_controller.rb:21:in `create'
```

**Comment by jordanallain** [comment]
also i changed my controller to be

``` js
def favorite_params
    params.require(:favorite, :user_id, :player_id)
end
```

originally it was

``` js
  def favorite_params
    params.require(:favorite).permit(:user_id, :player_id)
  end
```

thinking that would at least stop the POST from going through if it didn't get the player_id but it didn't

**Comment by gaand** [comment]
Please post the create action from the controller.

**Comment by jordanallain** [comment]
``` js
  def create
    @favorite = current_user.favorites.build(favorite_params)

    if @favorite.save
      render json: @favorite, status: :created, location: @favorite
    else
      render json: @favorite.errors, status: :unprocessable_entity
    end
  end
```

**Comment by gaand** [comment]
This would seem to be the correct strong params:

``` ruby
def favorite_params
    params.require(:favorite).permit(:player_id)
end
```

Please try this one change and then comment with the result.

**Comment by jordanallain** [comment]
Wow that seemed to fix it, thank you. i'm not sure why it did though.

**Comment by laurenfazah** [comment]
Awesome - could you close if fixed? @jordanallain

**Comment by jordanallain** [comment]
yeah totally should we mention why that fixed it or should i just figure it out?

**Comment by laurenfazah** [comment]
@jordanallain Sorry, just saw this. Up to you. If you have time we can figure it out, if not we can look into it post-project 2
