### ISSUE TITLE
ActionController::RoutingError (No route matches [OPTIONS] "/presets/1"):  ...... again

### ISSUE THREAD

**Issue by cdelsoin** [ga-wdi-boston/full-stack-project#390]
i am trying to send a patch but i am getting that error in my rails server and 

```
XMLHttpRequest cannot load http://localhost:3000/presets/1. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.
```

api.js

```
const changePresetName = function (id, newName){
  return $.ajax ({
    url: app.api + '/presets/' + id,
    method: 'UPDATE',
    headers: {
      Authorization: 'Token token=' + app.user.token
    },
    data: {
      "preset": {
        "name": newName
      }
    }
  });
};
```

events.js

```
const onChangePresetName = function changePresetName() {
  let newName = $('.update-input').prop('value');
  let id = $('.update').prop('id');
  api.changePresetName(id, newName)
    .done(ui.success)
    .fail(ui.failure);
};
```

ui.js

```
const changePresetNameSuccess = (data) => {
  const showPresets = require('../templates/presets.handlebars');
  $('.presets-container').html(showPresets({
    presets: data.presets
  }));
};
```

preset_controller.rb

```
  def update
    # @preset = current_user.presets.find(params[:id])

    if @preset.update(preset_params)
      head :no_content
    else
      render json: @preset.errors, status: :unprocessable_entity
    end
  end

  def set_preset
    @preset = Preset.find(params[:id])
    # @preset = current_user.presets.find(params[:id])
  end

  def preset_params
    params.require(:preset).permit(:name, :rain, :fire, :thunder, :crickets, :birds, :coffee, :waves, :bowl)
  end
```

**Comment by cdelsoin** [comment]
route.rb

```
Rails.application.routes.draw do
  resources :presets, except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

**Comment by cdelsoin** [comment]
newName and id have the correct values

**Comment by laurenfazah** [comment]
Is this only happening with this request? All other AJAX requests are okay?

**Comment by cdelsoin** [comment]
yes

**Comment by laurenfazah** [comment]
Is there output in your rails server from the request?

**Comment by cdelsoin** [comment]
```
Started OPTIONS "/presets/35" for ::1 at 2016-08-22 19:28:53 -0400

ActionController::RoutingError (No route matches [OPTIONS] "/presets/35"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.5ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/routes/_table.html.erb (2.4ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (85.6ms)


```

**Comment by laurenfazah** [comment]
So `No route matches [OPTIONS]` should make you think that the type of request is coming in wrong. Take a look at your AJAX request. What looks wrong about this?

`method: 'UPDATE',`

**Comment by cdelsoin** [comment]
gotcha. I changed UPDATE to PATCH. Thank you!
