### ISSUE TITLE
Naming problem / incomplete model

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/full-stack-project#415]
hi,

I am having trouble calling call requests after adding authentication to the tokens in terminal. It is the naming (First I used user_stories, but my terminal -sometimes- changes it to UserStory like in my modal.

**Error:**

```
Started POST "/user_stories" for ::1 at 2016-10-03 13:20:36 -0400
Processing by UserStoriesController#create as */*
  Parameters: {"userstory"=>{"role"=>"visitor", "action"=>"play", "goal"=>"I do not want to register"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "2c0a8856b0e4f441d3eab8031539400b"]]
Completed 500 Internal Server Error in 18ms (ActiveRecord: 1.5ms)

NoMethodError (undefined method `userstories' for #<User:0x007fcf5d758d50>):
  app/controllers/user_stories_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.4ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (46.8ms)
```

**user_stories.sh**

```
#create
curl --include --request POST http://localhost:3000/user_stories \
  --header "Authorization: Token token=BAhJIiUyYzBhODg1NmIwZTRmNDQxZDNlYWI4MDMxNTM5NDAwYgY6BkVG--da28d67875224af25ced7d02223ee29267df53e5" \
  --header "Content-Type: application/json" \
  --data '{
    "user_story": {
      "role": "visitor",
      "action": "play",
      "goal": "I do not want to register"
    }
  }'
```

**user_stories_controller.rb**

```
class UserStoriesController < ProtectedController
  before_action :set_user_story, only: [:show, :update, :destroy]
```

```
  def create
    @user_story = current_user.userstories.build(user_story_params)

    if @user_story.save
      render json: @user_story, status: :created, location: @user_story
    else
      render json: @user_story.errors, status: :unprocessable_entity
    end
  end
```

```
  private

  def set_user_story
    @user_story = current_user.userstories.find(params[:id])
  end

  def user_story_params
    params.require(:user_story).permit(:role, :string, :action, :goal, :project_id)
  end
end
```

**user_story.rb**

```
class UserStory < ActiveRecord::Base
  belongs_to :project
end
```

My projects' table curl requests work fine. And I make sure to change tokens every time I log in. Other naming I've tried to change in my user_stories_controller.rb include: userstories, userstory, userstorys, user_stories, UserStory...

**Comment by payne-chris-r** [comment]
Are you sure that this output:

```
#create
curl --include --request POST http://localhost:3000/user_stories \
  --header "Authorization: Token token=BAhJIiUyYzBhODg1NmIwZTRmNDQxZDNlYWI4MDMxNTM5NDAwYgY6BkVG--da28d67875224af25ced7d02223ee29267df53e5" \
  --header "Content-Type: application/json" \
  --data '{
    "user_story": {
      "role": "visitor",
      "action": "play",
      "goal": "I do not want to register"
    }
  }'
```

produces this response:

```
Started POST "/user_stories" for ::1 at 2016-10-03 13:20:36 -0400
Processing by UserStoriesController#create as */*
  Parameters: {"userstory"=>{"role"=>"visitor", "action"=>"play", "goal"=>"I do not want to register"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "2c0a8856b0e4f441d3eab8031539400b"]]
Completed 500 Internal Server Error in 18ms (ActiveRecord: 1.5ms)
```

**Comment by payne-chris-r** [comment]
You're dealing with two issues here as well.
The other is this: 

```
NoMethodError (undefined method `userstories' for #<User:0x007fcf5d758d50>):
  app/controllers/user_stories_controller.rb:21:in `create'
```

**Comment by jrhorn424** [comment]
Yep. Look at your `user_story_params` and then look at the `JSON` the server said it received... it doesn't quite match.

**Comment by viohlet** [comment]
Thanks, Jeff. Caught the extra `:string` element. Still not sure about the errors mentioned, Chris. Will keep trying.

**Comment by payne-chris-r** [comment]
What is the method `userstories` in `user_stories_controller.rb:21 create`? Why isn't it defined? What is ruby telling you?

**Comment by jrhorn424** [comment]
I appreciate that Chris is not trying to directly give you the answer.

Please do what I suggested earlier. Paste them into a response in this issue next to each other, and reply. See if that helps.

> Look at your user_story_params and then look at the JSON the server said it received...

**Comment by viohlet** [comment]
Hi guys,

Thank you for your replies. I've been thinking about this and I must be really missing something...

My user_story_params :

```
  def user_story_params
    params.require(:user_story).permit(:role, :action, :goal, :project_id)
  end
```

The JSON I received:

```
Processing by UserStoriesController#create as */*
  Parameters: {"userstory"=>{"role"=>"visitor", "action"=>"play", "goal"=>"I do not want to register"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "2c0a8856b0e4f441d3eab8031539400b"]]
Completed 500 Internal Server Error in 18ms (ActiveRecord: 1.5ms)
```

So I thought, maybe it's my project_id that needs to be in my curl request. However, when I created a curl request without the tokens from sign-up, I did not need it and it just showed as "null." So I am not sure if that's it. But I decided to give it a try anyways and created a new project which gave me an id of 9. I got more html errors, and this is what my server looks like:

```
Started POST "/user_stories" for ::1 at 2016-10-04 01:03:43 -0400
Error occurred while parsing request parameters.
Contents:

{
    "user_story": {
      "role": "visitor",
      "action": "play",
      "goal": "I do not want to register"
      "project_id": "9"
    }
  }

ActionDispatch::ParamsParser::ParseError (822: unexpected token at '{
    "user_story": {
      "role": "visitor",
      "action": "play",
      "goal": "I do not want to register"
      "project_id": "9"
    }
  }'):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:53:in `rescue in parse_formatted_parameters'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:32:in `parse_formatted_parameters'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:23:in `call'
  activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (18.2ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.4ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (81.3ms)
```

Just thought I'd update y'all on this. Even though I'm not getting it T_T
Thank you for your patience. I will keep at it.

-V

**Comment by payne-chris-r** [comment]
Please replace the token with a valid one, and run this curl script:

``` bash
curl --include --request POST http://localhost:3000/user_stories \
  --header "Authorization: Token token=BAhJIiUyYzBhODg1NmIwZTRmNDQxZDNlYWI4MDMxNTM5NDAwYgY6BkVG--da28d67875224af25ced7d02223ee29267df53e5" \
  --header "Content-Type: application/json" \
  --data '{
    "user_story": {
      "role": "visitor",
      "action": "play",
      "goal": "I do not want to register"
    }
  }'
```

and then post the output below.

**Comment by viohlet** [comment]
Thanks! Output:

```
Started POST "/user_stories" for ::1 at 2016-10-04 09:08:59 -0400
Processing by UserStoriesController#create as */*
  Parameters: {"user_story"=>{"role"=>"visitor", "action"=>"play", "goal"=>"I do not want to register"}}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "66aead9e5a4ea5a88e3d60c17a03eec7"]]
Completed 500 Internal Server Error in 19ms (ActiveRecord: 0.6ms)

NoMethodError (undefined method `userstories' for #<User:0x007fcb01d862f0>):
  app/controllers/user_stories_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (11.1ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.5ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (62.4ms)
```

</3

**Comment by payne-chris-r** [comment]
Ok, cool
Do you see how the first response you posted:
`Parameters: {"userstory"`
is different than the last one:
`Parameters: {"user_story"`
???

That `_` is an important distinction for rails!

You're now getting another issue, which I alluded to earlier:

`NoMethodError (undefined method `userstories' for #<User:0x007fcf5d758d50>):
  app/controllers/user_stories_controller.rb:21:in `create'`

**Comment by jrhorn424** [comment]
Please paste your `User` and `UserStory` models, as well as your ERD.

**Comment by viohlet** [comment]
Models>user.rb

```
class User < ActiveRecord::Base
  include Authentication
  has_many :examples
  has_many :projects
end
```

Models>user_story.rb

```
class UserStory < ActiveRecord::Base
  belongs_to :project
end
```

ERD:
![fullsizerender 12](https://cloud.githubusercontent.com/assets/17170398/19076444/c73a00b6-8a16-11e6-9637-21ab5293d3b6.jpg)

Thank you for your help!

**Comment by jrhorn424** [comment]
Your relationships are not complete. Please come see me and bring a notebook so you can post your resolution here.

**Comment by viohlet** [comment]
Gracias @payne-chris-r for spotting the params user_story/userstory different! And thanks @jrhorn424 for walking through this issue with me one-on-one.

Solution:
```
  def create
    @user_story = UserStory.new(user_story_params)

    if @user_story.save
      render json: @user_story, status: :created, location: @user_story
    else
      render json: @user_story.errors, status: :unprocessable_entity
    end
  end
```

Change 
`@user_story = current_user.userstories.build(user_story_params)` for 
`@user_story = UserStory.new(user_story_params)`

Reasoning: 
My user_story params do not recognize current_user. Also, the name of my modal is UserStory, and not userstories. Finally, I am not building a child out of a parent, but creating a child and then saving it on the next line `if @user_story.save` and so `new` is required and not `build`.

Lesson: Learn the meaning what I am coding, and templates are not my friend.

**Comment by viohlet** [comment]
Gracias @payne-chris-r for spotting the params user_story/userstory difference! And thanks @jrhorn424 for walking through this issue with me one-on-one.

Solution:

```
  def create
    @user_story = UserStory.new(user_story_params)

    if @user_story.save
      render json: @user_story, status: :created, location: @user_story
    else
      render json: @user_story.errors, status: :unprocessable_entity
    end
  end
```

Change 
`@user_story = current_user.userstories.build(user_story_params)` for 
`@user_story = UserStory.new(user_story_params)`

Reasoning: 
My user_story params do not recognize current_user. Also, the name of my modal is UserStory, and not userstories. Finally, I am not building a child out of a parent, but creating a child and then saving it on the next line `if @user_story.save` and so `new` is required and not `build`.

Lesson: Learn the meaning behind what I am coding, and templates are not my friend.
