### ISSUE TITLE
Trying to deploy

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#433]
I've followed all the directions in the backend and frontend deployment guides. However, I can't sign in after doing so. I've gotten the following error messages:

```
vendor.bundle.js:9646 POST https://booksucks.herokuapp.com/sign-in 401 (Unauthorized)
```

**Comment by berziiii** [comment]
Did you set a client_url variable in the heroku config var settings to tell your API to accept requests from your deployed client?

**Comment by julie1013** [comment]
Tried just now with`https://julie1013.github.io` and `https://julie1013.github.io/booksucks-front-end/`

Still same error.

**Comment by jrhorn424** [comment]
Your second URL is incorrect. Use the first.

In order to continue debugging, if you're getting the same error, you'll need to inspect `heroku logs`.

Did you sign up for a new account first? You can't sign in until you sign up. The databases on your machine and on heroku are different.

**Comment by jrhorn424** [comment]
Please paste `heroku logs` output.

**Comment by julie1013** [comment]
I've had Heroku for months now. I went into Heroku through their website and did what Brian said.

From `heroku logs`

```
2016-10-04T17:10:11.609117+00:00 app[web.1]: Processing by BooksController#index as */*
2016-10-04T17:10:11.610666+00:00 app[web.1]:   Book Load (0.6ms)  SELECT "books".* FROM "books"
2016-10-04T17:10:11.613504+00:00 app[web.1]: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Book::ActiveRecord_Relation (1.92ms)
2016-10-04T17:10:11.613729+00:00 app[web.1]: Completed 200 OK in 4ms (Views: 3.5ms | ActiveRecord: 0.6ms)
2016-10-04T17:10:18.249525+00:00 heroku[router]: at=info method=POST path="/sign-in" host=booksucks.herokuapp.com request_id=9c402434-3774-4fbf-893e-00c25e3b353f fwd="74.118.24.163" dyno=web.1 connect=1ms service=32ms status=401 bytes=625
2016-10-04T17:10:18.227347+00:00 app[web.1]: Started POST "/sign-in" for 74.118.24.163 at 2016-10-04 17:10:18 +0000
2016-10-04T17:10:18.244351+00:00 app[web.1]: Processing by UsersController#signin as */*
2016-10-04T17:10:18.244539+00:00 app[web.1]:   Parameters: {"credentials"=>{"email"=>"dog@dog.com", "password"=>"[FILTERED]"}}
2016-10-04T17:10:18.246912+00:00 app[web.1]:   User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "dog@dog.com"]]
2016-10-04T17:10:18.247339+00:00 app[web.1]: Completed 401 Unauthorized in 3ms (ActiveRecord: 1.3ms)
2016-10-04T17:28:37.399021+00:00 heroku[web.1]: Restarting
2016-10-04T17:28:37.402688+00:00 heroku[web.1]: State changed from up to starting
2016-10-04T17:28:37.109692+00:00 heroku[api]: Set CLIENT_URL config vars by julie1380@verizon.net
2016-10-04T17:28:37.109814+00:00 heroku[api]: Release v9 created by julie1380@verizon.net
2016-10-04T17:28:40.479276+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-10-04T17:28:40.723475+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-10-04T17:28:41.251473+00:00 app[web.1]: [2016-10-04 17:28:41] FATAL SignalException: SIGTERM
2016-10-04T17:28:41.251483+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:177:in `select'
2016-10-04T17:28:41.251487+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:177:in `block in start'
2016-10-04T17:28:41.251487+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:33:in `start'
2016-10-04T17:28:41.251488+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:164:in `start'
2016-10-04T17:28:41.251489+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
2016-10-04T17:28:41.251489+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
2016-10-04T17:28:41.251490+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
2016-10-04T17:28:41.251491+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2016-10-04T17:28:41.251492+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
2016-10-04T17:28:41.251493+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
2016-10-04T17:28:41.251493+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2016-10-04T17:28:41.251494+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
2016-10-04T17:28:41.251495+00:00 app[web.1]:    bin/rails:9:in `require'
2016-10-04T17:28:41.251495+00:00 app[web.1]:    bin/rails:9:in `<main>'
2016-10-04T17:28:41.252664+00:00 app[web.1]: [2016-10-04 17:28:41] INFO  going to shutdown ...
2016-10-04T17:28:41.252705+00:00 app[web.1]: [2016-10-04 17:28:41] INFO  WEBrick::HTTPServer#start done.
2016-10-04T17:28:41.252931+00:00 app[web.1]: Exiting
2016-10-04T17:28:41.373192+00:00 heroku[web.1]: Process exited with status 143
2016-10-04T17:28:42.161851+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 10368 -e production`
2016-10-04T17:28:44.882509+00:00 app[web.1]: [2016-10-04 17:28:44] INFO  WEBrick 1.3.1
2016-10-04T17:28:44.882545+00:00 app[web.1]: [2016-10-04 17:28:44] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
2016-10-04T17:28:44.882838+00:00 app[web.1]: [2016-10-04 17:28:44] INFO  WEBrick::HTTPServer#start: pid=3 port=10368
2016-10-04T17:28:45.019639+00:00 heroku[web.1]: State changed from starting to up
2016-10-04T17:28:46.892005+00:00 heroku[router]: at=info method=GET path="/books" host=booksucks.herokuapp.com request_id=01c4b2f5-2910-49e4-b4c1-ad34c18a15ea fwd="74.118.24.163" dyno=web.1 connect=0ms service=65ms status=200 bytes=1383
2016-10-04T17:28:46.835762+00:00 app[web.1]: => Booting WEBrick
2016-10-04T17:28:46.835783+00:00 app[web.1]: => Run `rails server -h` for more startup options
2016-10-04T17:28:46.835781+00:00 app[web.1]: => Rails 4.2.7.1 application starting in production on http://0.0.0.0:10368
2016-10-04T17:28:46.835783+00:00 app[web.1]: => Ctrl-C to shutdown server
2016-10-04T17:28:46.835784+00:00 app[web.1]: Started GET "/books" for 74.118.24.163 at 2016-10-04 17:28:46 +0000
2016-10-04T17:28:46.875649+00:00 app[web.1]: Processing by BooksController#index as */*
2016-10-04T17:28:46.879696+00:00 app[web.1]:   Book Load (1.8ms)  SELECT "books".* FROM "books"
2016-10-04T17:28:46.895302+00:00 app[web.1]: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Book::ActiveRecord_Relation (1.08ms)
2016-10-04T17:28:46.895454+00:00 app[web.1]: Completed 200 OK in 20ms (Views: 10.0ms | ActiveRecord: 9.0ms)
2016-10-04T17:28:51.646921+00:00 heroku[router]: at=info method=POST path="/sign-in" host=booksucks.herokuapp.com request_id=aa351dd2-f302-4723-b6af-4d0fbcf7524b fwd="74.118.24.163" dyno=web.1 connect=2ms service=23ms status=401 bytes=625
2016-10-04T17:28:51.631003+00:00 app[web.1]: Started POST "/sign-in" for 74.118.24.163 at 2016-10-04 17:28:51 +0000
2016-10-04T17:28:51.636170+00:00 app[web.1]: Processing by UsersController#signin as */*
2016-10-04T17:28:51.636223+00:00 app[web.1]:   Parameters: {"credentials"=>{"email"=>"dog@dog.com", "password"=>"[FILTERED]"}}
2016-10-04T17:28:51.650271+00:00 app[web.1]:   User Load (1.8ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "dog@dog.com"]]
2016-10-04T17:28:51.650601+00:00 app[web.1]: Completed 401 Unauthorized in 14ms (ActiveRecord: 6.1ms)
2016-10-04T17:29:09.107262+00:00 heroku[web.1]: Restarting
2016-10-04T17:29:09.108149+00:00 heroku[web.1]: State changed from up to starting
2016-10-04T17:29:08.252938+00:00 heroku[api]: Set CLIENT_URL config vars by julie1380@verizon.net
2016-10-04T17:29:08.253023+00:00 heroku[api]: Release v10 created by julie1380@verizon.net
2016-10-04T17:29:12.278411+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-10-04T17:29:12.998299+00:00 app[web.1]: [2016-10-04 17:29:12] FATAL SignalException: SIGTERM
2016-10-04T17:29:12.998321+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:177:in `block in start'
2016-10-04T17:29:12.998320+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:177:in `select'
2016-10-04T17:29:12.998322+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:33:in `start'
2016-10-04T17:29:12.998323+00:00 app[web.1]:    /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:164:in `start'
2016-10-04T17:29:12.998324+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:34:in `run'
2016-10-04T17:29:12.998325+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
2016-10-04T17:29:12.998324+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
2016-10-04T17:29:12.998326+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2016-10-04T17:29:12.998327+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
2016-10-04T17:29:12.998328+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
2016-10-04T17:29:12.998328+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
2016-10-04T17:29:12.998329+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
2016-10-04T17:29:12.998330+00:00 app[web.1]:    bin/rails:9:in `require'
2016-10-04T17:29:12.998331+00:00 app[web.1]:    bin/rails:9:in `<main>'
2016-10-04T17:29:12.998388+00:00 app[web.1]: [2016-10-04 17:29:12] INFO  going to shutdown ...
2016-10-04T17:29:12.998454+00:00 app[web.1]: [2016-10-04 17:29:12] INFO  WEBrick::HTTPServer#start done.
2016-10-04T17:29:12.998479+00:00 app[web.1]: Exiting
2016-10-04T17:29:13.147565+00:00 heroku[web.1]: Process exited with status 143
2016-10-04T17:29:14.843088+00:00 app[web.1]: [2016-10-04 17:29:14] INFO  WEBrick 1.3.1
2016-10-04T17:29:14.843111+00:00 app[web.1]: [2016-10-04 17:29:14] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux]
2016-10-04T17:29:14.843313+00:00 app[web.1]: [2016-10-04 17:29:14] INFO  WEBrick::HTTPServer#start: pid=3 port=13285
2016-10-04T17:29:15.243581+00:00 heroku[web.1]: State changed from starting to up
2016-10-04T17:29:11.596865+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 13285 -e production`
2016-10-04T17:29:16.921391+00:00 heroku[router]: at=info method=GET path="/books" host=booksucks.herokuapp.com request_id=e07712a5-70d7-4255-b8a0-99f1c7def909 fwd="74.118.24.163" dyno=web.1 connect=0ms service=70ms status=200 bytes=1383
2016-10-04T17:29:16.855811+00:00 app[web.1]: => Booting WEBrick
2016-10-04T17:29:16.855833+00:00 app[web.1]: => Rails 4.2.7.1 application starting in production on http://0.0.0.0:13285
2016-10-04T17:29:16.855834+00:00 app[web.1]: => Run `rails server -h` for more startup options
2016-10-04T17:29:16.855835+00:00 app[web.1]: => Ctrl-C to shutdown server
2016-10-04T17:29:16.855835+00:00 app[web.1]: Started GET "/books" for 74.118.24.163 at 2016-10-04 17:29:16 +0000
2016-10-04T17:29:16.897837+00:00 app[web.1]: Processing by BooksController#index as */*
2016-10-04T17:29:16.902271+00:00 app[web.1]:   Book Load (1.9ms)  SELECT "books".* FROM "books"
2016-10-04T17:29:16.918782+00:00 app[web.1]: [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Book::ActiveRecord_Relation (1.25ms)
2016-10-04T17:29:16.918997+00:00 app[web.1]: Completed 200 OK in 21ms (Views: 11.8ms | ActiveRecord: 8.3ms)
2016-10-04T17:29:20.216912+00:00 heroku[router]: at=info method=POST path="/sign-in" host=booksucks.herokuapp.com request_id=52a8bef6-e129-428a-9bc9-6283815add21 fwd="74.118.24.163" dyno=web.1 connect=0ms service=23ms status=401 bytes=625
2016-10-04T17:29:20.197197+00:00 app[web.1]: Started POST "/sign-in" for 74.118.24.163 at 2016-10-04 17:29:20 +0000
2016-10-04T17:29:20.202786+00:00 app[web.1]: Processing by UsersController#signin as */*
2016-10-04T17:29:20.202853+00:00 app[web.1]:   Parameters: {"credentials"=>{"email"=>"dog@dog.com", "password"=>"[FILTERED]"}}
2016-10-04T17:29:20.215387+00:00 app[web.1]:   User Load (1.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "dog@dog.com"]]
2016-10-04T17:29:20.215653+00:00 app[web.1]: Completed 401 Unauthorized in 13ms (ActiveRecord: 5.0ms)
```

**Comment by payne-chris-r** [comment]
Where does the user (`dog@dog.com`) have an account?

**Comment by julie1013** [comment]
HAHAHHAHAH! Damn! I forgot you had to sign up all over again when deploying! THat's it! Thanks!

**Comment by jrhorn424** [comment]
> HAHAHHAHAH! Damn! I forgot you had to sign up all over again when deploying! THat's it! Thanks!

I said that.

> Did you sign up for a new account first? You can't sign in until you sign up. The databases on your machine and on heroku are different.

**Please** read more carefully.

**Comment by julie1013** [comment]
I misunderstood what you were referring to when you said that. I thought you meant signing up for the Heroku account.
