### ISSUE TITLE
400 bad request when adding data from a form

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/full-stack-project#442]
rails server output

``` .html

Started OPTIONS "/events/" for ::1 at 2016-10-04 15:46:08 -0400


Started POST "/events/" for ::1 at 2016-10-04 15:46:08 -0400
Processing by EventsController#create as */*
  Parameters: {"band"=>"1", "venue"=>"1", "date"=>"1111-01-01", "setlist"=>"1", "submit"=>"Save!"}
Completed 400 Bad Request in 1ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: event):
  app/controllers/events_controller.rb:57:in `event_params'
  app/controllers/events_controller.rb:21:in `create'


  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.8ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.3ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.6ms)
  Rendered /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (33.8ms)
```

curl request creates event

``` .rb
curl --include --request POST http://localhost:3000/events \
  --header "Content-Type: application/json" \
  --data '{
    "event": {
      "band": "Your favorite band really sucks",
      "date": "2016-11-09",
      "venue": "Thunder Road",
      "setlist": "lots of songs"
    }
  }'
```

**Comment by payne-chris-r** [comment]
You and Pete need to have a pow-wow

**Comment by payne-chris-r** [comment]
See #438

**Comment by rosmith76** [comment]
@payne-chris-r i don't think that is the issue. I had a similar problem earlier, so I checked params.

``` .rb
  def event_params
    params.require(:event).permit(:band, :date, :venue, :setlist)
  end
```

**Comment by berziiii** [comment]
What is the form structure like? please provide the html for the form.

**Comment by rosmith76** [comment]
``` .html
    <div class="modal fade" id="add-events-button" tabindex="-1"role="dialog" aria-labelledby="addEventsModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <form id="add-event">
           <fieldset>
             <legend>Add Show</legend>
             <input type= "text" name= "band" placeholder="Band Name">
             <input type= "text" name= "venue" placeholder="Venue Name">
             <input type= "date" name= "date" placeholder="Show Date yyyy-mm-dd">
             <input type= "text" name= "setlist" placeholder="Setlist">
             <input type="submit" name="submit" value="Save!">
           </fieldset>
         </form>
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal"
             aria-label="Close"><span aria-hidden="true">&times;</span></button>
         </div>
       </div>
     </div>
   </div>
```

**Comment by payne-chris-r** [comment]
Please console.log(data) inside the api request to see what the object looks like.

**Comment by jrhorn424** [comment]
Your error is here, @rosmith76. The `name` is not correct.

``` diff
- <input type= "text" name= "band" placeholder="Band Name">
+ <input type= "text" name= "[something_goes_here]band" placeholder="Band Name">
```

Make that change everywhere.

**Comment by rosmith76** [comment]
``` .html
<input type= "text" name= "[event]band" placeholder="Band Name">
```

Once I figure out it was event not events it worked.
