### ISSUE TITLE
Trying to add books to master list on Heroku

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/full-stack-project#465]
Trying to manually (ie curl) add books to master list in Heroku. I took down the security features on the Books controller, so I temporarily have it like this:

``` ruby
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :update, :destroy]
  def index
    @books = Book.all

    render json: @books
  end

  def show
    render json: Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      render json: @book, status: :created, location: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      head :no_content
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy

    head :no_content
  end

  # def delete_user_book
  #   @book = current_user.book
  #   @book.destroy
  #
  #   head :no_content
  # end

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author)
  end

  private :set_book, :book_params
end
```

Delete curl request that's giving me a 500 error:

``` sh
curl --include --request DELETE https://booksucks.herokuapp.com/books/1 \
--header "Authorization: Token token=BAhJIiUzYmFmYTRmMjUxN2Q4MTBlYTk2Mjk1OGQ4NjI3Yjc2ZgY6BkVG--4979d622f021f2eaef8d418e7ca5795c00424d8c" \
--header "Content-Type: application/json"
```

**Comment by jrhorn424** [comment]
What's the 500? Please paste the relevant section of your `heroku logs`.

**Comment by julie1013** [comment]
``` sh
2016-10-13T02:10:21.152538+00:00 app[web.1]: Started DELETE "/books/1" for 73.142.162.110 at 2016-10-13 02:10:21 +0000
2016-10-13T02:10:21.155247+00:00 app[web.1]: Processing by BooksController#destroy as */*
2016-10-13T02:10:21.155299+00:00 app[web.1]:   Parameters: {"id"=>"1"}
2016-10-13T02:10:21.161924+00:00 app[web.1]: Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.0ms)
2016-10-13T02:10:21.163754+00:00 app[web.1]: 
2016-10-13T02:10:21.163756+00:00 app[web.1]: NameError (undefined local variable or method `books' for #<BooksController:0x007fe0101f5430>
2016-10-13T02:10:21.163757+00:00 app[web.1]: Did you mean?  books_url):
2016-10-13T02:10:21.163758+00:00 app[web.1]:   app/controllers/books_controller.rb:45:in `set_book'
2016-10-13T02:10:21.163759+00:00 app[web.1]: 
2016-10-13T02:10:21.163759+00:00 app[web.1]: 
```

**Comment by jrhorn424** [comment]
This error message:

``` sh
2016-10-13T02:10:21.163756+00:00 app[web.1]: NameError (undefined local variable or method `books' for #<BooksController:0x007fe0101f5430>
```

Does not match this method:

``` ruby
  def set_book
    @book = Book.find(params[:id])
  end
```

Did you change code and forget to redeploy?

**Comment by julie1013** [comment]
It appears you're right. OK, so I've successfully deleted the old books, so now I'm trying to add the new ones:

``` sh
curl --include --request POST https://booksucks.herokuapp.com/books \
--header "Authorization: Token token=BAhJIiU2OWYwOWM2Y2Q1MWIwMjA2MjVjZGM2NzhjNjU3MzY4NAY6BkVG--362ab53853ad31c62f71aba5b146354093bf1e59" \
--header "Content-Type: application/json"
  --data '{
    "book": {
      "title": "50 Shades of Grey",
      "author": "E. L. James"
    }
  }'
```

Got this error:

``` sh
2016-10-13T02:42:23.112465+00:00 app[web.1]: Started POST "/books" for 73.142.162.110 at 2016-10-13 02:42:23 +0000
2016-10-13T02:42:23.114381+00:00 app[web.1]: Processing by BooksController#create as */*
2016-10-13T02:42:23.114797+00:00 app[web.1]: Completed 400 Bad Request in 0ms (ActiveRecord: 0.0ms)
2016-10-13T02:42:23.115574+00:00 app[web.1]: 
2016-10-13T02:42:23.115575+00:00 app[web.1]: ActionController::ParameterMissing (param is missing or the value is empty: book):
2016-10-13T02:42:23.115576+00:00 app[web.1]:   app/controllers/books_controller.rb:14:in `create'
2016-10-13T02:42:23.115576+00:00 app[web.1]:   app/controllers/books_controller.rb:49:in `book_params'
2016-10-13T02:42:23.115577+00:00 app[web.1]: 
2016-10-13T02:42:23.115577+00:00 app[web.1]: 
```

**Comment by jrhorn424** [comment]
Doesn't look like any params are making it to the server. Can you spot the problem with your curl request? Look at the end of the line on the second header.

**Comment by julie1013** [comment]
Ah yes. Missing `\`
