### ISSUE TITLE
bootstrap table error

### ISSUE THREAD

**Issue by coffeeisamazing** [ga-wdi-boston/full-stack-project#472]
**Background**
I want to dynamically populate a bootstrap table with a JSON response.

**Issue**
I'm receiving the following error in console when trying to use the function.
```sh
jquery.js:3846 jQuery.Deferred exception: $(...).bootstrapTable is not a function TypeError: $(...).bootstrapTable is not a function
    at Object.getLocationTimeSuccess (http://localhost:7165/bundle.js:1781:16)
    at mightThrow (http://localhost:7165/dependencies.js:3680:30)
    at process (http://localhost:7165/dependencies.js:3748:13) undefined
```

**Steps**
- Followed installation steps per: http://bootstrap-table.wenzhixin.net.cn/getting-started/
- Added table to index.html with appropriate ID.
- Called function and attempted to populate first with API response and then directly with a JSON string.

**My Code**
_index.html_
```html
<!DOCTYPE html>
<html>
    <head>
      <title>Global Meeting Planner</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <script src="dependencies.js" type="text/javascript" charset="utf-8" defer></script>
      <script src="bundle.js" type="text/javascript" charset="utf-8" defer></script>
      <link rel="stylesheet" href="bootstrap-table.css">
      <link rel="stylesheet" href="bootstrap.min.css">
      <link rel="stylesheet" href="bootstrap-table.css">
      <script src="bootstrap-table.js"></script>
    </head>
    <body class="container-fluid">
      <h1>Global Meeting Planner</h1>
      <main><div id='content'></div></main>
      <aside><div id="user-message"></div></aside>
      <table id="table"></table>
    </body>
</html>
```
_planner-ui.js_
```js
const getLocationTimeSuccess = () => {
  console.log("Here!");
  $('#table').bootstrapTable({
      columns: [{
          field: 'id',
          title: 'Item ID'
      }, {
          field: 'name',
          title: 'Item Name'
      }, {
          field: 'price',
          title: 'Item Price'
      }],
      data: [{
          id: 1,
          name: 'Item 1',
          price: '$1'
      }, {
          id: 2,
          name: 'Item 2',
          price: '$2'
      }]
  });
};
```

**Comment by coffeeisamazing** [comment]
I'd like a 1-1 for this issue. Thanks!

**Comment by raq929** [comment]
I can do that!

**Comment by coffeeisamazing** [comment]
This is Caleb. :)

**Comment by gaand** [comment]
It doesn't appear that you're using the template as intended.

**Comment by coffeeisamazing** [comment]
Decided to use handlebars given my use case.
