### ISSUE TITLE
AJAX - responseText: "Cannot POST /undefined/sign-up↵", status: 404, statusText: "Not Found"}

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/full-stack-project#491]
I cannot figure out what is wrong with my AJAX request. I have three users made via cURL request that I can see in table form in bash, so I know my back end is working. However, when I try to fill in a form on my front end I get a 404 error telling me that 
```
Object {readyState: 4, responseText: "Cannot POST /undefined/sign-up↵", status: 404, statusText: "Not Found"}
```

My back end shows this, too:
```
Started POST "/sign-up" for ::1 at 2016-11-30 10:47:52 -0500
Processing by UsersController#signup as */*
Completed 400 Bad Request in 4ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/users_controller.rb:63:in `user_creds'
  app/controllers/users_controller.rb:7:in `signup'
```

I tried hard coding the url in api.js to ``` url: 'http://localhost:4741/sign-up' ``` rather than ``` url: app.host + '/sign-up' ``` which didn't resolve anything other than returning a slightly different error message of 

```
Object {readyState: 4, responseText: "<!DOCTYPE html>↵<html lang="en">↵<head>↵  <meta ch…>:</p> <pre>None</pre>↵↵</div>↵↵↵</body>↵</html>↵", status: 400, statusText: "Bad Request"}
```

II have credentials attached to each form entry in my HTML, too. What am i missing?
```
<form class="sign-up-form">
        <div class="col-md-6">
          <div class="form-group">
            <label for="InputEmail">Your Email</label>
            <div class="input-group">
              <input type="email" class="form-control" name="credentials[email]" id="InputEmail" placeholder="Enter Email" required>
              <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
            </div>
          </div>


          <div class="form-group">
            <label for="InputPassword">Your Password</label>
            <div class="input-group">
              <input type="password" class="form-control" id="InputPassword" name="credentials[password]" placeholder="Enter Password" required  >
              <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
            </div>
          </div>

          <div class="form-group">
            <label for="ConfirmPassword">Confirm Password</label>
            <div class="input-group">
              <input type="password" class="form-control" id="InputConfirmPassword" name="credentials[password_confirmation]" placeholder="Confirm Password" required  >
              <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
            </div>
          </div>
```

**Comment by kiraamaa** [comment]
I'm getting a new error now:
```
Started POST "/sign-up" for ::1 at 2016-11-30 11:51:34 -0500
Processing by UsersController#signup as */*
Completed 400 Bad Request in 10ms (ActiveRecord: 0.0ms)

ActionController::ParameterMissing (param is missing or the value is empty: credentials):
  app/controllers/users_controller.rb:63:in `user_creds'
  app/controllers/users_controller.rb:7:in `signup'


  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (10.1ms)
  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.4ms)
  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (10.3ms)
  Rendered /Users/kiraamaa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (88.9ms)
```
I put a console.log inside my onSignUp function and while the console is logging that an Object is created there is no data inside of it. Do I need to hard code the credentials into the AJAZ request?

Please help I feel like crying I've been working on this for so long.

**Comment by neugierige** [comment]
first of all, take a deeeeeeeeeeep breath...

could you share the curl request you used that _did_ work?

**Comment by neugierige** [comment]
By the way, the error in your 2nd post looks the same as the error in your 1st post. Did you mean to paste something else?

**Comment by kiraamaa** [comment]
This is the cURL request:
```
curl "http://localhost:4741/sign-up" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{
    "credentials": {
      "email": "'"blah@mail.com"'",
      "password": "'"open"'",
      "password_confirmation": "'"open"'"
    }
  }'

echo
```

**Comment by kiraamaa** [comment]
And I guess it is still showing the same error now that the url is actually pointing in the right direction.
The url was previously POSTing to "http://localhost:7165/undefined/sign-up".

**Comment by neugierige** [comment]
`param is missing or the value is empty: credentials`

If I were you, I would first determine whether the param is actually missing, or if the values you are submitting are empty.

**Comment by kiraamaa** [comment]
Neither should be true... By values do you mean the inputs into the actual form on the front end, because those are not empty? Params shouldn't be missing either

**Comment by neugierige** [comment]
I understand, have you tested it? maybe some console.logs?

**Comment by raq929** [comment]
Agreed, find out what data you are getting from 'getFormFields' and make sure it matches the data in the curl request.

**Comment by kiraamaa** [comment]
Okay after putting debuggers and console.logs I've found that while the onSignUp function is running and printing an Object in the console, the function isn't hitting the ui.success or .failure functions. How do I fix that?

**Comment by neugierige** [comment]
Is onSignUp part of the template? Or did you write it? In any case, can you share that code?

**Comment by kiraamaa** [comment]
onSignUp was taken from my auth folder on the tic-tac-toe project. It's inside my events.js file:
```
const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
    .then(ui.success)
    .catch(ui.failure);
  console.log(data);
};
```

**Comment by kiraamaa** [comment]
My credentials in Rails should match my HTML too.

Rails users_controller.rb:
```
def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation)
  end
```

HTML
```
<form class="sign-up-form">
        <div class="col-md-6">
          <div class="form-group">
            <label for="InputEmail">Your Email</label>
            <div class="input-group">
              <input type="email" name="credentials[email]" class="form-control" id="sign-up-email" placeholder="Enter Email" required>
              <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
            </div>
          </div>


          <div class="form-group">
            <label for="InputPassword">Your Password</label>
            <div class="input-group">
              <input type="password" name="credentials[password]" class="form-control" id="input-password" placeholder="Enter Password" required  >
              <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
            </div>
          </div>

          <div class="form-group">
            <label for="ConfirmPassword">Confirm Password</label>
            <div class="input-group">
              <input type="password" name="credentials[password_confirmation]" class="form-control" id="input-password" placeholder="Confirm Password" required  >
              <span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
            </div>
          </div>

          <button id="on-form-submit" class="btn wow tada btn-primary btn-embossed pull-right">Submit</button>

          <p id="sign-in-text">Already have an account? Sign in <a href="#" data-toggle="modal" data-target="#signInModal">here</a>.</p>
        </div>
      </form>
```

**Comment by raq929** [comment]
When you put a debugger in onSignUp, what does `data` look like? (You should be able to type `data` in the console and get the object back, if the debugger is after you define `data`)

**Comment by kiraamaa** [comment]
It's just and empty object: Object {}

This is what I used to debug:

```
const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
    .then(ui.success)
    .catch(ui.failure);
  console.log(data);
  debugger;
};
```

**Comment by kiraamaa** [comment]
I looked at issue 251 and maybe I have a similar problem? I tried to make similar/same edits and it didn't work
https://github.com/ga-wdi-boston/full-stack-project/issues/251

**Comment by neugierige** [comment]
Hmm this is interesting. If you haven't already, try going back to your tic-tac-toe project and see how that worked, and see what's different between that setup and what your have here.

**Comment by neugierige** [comment]
please close if resolved, even if the solution is a temporary workaround

**Comment by kiraamaa** [comment]
I fixed it by getting rid of the Bootstrap form entirely and just using my modals from my tic-tac-toe project that I knew worked. Thanks y'all.
