### ISSUE TITLE
Since adding current user getting error 500

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/full-stack-project#493]
Since adding what I thought would be current user functionality, I am getting server error error 500.

Exact error:
```sh
Started POST "/chores" for ::1 at 2016-11-30 12:47:57 -0500
Processing by ChoresController#create as */*
  Parameters: {"chore"=>{"name"=>"new", "due_date"=>"", "difficulty"=>""}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "9a979c0e120f25f3a01c5b57b1edd071"]]
Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.4ms)

ActiveRecord::UnknownAttributeError (unknown attribute 'user_id' for Chore.):
  app/controllers/chores_controller.rb:23:in `create'


  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (7.1ms)
  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.5ms)
  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.5ms)
  Rendered /Users/AlexKradin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (65.2ms)
```

what my controller looks like
```rb
class ChoresController < ProtectedController
  before_action :set_chore, only: [:show, :update, :destroy]

  def set_chore
    @chore = current_user.chores.find(params[:id])
  end

  def chore_params
    params.require(:chore).permit(:name, :due_date, :difficulty)
  end

  def index
    @chores = Chore.all

    render json: @chores
  end

  def show
    render json: Chore.find(params[:id])
  end

  def create
    @chore = current_user.chores.build(chore_params)

    if @chore.save
      render json: @chore, status: :created, location: @chore
    else
      render json: @chore.errors, status: :unprocessible_entity
    end
  end

  def update
    if @chore.update(chore_params)
      head :no_content
    else
      render json: @chore.errors, status: :unprocessible_entity
    end
  end

  def destroy
    @chore.destroy

    head :no_content
  end
end
```

I tried having inheritance from `OpenReadController` but that didn't work.

**Comment by raq929** [comment]
Does your model for chores look like the example model?
Did you migrate after making that change?

**Comment by akradin** [comment]
Yes to looking the same. However, when I migrate, nothing happens in terminal.

**Comment by raq929** [comment]
What about your user model? Does it also have has_many?

**Comment by akradin** [comment]
Yes

**Comment by raq929** [comment]
This might help: https://github.com/ga-wdi-boston/rails-api-one-to-many#demo-modify-books-migration

**Comment by akradin** [comment]
My users already has a reference to chores

**Comment by raq929** [comment]
Can I see the migration file where you added the reference?

**Comment by raq929** [comment]
And/or can you verify that the reference exists in the rails shell or in psql?

**Comment by akradin** [comment]
```rb
class AddChoreRefToUsers < ActiveRecord::Migration
  def change
    add_reference :users, :chore, index: true, foreign_key: true
  end
end
```

And yes, verified in railsdb

**Comment by raq929** [comment]
Are you doing the post via curl? Can you post the curl command you're using?

**Comment by raq929** [comment]
AH. Your migration has users instead of user. Change it to user, and either rollback the last migration and re-migrate, or drop the database, recreate it, and migrate.

**Comment by akradin** [comment]
Ohhhhh okay, can I change `users` to `user` directly in the Ruby file? Dropping tables scares me.

update: answered my own question will close once I figure it out

**Comment by akradin** [comment]
so I should do:
`bundle exec rake db:rollback`
`bundle exec rake d AddChoreRefToUsers`
`bundle exec rake g AddChoreRefToUser`
`bundle exec rake db:migrate`
 I think, so I did that
I get the same looking migration when I take those steps
So I rolled back again, manually changed `:users` to `:user` and attempted to migrate but I got a an error

**Comment by raq929** [comment]
What's the error?

**Comment by akradin** [comment]
```sh
~/wdi/projects/chore-tracker/rails-api-template-master (rails-setup)$ bundle exec rake db:migrate
== 20161130190826 AddChoreRefToUser: migrating ================================
-- add_reference(:user, :chore, {:index=>true, :foreign_key=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "user" does not exist
: ALTER TABLE "user" ADD "chore_id" integer
/Users/AlexKradin/wdi/projects/chore-tracker/rails-api-template-master/db/migrate/20161130190826_add_chore_ref_to_user.rb:3:in `change'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "user" does not exist
: ALTER TABLE "user" ADD "chore_id" integer
/Users/AlexKradin/wdi/projects/chore-tracker/rails-api-template-master/db/migrate/20161130190826_add_chore_ref_to_user.rb:3:in `change'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
PG::UndefinedTable: ERROR:  relation "user" does not exist
/Users/AlexKradin/wdi/projects/chore-tracker/rails-api-template-master/db/migrate/20161130190826_add_chore_ref_to_user.rb:3:in `change'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/AlexKradin/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by gaand** [comment]
A User `has_many :chores`?
A Chore `belongs_to :user`?

**Comment by akradin** [comment]
Fixed! Big Thanks to Rachel!!

correct migration:
`bundle exec rails g migration AddUserToChores user:references`

Correct migration file
```rb
class AddChoreRefToUser < ActiveRecord::Migration
  def change
    add_reference :users, :chore, index: true, foreign_key: true
  end
end
```
