### ISSUE TITLE
Need help with authentication

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/full-stack-project#547]
I need help figuring out how to restrict access to data to the user that created it. I've been banging my head over this for a while and have made no headway.

**Comment by raq929** [comment]
Have you looked at the example model and the example serializer?

**Comment by gaand** [comment]
And the example controller?

**Comment by treep78** [comment]
I'm not sure what I should be using from those or what they do. All I know is that implementing the serializer code causes
```
:4741/card_links:1 POST http://localhost:4741/card_links 500 (Internal Server Error)
2016-12-02 16:42:21.254 jquery.js:9536 XHR finished loading: POST "http://localhost:4741/card_links".send @ jquery.js:9536ajax @ jquery.js:9143newCardLink @ api.js:67onAddCard @ events.js:81dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009
2016-12-02 16:42:21.258 ui.js:47 Object {readyState: 4, responseText: "<!DOCTYPE html>↵<html lang="en">↵<head>↵  <meta ch…>:</p> <pre>None</pre>↵↵</div>↵↵↵</body>↵</html>↵", status: 500, statusText: "Internal Server Error"}failure @ ui.js:47mightThrow @ jquery.js:3570process @ jquery.js:3638
2016-12-02 16:42:21.580 :4741/card_links:1 GET http://localhost:4741/card_links 500 (Internal Server Error)
2016-12-02 16:42:21.582 jquery.js:9536 XHR finished loading: GET "http://localhost:4741/card_links".send @ jquery.js:9536ajax @ jquery.js:9143getCardLinks @ api.js:77onGetCardLinks @ events.js:63onAddCard @ events.js:84dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009
2016-12-02 16:42:21.585 ui.js:47 Object {readyState: 4, responseText: "<!DOCTYPE html>↵<html lang="en">↵<head>↵  <meta ch…>:</p> <pre>None</pre>↵↵</div>↵↵↵</body>↵</html>↵", status: 500, statusText: "Internal Server Error"}failure @ ui.js:47mightThrow @ jquery.js:3570process @ jquery.js:3638
```

**Comment by treep78** [comment]
Retested: appears to be same error
```
:4741/card_links:1 POST http://localhost:4741/card_links 500 (Internal Server Error)
2016-12-02 17:00:50.813 jquery.js:9536 XHR finished loading: POST "http://localhost:4741/card_links".send @ jquery.js:9536ajax @ jquery.js:9143newCardLink @ api.js:67onAddCard @ events.js:81dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009
2016-12-02 17:00:50.818 ui.js:47 Object {readyState: 4, responseText: "<!DOCTYPE html>↵<html lang="en">↵<head>↵  <meta ch…>:</p> <pre>None</pre>↵↵</div>↵↵↵</body>↵</html>↵", status: 500, statusText: "Internal Server Error"}failure @ ui.js:47mightThrow @ jquery.js:3570process @ jquery.js:3638
2016-12-02 17:00:51.079 jquery.js:9536 XHR finished loading: GET "http://localhost:4741/card_links".send @ jquery.js:9536ajax @ jquery.js:9143getCardLinks @ api.js:77onGetCardLinks @ events.js:63onAddCard @ events.js:84dispatch @ jquery.js:5201elemData.handle @ jquery.js:5009
```

**Comment by treep78** [comment]
The back end doesn't appear to do anything on the call

**Comment by treep78** [comment]
new error 
```
NoMethodError (undefined method `text' for #<CardLink:0x007fc3b28d85d8>):
  app/controllers/card_links_controller.rb:24:in `create'
```

**Comment by treep78** [comment]
serializer
```
class CardLinkSerializer < ActiveModel::Serializer
  attributes :id, :editable
  has_one :deck
  has_one :card

  def editable
    scope == object.user
  end
end

```

controller
```
class CardLinksController < ProtectedController
  before_action :set_card_link, only: [:show, :update, :destroy]

  # GET /card_links
  # GET /card_links.json
  def index
    @card_links = CardLink.all

    render json: @card_links
  end

  # GET /card_links/1
  # GET /card_links/1.json
  def show
    render json: @card_link
  end

  # POST /card_links
  # POST /card_links.json
  def create
    # @card_link = CardLink.new(card_link_params)
    @card_link = current_user.card_links.build(card_link_params)

    if @card_link.save
      render json: @card_link, status: :created
    else
      render json: @card_link.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /card_links/1
  # PATCH/PUT /card_links/1.json
  def update
    @card_link = CardLink.find(params[:id])

    if @card_link.update(card_link_params)
      head :no_content
    else
      render json: @card_link.errors, status: :unprocessable_entity
    end
  end

  # DELETE /card_links/1
  # DELETE /card_links/1.json
  def destroy
    @card_link.destroy

    head :no_content
  end

  private

  def set_card_link
    @card_link = CardLink.find(params[:id])
  end

  def card_link_params
    params.require(:card_link).permit(:deck_id, :card_id)
  end
end

```

**Comment by treep78** [comment]
Current error:
```
Completed 500 Internal Server Error in 69ms (ActiveRecord: 28.7ms)

NoMethodError (undefined method `text' for #<CardLink:0x007fc3b28d85d8>):
  app/controllers/card_links_controller.rb:24:in `create'
```

Google turned up no useful answers.

**Comment by raq929** [comment]
Can you post the curl request that led to the error?

**Comment by payne-chris-r** [comment]
Text might be also be an reserved word. I can't remember. Please do what @raq929 asked and then post what your schema looks like as well.

**Comment by gaand** [comment]
Please post the card link model.

**Comment by gaand** [comment]
`text` is the attribute name in the `Example` model, so it might be related to that.

Have you shutdown and restarted your server?

**Comment by raq929** [comment]
@treep78, what's your status?

**Comment by treep78** [comment]
No progress. Server restart did nothing and I have no idea what text in the example model could have to do with the card_link model but here it is.

```
class CardLink < ActiveRecord::Base
  belongs_to :deck, inverse_of: :card_links
  belongs_to :card, inverse_of: :card_links
  belongs_to :user
  validates :text, :user, presence: true
end
```

**Comment by treep78** [comment]
So I attempted a db drop create migrate examples, but when I attempted to run examples I got the same error:
```
NoMethodError: undefined method `text' for #<CardLink:0x007f864211b7f8>
```
not sure if this tells me anything new, but there it is

**Comment by treep78** [comment]
I've been trying anything I can think of. Deleting ```:text``` from the card_link model fixes the initial error, but causes a lot of others. At this point I'm not sure what to do.

**Comment by payne-chris-r** [comment]
If you only do what the last person suggests, you are missing the point. We're trying to pull as much data out of you as possible in order to help. If we ask you to do steps 1-3, but you only do 3, I can't help you much.

**Comment by treep78** [comment]
i did do all of that and noted as such. With the exception of:
```
API="http://localhost:4741"
URL_PATH="/card_links"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiU3NDQ4ZTJhMzdhZGNkMjFmZTM1NmU2M2JiYTUwMDExYgY6BkVG--4fd057ce0557a63637ad91581e49658e2c70b064" \
  --data '{
    "card_link": {
      "deck_id": "1",
      "card_id": "1"
    }
  }'

echo

```
curl request.

**Comment by raq929** [comment]
Please post your schema as @payne-chris-r asked.

**Comment by treep78** [comment]
Schema
```
ActiveRecord::Schema.define(version: 20161202222720) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "card_links", force: :cascade do |t|
    t.integer  "deck_id"
    t.integer  "card_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end

  add_index "card_links", ["card_id"], name: "index_card_links_on_card_id", using: :btree
  add_index "card_links", ["deck_id"], name: "index_card_links_on_deck_id", using: :btree
  add_index "card_links", ["user_id"], name: "index_card_links_on_user_id", using: :btree

  create_table "cards", force: :cascade do |t|
    t.string   "name"
    t.string   "card_class"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "combinations", force: :cascade do |t|
    t.string   "first_card_class"
    t.string   "second_card_class"
    t.string   "result"
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
  end

  create_table "decks", force: :cascade do |t|
    t.string   "name"
    t.text     "description"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
  end

  create_table "examples", force: :cascade do |t|
    t.text     "text",       null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_index "examples", ["user_id"], name: "index_examples_on_user_id", using: :btree

  create_table "hands", force: :cascade do |t|
    t.string   "card"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["token"], name: "index_users_on_token", unique: true, using: :btree

  add_foreign_key "card_links", "cards"
  add_foreign_key "card_links", "decks"
  add_foreign_key "card_links", "users"
  add_foreign_key "examples", "users"
end
```

**Comment by treep78** [comment]
If I can't figure this out tonight should I present tomorrow with ownership commented out so I can show the app working?

**Comment by payne-chris-r** [comment]
Is this still broken? Did you figure it out? Can you update please?

**Comment by treep78** [comment]
Still broken. I'm working on my front end to ensure its somewhat bullet proof before diving back into the back end.

**Comment by payne-chris-r** [comment]
Please post your resolution and close this issue @treep78

**Comment by treep78** [comment]
It turns out I had had card_links validation text, but it has no text method.
