### ISSUE TITLE
Empty dataset issue 

### ISSUE THREAD

**Issue by matthewgsommers** [ga-wdi-boston/full-stack-project#569]
Hey everyone!

So, I have GET / POST / PATCH / DELETE all working, but my issue is that they're only working when there is information in my backend. 

The way that I have everything set up, I can POST a picture to the backend, but after being sent to the back end I'm running into the following error: 

```
TypeError: app.items.push is not a function
    at Object.uploadPictureSuccess (http://localhost:7165/bundle.js:493:14)
    at mightThrow (http://localhost:7165/dependencies.js:3680:30)
    at process (http://localhost:7165/dependencies.js:3748:13)failure @ ui.js:82mightThrow @ jquery.js:3570process @ jquery.js:3638 
```

Here is the relevant code; I'm going to describe what I think is going on below the code itself.

**From ui.js**
```
'use strict';

const app = require('../app.js');

const getPictureSuccess = (data) => {
  console.log('pictureSuccessID', data.id);
  console.log("SUCCESSFUL GET");
  renderItem(data);
  console.log(data.id);
};

function renderItem(item){
let template = `<div data-item="${item.id}" class="graffiti-one-container">
  <div class="graffiti-one-img-container">
    <a href="#">
      <img src="${item.url || "#"}" alt="Image to be linked to" class="graffiti-one-img">
    </a>
  </div>
<!-- This div contains all code relevant to img one's info-->
  <div class="graffiti-one-info">
     <div class="row">
     <div class="col-md-4 id-container"><p>Tag Name:<br> ${item.id}</p></div>
     <div class="col-md-4 tag-name-container"><p>Tag Name:<br> ${item.title}</p></div>
     <div class="col-md-4 artist-name-container">Artist:<br>  ${item.artist}</div>
     <div class="col-md-4 location-container">Location:<br>  ${item.location}</div>
     <div class="col-md-4 date-container">Date Photographed:<br>  ${item.date}</div>
     <div class="col-md-4 url-container">URL:<br>  ${item.url}</div>
     <div class="col-md-4 comment-display">Comments:<br>  ${item.comment}</div>
     </div>
     <div class="row">
       <div class="col-md-12 description-container">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
     </div>
  </div>
  <div class="comment-box">
    <form id="comment-form" data-item="${item.id}">
      <input type="text" class="comment-container" name="battle[comment]">
      <input type="submit" class="comment-btn">
    </form>
  </div>
  <div class="delete-btn-container">
    <form id='delete-btn-form' data-item="${item.id}">
      <!-- <input type="text" name="id"  placeholder="ID"> -->
      <input type="submit" class='delete-btn' value="DELETE PICTURE">
    </form>
  </div>
<!--  <div class="delete-btn-container">
    <form id='delete-btn-form'>
      <input type="text" name="battle[id]" placeholder="ID">
      <input type="submit" class='delete-btn' name='delete-picture-btn' value="Click this button to delete this image and information">
    </form>
  </div> -->
</div>`

$('.graffiti-main').html(template);
}

const uploadPictureSuccess = (data) => {
  app.items = app.items || [];
  app.items.push(data);
  console.log('Upload is working');
  console.log(data.id);
};

const deletePictureSuccess = (id) => {
  console.log("SUCCESSFUL DELETE");
  console.log(app.items);
  app.items.shift();
  console.log(app.items);
  if(app.items.length === 0 ){
      $('.get-picture-button').hide();
    return;
  }
};

const commentPictureSuccess = (id) => {
  $('.comment-display').text(id);
  console.log(app.items.id);
};

const failure = (err) => {
  console.error(err);
};

module.exports = {
  getPictureSuccess,
  uploadPictureSuccess,
  deletePictureSuccess,
  commentPictureSuccess,
  failure,
};
```

**From events.js**
```
'use strict';

const getFormFields = require('../../../lib/get-form-fields');
const api = require('./api');
const ui = require('./ui');
const app = require('../app');

const onGetPicture = function (event) {
  event.preventDefault();
  let firstItem = app.items.shift();
  ui.getPictureSuccess(firstItem);
  app.items.push(firstItem);
};

const onUploadPicture = function (event) {
  event.preventDefault();
  let battle = getFormFields(event.target).battle;
  api.uploadPicture({battle})
  .then(ui.uploadPictureSuccess)
  .catch(ui.failure);
  $('.get-picture-button').show();
  $('.delete-btn').show();
};

const onDeletePicture = function (event) {
  event.preventDefault();
  console.log(event.target);
  if(app.items.length === 0 ){
    return;
  }
  let id = $(event.target).data("item");
  api.deletePicture(id)
  .then(ui.deletePictureSuccess)
  .then(api.getPicture)
  .then(data => app.items = data)
  .then((data)=>{
    app.items = data;
    let firstItem = app.items.shift();
    ui.getPictureSuccess(firstItem);
    app.items.push(firstItem);
  })
  .catch(ui.failure);
  $('.graffiti-one-container').hide();
};

const onCommentPicture = function (event) {
  event.preventDefault();
  console.log(event.target);
  let id = $(event.target).data("item");
  console.log(id);
    let commentField = getFormFields(event.target);
    api.commentPicture(id, commentField)
    .then(api.getPicture)
    .then(data => app.items = data)
    .then((data)=>{
      app.items = data;
      let firstItem = app.items.shift();
      ui.getPictureSuccess(firstItem);
      app.items.push(firstItem);
    })
    .catch(ui.failure);
};

const addHandlers = () => {
  api.getPicture().then(data => app.items = data);
  $('#get-picture-form').on('submit', onGetPicture);
  $('#upload-picture-form').on('submit', onUploadPicture);
  $(document).on('submit', '#delete-btn-form', onDeletePicture);
  $(document).on('submit', '#comment-form', onCommentPicture);
};

module.exports = {
  addHandlers,
};
```

So, if my data is getting posted to the backend, then I know that the line below ```  api.uploadPicture({battle})```  (in events.js) is where the issue is stemming from. 

I've been trying to utilize an if statement like:
```
if (app.items.length !==0) {
'continue as normal'}
else { 
'do something to fix'
}
```
to create a solution, but I'm having trouble determining what the next step is. 

I've also tried to remove the push method but it creates problems in the rest of my code that I'm having trouble tracking. I've also tried to "go around the brick wall" by inserting that if statement into other sections of the code but again, it creates problems everywhere else. 

Suggestions? Thank you!!!

**Comment by gaand** [comment]
In some of the places you are assigning items

```js
app.items = ...
```

You may be assigning something other than an array.  If that happens then push won't be a function.

**Comment by callmelife** [comment]
I was wrong about the location of the error; its actually in my `onDeletePicture ` in events.js: 

```
const onDeletePicture = function (event) {
  event.preventDefault();
  console.log(event.target);
    let id = $(event.target).data("item");
    api.deletePicture(id)
    .then(ui.deletePictureSuccess)
    .then(api.getPicture)
    .then(data => app.items = data)
    .then((data)=>{
      app.items = data;
      let firstItem = app.items.shift();
      ui.getPictureSuccess(firstItem);
      app.items.push(firstItem);
    })
    .catch(ui.failure);
    $('.graffiti-one-container').hide();
  }
};
```
The `.then(api.getPicture)` promise `onDeletePicture` is attempting to load an object that doesnt exist after the last object in the array is deleted. Looking into how to tell if an object exists/is empty now.

**Comment by matthewgsommers** [comment]
I think I might have found the source of the error.

` .then(api.getPicture)` in `const onDeletePicture = function (event) {` is attempting to GET an object that doesnt exist because it keeps firing even after the last object in the array was deleted. I intended on auto-populating each time but I didnt think of that aspect. 

```
const onDeletePicture = function (event) {
  event.preventDefault();
  console.log(event.target);
    let id = $(event.target).data("item");
    api.deletePicture(id)
    .then(ui.deletePictureSuccess)
    .then(api.getPicture)
    .then(data => app.items = data)
    .then((data)=>{
      app.items = data;
      let firstItem = app.items.shift();
      ui.getPictureSuccess(firstItem);
      app.items.push(firstItem);
    })
    .catch(ui.failure);
    $('.graffiti-one-container').hide();
  }
};
```

Right? Or am I off / have multiple problems? I'm looking into determine if an object I'm looking for exists or not. 

Thanks!

**Comment by neugierige** [comment]
I would agree with your idea here. It does seem odd that you are calling `api.getPicture` after `api.deletePicture(id)` is called. There may be other things going on, but start there and see if that fixes things. 

I also noticed this in your `ui.js`:
```js
const uploadPictureSuccess = (data) => {
  app.items = app.items || [];
  app.items.push(data);
};
```

what were you trying to accomplish with `app.items = app.items || [];`?

**Comment by matthewgsommers** [comment]
Thats an Antony line. The way that he explained it to me, if my memory serves correctly, is that we're setting app.items to itself or an empty array in case app.items doesnt already exist - that way it prevents error stemming from app.items not existing because then it will be equal to an empty array. 

Thinking through it now,  app.items.push(data); would still throw an error if attempting to push an object that doesnt exist in an empty array.

**Comment by raq929** [comment]
@neugierige Matt's api.getPicture is actually calling to get all the pictures. So I think it's ok that he's refreshing the data there. 
Your getPicture should return an empty array if there are no pictures.

**Comment by matthewgsommers** [comment]
I thought that the error was stemming from `.then(api.getPicture)` attempting to GET information that doesnt exist when in reality it would still be getting an empty array. The solution was to add the if statement before the ` let firstItem = app.items.shift();` line, not before `.then(api.getPicture)`. Now that I can successfully tell that there is no item being passed back from the api, I should be all set. 

```
const onDeletePicture = function (event) {
  event.preventDefault();
  console.log(event.target);
    let id = $(event.target).data("item");
    api.deletePicture(id)
    .then(ui.deletePictureSuccess)
    .then(api.getPicture)
    .then(data => app.items = data)
    .then((data)=>{
      app.items = data;
      if (app.items.length > 0) {
        let firstItem = app.items.shift();
        ui.getPictureSuccess(firstItem);
        app.items.push(firstItem);
      } else {
        alert('there are no items to get!')
      }
    })
    .catch(ui.failure);
    $('.graffiti-one-container').hide();
};
```
Thank you!!!
