### ISSUE TITLE
migration after scaffold

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#597]
I made a scaffold 
```rb
bin/rails generate scaffold Comment movie:references user:references date:datetime
```
but now, there are lots of errors regarding a migration

do I also need to run 
```rb
rails g migration AddUserIdToComments user:references
rails g migration AddMovieIdToComments movie:references
```
my terminal tells me to run 

```rb
bin/rails db:migrate RAILS_ENV=development
```
but I'm getting duplicate errors
so I ran 

```rb
bin/rails db:drop db:create db:mirgrate db:seed db:examples
```
thinking that this would recreate the tables without any issues
but I am still getting duplicate column errors

then it told me to run

```rb
bin/rails db:environment:set RAILS_ENV=development
```

and still got duplicate column errors

so do I also need to run 
```rb
rails g migration AddUserIdToComments user:references
rails g migration AddMovieIdToComments movie:references
```
to add these migrations?

**Comment by raq929** [comment]
Can you post the error that you're getting?

**Comment by ggabrakadabra** [comment]
```rb
$ bin/rails db:environment:set RAILS_ENV=development
~/wdi/gabs-scary-movies (scripts)
$ bin/rails db:drop db:create db:migrate db:seed db:examples
Dropped database 'gabs-scary-movies_development'
Dropped database 'gabs-scary-movies_test'
Created database 'gabs-scary-movies_development'
Created database 'gabs-scary-movies_test'
== 1 CreateUsers: migrating ===================================================
-- create_table(:users, {})
   -> 0.0105s
== 1 CreateUsers: migrated (0.0106s) ==========================================

== 2 CreateExamples: migrating ================================================
-- create_table(:examples, {})
   -> 0.0082s
== 2 CreateExamples: migrated (0.0083s) =======================================

== 20170216223840 CreateMovies: migrating =====================================
-- create_table(:movies)
   -> 0.0040s
== 20170216223840 CreateMovies: migrated (0.0041s) ============================

== 20170216232340 AddUserIdToMovies: migrating ================================
-- add_reference(:movies, :user, {:foreign_key=>true, :index=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "user_id" of relation "movies" already exists
: ALTER TABLE "movies" ADD "user_id" integer
/Users/Gabrakadabra/wdi/gabs-scary-movies/db/migrate/20170216232340_add_user_id_to_movies.rb:6:in `change'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `require'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `<top (required)>'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "user_id" of relation "movies" already exists
: ALTER TABLE "movies" ADD "user_id" integer
/Users/Gabrakadabra/wdi/gabs-scary-movies/db/migrate/20170216232340_add_user_id_to_movies.rb:6:in `change'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `require'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `<top (required)>'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
PG::DuplicateColumn: ERROR:  column "user_id" of relation "movies" already exists
/Users/Gabrakadabra/wdi/gabs-scary-movies/db/migrate/20170216232340_add_user_id_to_movies.rb:6:in `change'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `require'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `<top (required)>'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by raq929** [comment]
It seems like you added the user as a reference when you first created the movie table, and then added it again in the `AddUserIdToMovies` migration. If you remove `AddUserIdToMovies`, I think you'll have the table you want.

**Comment by ggabrakadabra** [comment]
But I want the user_id to be in movies. I was only trying to create a join table of comments with the user_id and movie_id. If I delete that file, won't the user_id be removed from the movies table?

**Comment by raq929** [comment]
Right. What the error is telling you is that it already _is_ in movie when you try to add it. I think you'll have it after deleting the file. (You can double check in psql.)

**Comment by ggabrakadabra** [comment]
I removed the file, then got this error
```rb
$ bin/rails db:drop db:create db:migrate db:seed db:examples
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=development

/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `require'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `<top (required)>'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
~/wdi/gabs-scary-movies (scripts)
$ bin/rails db:drop db:create db:migrate db:seed db:examples
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 

Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=development

/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `require'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/rails:9:in `<top (required)>'
/Users/Gabrakadabra/wdi/gabs-scary-movies/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
```
then ran 
```rb
bin/rails db:environment:set RAILS_ENV=development
```

and nothing happened, then ran 

```rb
bin/rails db:drop db:create db:migrate db:seed db:examples
```
and it worked! Thank you

**Comment by raq929** [comment]
Yay! I'm confused about why it keeps asking you to set the environment, but I'm glad it worked! (I'm going to check with @gaand about the env issue.)

**Comment by raq929** [comment]
I checked on the environment issue, and it has to do with switching between rails 4 and 5. The command you ran to fix it is the right thing to do, so you're good to go!
