### ISSUE TITLE
Users must exist issue, but with a 1:1 relationship

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/full-stack-project#602]
I'm having a similar issue Max was having earlier in [586](https://github.com/ga-wdi-boston/full-stack-project/issues/586) except I'm doing the 1 to 1 relationship between user and athlete... Same error, different relationship?
Anyway, here are my models:
```rb
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_one :athlete
end

class Athlete < ApplicationRecord
  has_many :workouts, through: :logs
  has_many :logs
  belongs_to :users

  validates :given_name, presence: true
  validates :surname, presence: true
  validates :date_of_birth, presence: true
end
```

Migration:
```rb
class AddUserIdToAthletes < ActiveRecord::Migration[5.0]
  def change
    add_reference :athletes, :user, index: true, foreign_key: true
  end
end
```

```rb
User.transaction do
  %w(lauren maddie jeff max alec kate brian gary anna).each do |name|
    email = "#{name}@#{name}.com"
    next if User.exists? email: email
    User.create!(email: email,
                 password: 'abc123',
                 password_confirmation: nil)
  end
end

Athlete.transaction do
  %w(lauren maddie jeff max alec kate brian gary anna).each do |name|
    user = User.first
    athlete_params = {
      user_id: user.id,
      given_name: name,
      surname: 'Tufts',
      date_of_birth: '1993-01-16'
    }
    next if Athlete.exists? athlete_params
    Athlete.create! athlete_params
  end
end
```
So far I've built Athlete, Workout, and Log first, made them all CRUDable, and Athlete and Workout have a many-to-many relationship through Log... And now I want to create a one-to-one relationship with Athlete and the User for ownership reasons.

**Comment by MicFin** [comment]
Are you getting a new user each time or are you just getting the first user every time?

```rb
Athlete.transaction do
  %w(lauren maddie jeff max alec kate brian gary anna).each do |name|
    # user = User.first
    email = "#{name}@#{name}.com"
    user = User.where(email: email).first
    athlete_params = {
      user_id: user.id,
      given_name: name,
      surname: 'Tufts',
      date_of_birth: '1993-01-16'
    }
    next if Athlete.exists? athlete_params
    Athlete.create! athlete_params
  end
end
```

**Comment by raq929** [comment]
Make sure you have a valid user id.

**Comment by laurpaik-zz** [comment]
```
Dropped database 'workit-api_development'
Dropped database 'workit-api_test'
Created database 'workit-api_development'
Created database 'workit-api_test'
== 1 CreateUsers: migrating ===================================================
-- create_table(:users, {})
   -> 0.0080s
== 1 CreateUsers: migrated (0.0081s) ==========================================

== 2 CreateExamples: migrating ================================================
-- create_table(:examples, {})
   -> 0.0078s
== 2 CreateExamples: migrated (0.0079s) =======================================

== 20170215202723 CreateWorkouts: migrating ===================================
-- create_table(:workouts)
   -> 0.0026s
== 20170215202723 CreateWorkouts: migrated (0.0027s) ==========================

== 20170215213719 CreateAthletes: migrating ===================================
-- create_table(:athletes)
   -> 0.0025s
== 20170215213719 CreateAthletes: migrated (0.0026s) ==========================

== 20170217140857 CreateLogs: migrating =======================================
-- create_table(:logs)
   -> 0.0069s
== 20170217140857 CreateLogs: migrated (0.0069s) ==============================

== 20170217163253 AddUserIdToAthletes: migrating ==============================
-- add_reference(:athletes, :user, {:index=>true, :foreign_key=>true})
   -> 0.0070s
== 20170217163253 AddUserIdToAthletes: migrated (0.0071s) =====================

rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Users must exist
/Users/laurenpaik/wdi/projects/WorkIt-API/db/examples.rb:34:in `block (2 levels) in <top (required)>'
/Users/laurenpaik/wdi/projects/WorkIt-API/db/examples.rb:24:in `each'
/Users/laurenpaik/wdi/projects/WorkIt-API/db/examples.rb:24:in `block in <top (required)>'
/Users/laurenpaik/wdi/projects/WorkIt-API/db/examples.rb:23:in `<top (required)>'
/Users/laurenpaik/wdi/projects/WorkIt-API/lib/tasks/db.rake:5:in `require_relative'
/Users/laurenpaik/wdi/projects/WorkIt-API/lib/tasks/db.rake:5:in `block (2 levels) in <top (required)>'
/Users/laurenpaik/wdi/projects/WorkIt-API/bin/rails:9:in `require'
/Users/laurenpaik/wdi/projects/WorkIt-API/bin/rails:9:in `<top (required)>'
/Users/laurenpaik/wdi/projects/WorkIt-API/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:nuke_pave => db:examples
(See full trace by running task with --trace)
```

**Comment by laurpaik-zz** [comment]
it was a typo in the model.... 
```rb
class Athlete < ApplicationRecord
  has_many :workouts, through: :logs
  has_many :logs
  belongs_to :users
```
needed to be 
```rb
class Athlete < ApplicationRecord
  has_many :workouts, through: :logs
  has_many :logs
  belongs_to :user
```
