### ISSUE TITLE
param is missing or the value is empty

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/full-stack-project#603]
I am testing the update for reviews, but I am getting the error message in the title. 

This is my command: $ ID=1 STARS=4 sh scripts/reviews/update.sh

This is what I have in my update.sh file and where the problem is:
```sh
#!bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews/${ID}"
curl "${API}${URL_PATH}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --data '{
    "reviews": {
      "rating": "'"${STARS}"'"
    }
  }'
   #\
  # --header "Authorization: Token token=$TOKEN"

echo
```

**Comment by BenGitsCode** [comment]
Please format your code snippets in block format per https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by BenGitsCode** [comment]
Is that the full error you're getting?

**Comment by alexkarasik** [comment]
According to my server, its a 400 bad request. The full error from the server is: ActionController::ParameterMissing (param is missing or the value is empty: review):
  
app/controllers/reviews_controller.rb:51:in `review_params'
app/controllers/reviews_controller.rb:30:in `update'

I will format the code now

**Comment by alexkarasik** [comment]
I hope this is right:

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews/${ID}"
curl "${API}${URL_PATH}" 
  --include 
  --request PATCH 
  --header "Content-Type: application/json" 
  --data '{
    "reviews": {
      "rating": "'"${STARS}"'"
      }
}'
  #\

**Comment by raq929** [comment]
Please edit your comment to format your code the way Ben asked you to.

**Comment by alexkarasik** [comment]
```

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews/${ID}"
curl "${API}${URL_PATH}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --data '{
    "reviews": {
      "stars": "'"${STARS}"'"
    }
  }'
   #\
  # --header "Authorization: Token token=$TOKEN"

echo
```

**Comment by raq929** [comment]
Cool. What happens when you run it?

**Comment by alexkarasik** [comment]
I don't understand what you mean. When I execute the command in the terminal? I

**Comment by BenGitsCode** [comment]
👏 See how much more readable that is?

Yes, what's the output from your input?

**Comment by alexkarasik** [comment]
HTTP/1.1 400 Bad Request

followed by 

{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: review\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/reviews_controller.rb:51:in `review_params'"},

it goes on like that for awhile....

**Comment by alexkarasik** [comment]
All the way to id 62 for some reason I might add. As of now, there should only be 2 created elements in my index, so I don't know what all that other crap is. All my other scripts are working.

**Comment by raq929** [comment]
Post the whole error please! (in between backtics)

**Comment by MicFin** [comment]
@alexkarasik check this out if you are unsure about how to style your code in comments
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by alexkarasik** [comment]
```
$ ID=1 STARS=4 sh scripts/reviews/update.sh
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Request-Id: 4317e310-23ff-4265-9d2c-88786de88bc7
X-Runtime: 0.059102
Vary: Origin
Content-Length: 11868

{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: review\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/reviews_controller.rb:51:in `review_params'"},{"id":2,"trace":"app/controllers/reviews_controller.rb:30:in `update'"}],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_controller/metal/strong_parameters.rb:310:in `require'"},{"id":3,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":6,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"},{"id":7,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'"},{"id":8,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"},{"id":9,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":11,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":12,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":13,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":14,"trace":"actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":15,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":16,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":17,"trace":"activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":18,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":19,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":20,"trace":"actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":21,"trace":"activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":22,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":23,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":24,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":25,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":26,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":27,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":28,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":29,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":30,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":31,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":32,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"},{"id":33,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":34,"trace":"activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'"},{"id":35,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":36,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":37,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":38,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":39,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":40,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":41,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":42,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":43,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":44,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":45,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":46,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":47,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":48,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":49,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":50,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":51,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":52,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":53,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":54,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":55,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":56,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":57,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":58,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":59,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":60,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":61,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":62,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}],"Full Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_controller/metal/strong_parameters.rb:310:in `require'"},{"id":1,"trace":"app/controllers/reviews_controller.rb:51:in `review_params'"},{"id":2,"trace":"app/controllers/reviews_controller.rb:30:in `update'"},{"id":3,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":6,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"},{"id":7,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'"},{"id":8,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"},{"id":9,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":11,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":12,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":13,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":14,"trace":"actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":15,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":16,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":17,"trace":"activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":18,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":19,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":20,"trace":"actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":21,"trace":"activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":22,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":23,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":24,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":25,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":26,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":27,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":28,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":29,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":30,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":31,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":32,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"},{"id":33,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":34,"trace":"activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'"},{"id":35,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":36,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":37,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":38,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":39,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":40,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":41,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":42,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":43,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":44,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":45,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":46,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":47,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":48,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":49,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":50,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":51,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":52,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":53,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":54,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":55,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":56,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":57,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":58,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":59,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":60,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":61,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":62,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}]}}
```

**Comment by alexkarasik** [comment]
I put it in the ``` brackets before and after. The error goes on and on to the right.

**Comment by MicFin** [comment]
`ActionController::ParameterMissing (param is missing or the value is empty: review):`
That makes me think that your request doesn't have the `review` the controller is expecting, maybe because your request is sending `reviews` plural.  You are only trying to update 1 review at a time so sending a single review and not reviews might make sense.

Try changing the key to singular `review`

```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews/${ID}"
curl "${API}${URL_PATH}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --data '{
    "review": {
      "stars": "'"${STARS}"'"
    }
  }'
   #\
  # --header "Authorization: Token token=$TOKEN"

echo
```

**Comment by alexkarasik** [comment]
That was it! Thanks guys! I will work on my formatting!
