### ISSUE TITLE
questions about a test failure

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#605]
I have a test faliure and I can't figure out the problem.
I don't think we went over  GET new in the last repo???

```1) TrailsController GET #new assigns a new trail as @trail
     Failure/Error: get :new, params: {}, session: valid_session
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"new", :controller=>"trails"}
     # ./spec/controllers/trails_controller_spec.rb:57:in `block (3 levels) in <top (required)>'

  2) TrailsController routing routes to #new
     Failure/Error: expect(get: '/trails/new').to route_to('trails#new')
     
       The recognized options <{"controller"=>"trails", "action"=>"show", "id"=>"new"}> did not match <{"controller"=>"trails", "action"=>"new"}>, difference:.
       --- expected
       +++ actual
       @@ -1 +1 @@
       -{"controller"=>"trails", "action"=>"new"}
       +{"controller"=>"trails", "action"=>"show", "id"=>"new"}
     # ./spec/routing/trails_routing_spec.rb:11:in `block (3 levels) in <top (required)>'```

**Comment by raq929** [comment]
Please post the code for the test. I suspect you're running into the same issue as Sam was in #589

**Comment by Soboscott** [comment]
```rb
require 'rails_helper'

RSpec.describe TrailsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Trail. As you add validations to Trail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TrailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all trails as @trails' do
      trail = Trail.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:trails)).to eq([trail])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested trail as @trail' do
      trail = Trail.create! valid_attributes
      get :show, params: { id: trail.to_param }, session: valid_session
      expect(assigns(:trail)).to eq(trail)
    end
  end

  describe 'GET #new' do
    it 'assigns a new trail as @trail' do
      get :new, params: {}, session: valid_session
      expect(assigns(:trail)).to be_a_new(Trail)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested trail as @trail' do
      trail = Trail.create! valid_attributes
      get :edit, params: { id: trail.to_param }, session: valid_session
      expect(assigns(:trail)).to eq(trail)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Trail' do
        expect do
          post :create, params: { trail: valid_attributes },
                        session: valid_session
        end.to change(Trail, :count).by(1)
      end

      it 'assigns a newly created trail as @trail' do
        post :create, params: { trail: valid_attributes },
                      session: valid_session
        expect(assigns(:trail)).to be_a(Trail)
        expect(assigns(:trail)).to be_persisted
      end

      it 'redirects to the created trail' do
        post :create, params: { trail: valid_attributes },
                      session: valid_session
        expect(response).to redirect_to(Trail.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved trail as @trail' do
        post :create, params: { trail: invalid_attributes },
                      session: valid_session
        expect(assigns(:trail)).to be_a_new(Trail)
      end

      it "re-renders the 'new' template" do
        post :create, params: { trail: invalid_attributes },
                      session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested trail' do
        trail = Trail.create! valid_attributes
        put :update, params: { id: trail.to_param, trail: new_attributes },
                     session: valid_session
        trail.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested trail as @trail' do
        trail = Trail.create! valid_attributes
        put :update, params: { id: trail.to_param, trail: valid_attributes },
                     session: valid_session
        expect(assigns(:trail)).to eq(trail)
      end

      it 'redirects to the trail' do
        trail = Trail.create! valid_attributes
        put :update, params: { id: trail.to_param, trail: valid_attributes },
                     session: valid_session
        expect(response).to redirect_to(trail)
      end
    end

    context 'with invalid params' do
      it 'assigns the trail as @trail' do
        trail = Trail.create! valid_attributes
        put :update, params: { id: trail.to_param, trail: invalid_attributes },
                     session: valid_session
        expect(assigns(:trail)).to eq(trail)
      end

      it "re-renders the 'edit' template" do
        trail = Trail.create! valid_attributes
        put :update, params: { id: trail.to_param, trail: invalid_attributes },
                     session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested trail' do
      trail = Trail.create! valid_attributes
      expect do
        delete :destroy, params: { id: trail.to_param }, session: valid_session
      end.to change(Trail, :count).by(-1)
    end

    it 'redirects to the trails list' do
      trail = Trail.create! valid_attributes
      delete :destroy, params: { id: trail.to_param }, session: valid_session
      expect(response).to redirect_to(trails_url)
    end
  end
end
```

**Comment by raq929** [comment]
This looks like a controller spec, but it looks like it's the route spec that's failing.

**Comment by raq929** [comment]
Do you have a `new` method on your controller? Because that's what you're testing for. It should likely be a `create`. Can you explain a bit about what you're trying to do/test for?

**Comment by gaand** [comment]
You don't have `new` and `edit` actions on an API controller.

**Comment by samordonez** [comment]
I ran into similar failures when I first tried to run tests on my controllers, as Antony said, we don't use the `new` or `edit` actions on  a controller. However, the automatically generated specs will test for them, I just commented out any tests referring to `new` or `edit`

**Comment by raq929** [comment]
If this issue is resolved, please tell us how you resolved it and close. If not, please let us know where you're at. Thanks!

**Comment by Soboscott** [comment]
Sam helped me out,
I commented out the new and edit

**Comment by jrhorn424** [comment]
I'd prefer if we'd delete tests we aren't going to use. Or any code for that matter.
