### ISSUE TITLE
ActionController::RoutingError

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#613]
Trying to get my update to work for my comments.
Whenever I run,

```rb
MOVIE_ID=1 NOTE="blah" TOKEN="BAhJIiVhMzU2ZmEyNTdiZjExZTJmNTA2MWNlMjIwMDUzYjVkMQY6BkVG--94ef68204dd4d1714349c1e2f4c20ece67fb4bc9" sh scripts/comments/update.sh
```

I get this error in the terminal,

```rb
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: 1678e09f-4f16-4969-b255-5918a65db932
X-Runtime: 0.029498
Vary: Origin
Content-Length: 3771
```

and this one in the server

```rb
Started PATCH "/comments/" for 127.0.0.1 at 2017-02-18 12:18:16 -0500
  
ActionController::RoutingError (No route matches [PATCH] "/comments"):
  
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

My routes.rb looks like this

```rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :comments, except: [:new, :edit]
  resources :movies, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

this is what my comments controller looks like for update

```rb
  def update
    if @comment.update(comment_params)
      head :no_content
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end
```

my update.sh looks like this,

```rb
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/comments/${ID}"
curl "${API}${URL_PATH}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "comment": {
      "movie_id": "'"${MOVIE_ID}"'",
      "note": "'"${NOTE}"'"
    }
  }'

echo
```

What am I missing/doing wrong?

**Comment by raq929** [comment]
This is an awesome issue!

When you're running you're script, You're setting MOVIE_ID, but not the `ID` in the URL path. So it's trying to route to `/comments/` (which doesn't have a route for PATCH) instead of `/comments/:id`. If you set the comment ID, I think this will work.

**Comment by ggabrakadabra** [comment]
when I run
```rb
MOVIE_ID=1 NOTE="hhahahah" DATE="1990-07-03" TOKEN="BAhJIiVhMzU2ZmEyNTdiZjExZTJmNTA2MWNlMjIwMDUzYjVkMQY6BkVG--94ef68204dd4d1714349c1e2f4c20ece67fb4bc9" sh scripts/comments/create.sh
```

the terminal returns

```rb
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"378864e1d12d0b2168af853c9d835f03"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: d38d4732-46d2-4272-933b-9eb7fb0b7ded
X-Runtime: 0.021843
Vary: Origin
Transfer-Encoding: chunked

{"comment":{"id":6,"note":"hhahahah","date":"1990-07-03","movie":{"id":1,"title":"Scary Movie"},"user":{"id":1,"email":"gab@gab"}}}
```

which is great. but then when I run,
```rb
ID=6 MOVIE_ID=1 NOTE="blah" TOKEN="BAhJIiVhMzU2ZmEyNTdiZjExZTJmNTA2MWNlMjIwMDUzYjVkMQY6BkVG--94ef68204dd4d1714349c1e2f4c20ece67fb4bc9" sh scripts/comments/update.sh
```

the terminal returns

```rb
HTTP/1.1 204 No Content
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache
X-Request-Id: 9ca37f16-8dd7-42bf-8ab7-118dcbe1811e
X-Runtime: 0.015744
Vary: Origin

```

and in the server it says this

```rb
Started PATCH "/comments/6" for 127.0.0.1 at 2017-02-18 13:49:13 -0500
Processing by CommentsController#update as */*
  Parameters: {"comment"=>{"movie_id"=>"1", "note"=>"blah"}, "id"=>"6"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "a356fa257bf11e2f5061ce220053b5d1"], ["LIMIT", 1]]
  Comment Load (0.6ms)  SELECT  "comments".* FROM "comments" WHERE "comments"."user_id" = $1 AND "comments"."id" = $2 LIMIT $3  [["user_id", 1], ["id", 6], ["LIMIT", 1]]
   (0.2ms)  BEGIN
  Movie Load (0.2ms)  SELECT  "movies".* FROM "movies" WHERE "movies"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  COMMIT
Completed 204 No Content in 7ms (ActiveRecord: 1.3ms)
```
I also tried
```rb
COMMENT_ID=6 MOVIE_ID=1 NOTE="blah" TOKEN="BAhJIiVhMzU2ZmEyNTdiZjExZTJmNTA2MWNlMjIwMDUzYjVkMQY6BkVG--94ef68204dd4d1714349c1e2f4c20ece67fb4bc9" sh scripts/comments/update.sh
```
 but that returned,
```rb
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: 4e1180fa-fa25-44be-b9b8-802ecb91a828
X-Runtime: 0.006880
Vary: Origin
Content-Length: 3771
```

and the server says 

```rb
Started PATCH "/comments/" for 127.0.0.1 at 2017-02-18 13:51:34 -0500
  
ActionController::RoutingError (No route matches [PATCH] "/comments"):
  
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```


Do I need to set comment_id in the curl script?

**Comment by ggabrakadabra** [comment]
when I run 
```rb
ID=6 sh scripts/comments/show.sh 
```

the terminal returns

```rb
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"2e4ada13e283c961a70d7dc3e8d65ef5"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 0d6d2154-a283-4751-8718-d3dcf91ebc87
X-Runtime: 0.008803
Vary: Origin
Transfer-Encoding: chunked

{"comment":{"id":6,"note":"blah","date":"1990-07-03","movie":{"id":1,"title":"Scary Movie"},"user":{"id":1,"email":"gab@gab"}}}
```

but when I run 
```rb
movie_id=1 sh scripts/comments/index.sh 
```
or 
```rb
sh scripts/comments/index.sh 
```

the terminal returns 

```rb
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"74234e98afe7498fb5daf1f36ac2d78a"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: c275adb6-9199-4c45-aab1-d3ed8be9ecaa
X-Runtime: 0.002518
Vary: Origin
Transfer-Encoding: chunked

null
```

and the server response is the same for both

```rb
Started GET "/comments" for 127.0.0.1 at 2017-02-18 14:13:56 -0500
Processing by CommentsController#index as */*
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Class (0.05ms)
Completed 200 OK in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms)
```

**Comment by MicFin** [comment]
You can run `create.sh` and it creates a comment so that's good. 
```rb
MOVIE_ID=1 NOTE="hhahahah" DATE="1990-07-03" TOKEN="BAhJIiVhMzU2ZmEyNTdiZjExZTJmNTA2MWNlMjIwMDUzYjVkMQY6BkVG--94ef68204dd4d1714349c1e2f4c20ece67fb4bc9" sh scripts/comments/create.sh
```

The response from the server is 201 so that is good and we can see the note has `ID: 6` and `note: "hahahah"` which is good.
```rb
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"378864e1d12d0b2168af853c9d835f03"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: d38d4732-46d2-4272-933b-9eb7fb0b7ded
X-Runtime: 0.021843
Vary: Origin
Transfer-Encoding: chunked

{"comment":{"id":6,"note":"hhahahah","date":"1990-07-03","movie":{"id":1,"title":"Scary Movie"},"user":{"id":1,"email":"gab@gab"}}}
```

This is your `update.sh` and that all looks good.
*update.sh*
```rb
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/comments/${ID}"
curl "${API}${URL_PATH}" \
  --include \
  --request PATCH \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "comment": {
      "movie_id": "'"${MOVIE_ID}"'",
      "note": "'"${NOTE}"'"
    }
  }'

echo
````

When you run `update.sh` it returns a 204 so that is good.
```rb
ID=6 MOVIE_ID=1 NOTE="blah" TOKEN="BAhJIiVhMzU2ZmEyNTdiZjExZTJmNTA2MWNlMjIwMDUzYjVkMQY6BkVG--94ef68204dd4d1714349c1e2f4c20ece67fb4bc9" sh scripts/comments/update.sh
```

The response from the server is 204 NO Content so that is good.
```rb
HTTP/1.1 204 No Content
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: no-cache
X-Request-Id: 9ca37f16-8dd7-42bf-8ab7-118dcbe1811e
X-Runtime: 0.015744
Vary: Origin
```

When you check the server log, it does not show any errors so that is good.  It says `Completed 204` which is what we got back so that's good.
```rb
Started PATCH "/comments/6" for 127.0.0.1 at 2017-02-18 13:49:13 -0500
Processing by CommentsController#update as */*
  Parameters: {"comment"=>{"movie_id"=>"1", "note"=>"blah"}, "id"=>"6"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "a356fa257bf11e2f5061ce220053b5d1"], ["LIMIT", 1]]
  Comment Load (0.6ms)  SELECT  "comments".* FROM "comments" WHERE "comments"."user_id" = $1 AND "comments"."id" = $2 LIMIT $3  [["user_id", 1], ["id", 6], ["LIMIT", 1]]
   (0.2ms)  BEGIN
  Movie Load (0.2ms)  SELECT  "movies".* FROM "movies" WHERE "movies"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  COMMIT
Completed 204 No Content in 7ms (ActiveRecord: 1.3ms)
```

Now ideally if everything is working then our comment should no longer have `note: "hahahaha"` it should have been updated with `note: "blah"`.

When you run your `show.sh` it returns 200 so that is good.
```rb
ID=6 sh scripts/comments/show.sh 
```

The server response of 200 also shows us that the comment has been *SUCCESSFULLY* updated with `note: "blah"` as expected.
```rb
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"2e4ada13e283c961a70d7dc3e8d65ef5"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 0d6d2154-a283-4751-8718-d3dcf91ebc87
X-Runtime: 0.008803
Vary: Origin
Transfer-Encoding: chunked

{"comment":{"id":6,"note":"blah","date":"1990-07-03","movie":{"id":1,"title":"Scary Movie"},"user":{"id":1,"email":"gab@gab"}}}
```

After passing in the `ID=6` it looks like your update is working great!  I think `index.sh` would be better suited for another issue and be sure to include your `index.sh` page and the `comments_controller.rb`.
