### ISSUE TITLE
Locked out of creating an athlete, even with a token

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/full-stack-project#614]
Hi, continuing from this [thread](https://github.com/ga-wdi-boston/full-stack-project/issues/612): 
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/athletes"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "athlete": {
      "given_name": "'"${GIVEN_NAME}"'",
      "surname": "'"${SURNAME}"'",
      "date_of_birth": "'"${DOB}"'"
    }
  }'
```
AthleteController:
```rb
# frozen_string_literal: true

class AthletesController < OpenReadController
  before_action :set_athlete, only: [:update, :destroy]

  # GET /athletes
  def index
    @athletes = Athlete.all

    render json: @athletes
  end

  # GET /athletes/1
  def show
    render json: Athlete.find(params[:id])
  end

  # POST /athletes
  def create
    @athlete = current_user.athletes.build(athlete_params)

    if @athlete.save
      render json: @athlete, status: :created
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /athletes/1
  def update
    if @athlete.update(athlete_params)
      head :no_content
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end

  # DELETE /athletes/1
  def destroy
    @athlete.destroy
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_athlete
    @athlete = current_user.athletes.find(params[:id])
  end
  private :set_athlete

  # Only allow a trusted parameter "white list" through.
  def athlete_params
    params.require(:athlete).permit(:given_name, :surname,
                                    :date_of_birth)
  end
  private :athlete_params
end
```

I tried this, with and without the token:
```node
TOKEN="<token>" GIVEN_NAME='la' SURNAME='pa' DOB='1993-01-16' sh scripts/athletes/create.sh 
```
I think without the token I got this:
```
NoMethodError (undefined method `password_digest' for #<Athlete:0x007f86b6349d30>
Did you mean?  password):
  
app/controllers/athletes_controller.rb:22:in `create'
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 12:13:18 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "797453e5660ce49523d66e5452fe3254"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 20ms (ActiveRecord: 2.7ms)
```

and with the token I got this:
```
NoMethodError (undefined method `athletes' for #<User:0x007f86bc99b408>
Did you mean?  athlete
               athlete=):
  
app/controllers/athletes_controller.rb:20:in `create'
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 12:13:41 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)
```

**Comment by laurpaik-zz** [comment]
I think I copied the errors from the wrong spot, so here's what I'm getting:
```TOKEN="<token>" GIVEN_NAME='la' SURNAME='pa' DOB='1993-01-16' sh scripts/athletes/create.sh```

```
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 13:39:35 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "1821f347b06672c2f5e78c65d4080a1d"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.3ms)


  
NoMethodError (undefined method `athletes' for #<User:0x007f86b74aeeb8>
Did you mean?  athlete
               athlete=):
  
app/controllers/athletes_controller.rb:20:in `create'
```

**Comment by novakw267** [comment]
I am having the same issue as lauren

```
Started POST "/profiles" for 127.0.0.1 at 2017-02-18 13:04:37 -0500
Processing by ProfilesController#create as */*
  Parameters: {"profile"=>{"username"=>"grumpycat", "favorite_genre"=>"emo", "favorite_band"=>"dashboard confessional"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "1b7b04e4a44b08cdfa8fcb52a4a237b5"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.3ms)


  
NoMethodError (undefined method `profiles' for #<User:0x007f7f8a5caee8>
Did you mean?  profile
               profile=):
```
We were able to figure out by testing show that the relationship was working, at least I think. However we're trying to figure out where the referenced method may have been defined or where the miss match would be. The major difference between our codes is how we structured our relationships, mine are a one to one and then a one to many, there is no join table in my structure.

**Comment by MicFin** [comment]
@novakw267 Feel free to link to each other's issues, but also open separate issues and post your own code and errors.

**Comment by MicFin** [comment]
```
NoMethodError (undefined method `athletes' for #<User:0x007f86bc99b408>
Did you mean?  athlete
               athlete=):

NoMethodError (undefined method `profiles' for #<User:0x007f7f8a5caee8>
Did you mean?  profile
               profile=):
```

Undefined method `athletes` or `profiles` 
for `User` 
did you mean `athlete` or `athlete=` or `profile` or `profile=`.  

That seems to be saying that your `User` model does not have a method called `athletes` or `profiles` plural but does have a method called `athlete`, `profile` , `athlete=` and `profile=` singular.  

Where are you calling or passing `.profiles` or `.athletes`? 
```rb
  # POST /athletes
  def create
    @athlete = current_user.athletes.build(athlete_params)
```

`.athletes` and `.profiles` are instance methods on your `User` model, `current_user` is one instance of a `User`.
 
What is the two way relationship?
How do your relationships look in the `User.rb`, `Profile.rb` and `Athete.rb`?

**Comment by laurpaik-zz** [comment]
In Athlete.rb:
```rb
# frozen_string_literal: true

class Athlete < ApplicationRecord
  include Authentication
  has_many :workouts, through: :logs
  has_many :logs
  belongs_to :user

  validates :given_name, presence: true
  validates :surname, presence: true
  validates :date_of_birth, presence: true
end
```
In User.rb:
```rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_one :athlete
end
```

So when I changed  it to:
```rb
  # POST /athletes
  def create
    @athlete = current_user.athlete.build(athlete_params)

    if @athlete.save
      render json: @athlete, status: :created
    else
      render json: @athlete.errors, status: :unprocessable_entity
    end
  end
```
I got:
```
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 15:01:14 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "d3bd24b4493cf9d30c0f0a5ac5a88aed"], ["LIMIT", 1]]
  Athlete Load (0.3ms)  SELECT  "athletes".* FROM "athletes" WHERE "athletes"."user_id" = $1 LIMIT $2  [["user_id", 11], ["LIMIT", 1]]
Completed 500 Internal Server Error in 20ms (ActiveRecord: 0.5ms)


  
NoMethodError (undefined method `build' for nil:NilClass):
  
app/controllers/athletes_controller.rb:20:in `create'
```

**Comment by MicFin** [comment]
I wasn't sure why build `.build` wouldn't work, so I had to look on Google.  I searched `rails has_one build` and the top result was https://stackoverflow.com/questions/2472982/using-build-with-a-has-one-association-in-rails where it says:

The build method signature is different for  has_one and has_many associations.
```rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :messages
end
```

The build syntax for has_many association:
```rb
user.messages.build
```

The build syntax for has_one association:
```rb
user.build_profile  # this will work
user.profile.build  # this will throw error
```

Read the [has_one](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#M001834) association documentation for more details.

**Comment by laurpaik-zz** [comment]
Interesting... so now it's not reading password_digest, which I'm assuming it's seeing from the User?
```
Started POST "/athletes" for 127.0.0.1 at 2017-02-18 15:09:35 -0500
Processing by AthletesController#create as */*
  Parameters: {"athlete"=>{"given_name"=>"la", "surname"=>"pa", "date_of_birth"=>"1993-01-16"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "d3bd24b4493cf9d30c0f0a5ac5a88aed"], ["LIMIT", 1]]
  Athlete Load (0.3ms)  SELECT  "athletes".* FROM "athletes" WHERE "athletes"."user_id" = $1 LIMIT $2  [["user_id", 11], ["LIMIT", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 38ms (ActiveRecord: 0.8ms)


  
NoMethodError (undefined method `password_digest' for #<Athlete:0x007f86b67b1198>
Did you mean?  password):
  
app/controllers/athletes_controller.rb:22:in `create'

```
But we're not supposed to change password_digest, correct?

**Comment by laurpaik-zz** [comment]
Nevermind, I commented out `include Authentication` in my Athlete.rb model and it worked.

**Comment by laurpaik-zz** [comment]
For the record, because of the has_one relationship, 
```rb
  def set_example
    @example = current_user.examples.find(params[:id])
  end
```
will also not work in the controller.
instead, I did this, and now my update feature also works:
```rb
def set_athlete
    @athlete = Athlete.where(id: params[:id], user: current_user).take
  end
```

**Comment by jrhorn424** [comment]
@laurpaik You're filing great issues. Thanks.

Please prefer this:

```ruby
# "GOOD"
def set_athlete
  @athlete = Athlete.find_by(id: params[:id], user: current_user)
end
```

And not this:

```ruby
# "BAD"
def set_athlete
  @athlete = Athlete.where(id: params[:id], user: current_user).take
end
```

**Comment by jrhorn424** [comment]
```ruby
# THE VERY BEST
def set_athlete
  @athlete = current_user.athlete.find(params[:id])
end
```

If this wasn't working before, I'd like to know why. I suspect you were using `athletes` instead of `athlete`.

**Comment by laurpaik-zz** [comment]
This was my error when I changed it to THE VERY BEST:
```
Started PATCH "/athletes/1" for 127.0.0.1 at 2017-02-22 11:13:06 -0500
Processing by AthletesController#update as */*
  Parameters: {"athlete"=>{"given_name"=>"Lauren", "surname"=>"Bae", "date_of_birth"=>"1993-01-16"}, "id"=>"1"}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "9cc534e1888c274580d88dad3f5ad538"], ["LIMIT", 1]]
  Athlete Load (5.8ms)  SELECT  "athletes".* FROM "athletes" WHERE "athletes"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
Completed 500 Internal Server Error in 39ms (ActiveRecord: 6.5ms)


  
NoMethodError (undefined method `find' for #<Athlete:0x007fb04fe53290>):
  
app/controllers/athletes_controller.rb:17:in `set_athlete'
```

**Comment by laurpaik-zz** [comment]
```rb
  def set_athlete
    @athlete = current_user.athlete.find(params[:id])
  end
  private :set_athlete
```

**Comment by laurpaik-zz** [comment]
Jokes, GOOD worked:
```rb
  def set_athlete
    @athlete = Athlete.find_by(id: params[:id], user: current_user)
  end
  private :set_athlete
```
```
Started PATCH "/athletes/1" for 127.0.0.1 at 2017-02-22 11:14:38 -0500
Processing by AthletesController#update as */*
  Parameters: {"athlete"=>{"given_name"=>"Lauren", "surname"=>"Bae", "date_of_birth"=>"1993-01-16"}, "id"=>"1"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "9cc534e1888c274580d88dad3f5ad538"], ["LIMIT", 1]]
  Athlete Load (0.5ms)  SELECT  "athletes".* FROM "athletes" WHERE "athletes"."id" = $1 AND "athletes"."user_id" = 1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.1ms)  BEGIN
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  SQL (6.3ms)  UPDATE "athletes" SET "surname" = $1, "updated_at" = $2 WHERE "athletes"."id" = $3  [["surname", "Bae"], ["updated_at", 2017-02-22 16:14:38 UTC], ["id", 1]]
   (5.7ms)  COMMIT
Completed 204 No Content in 46ms (ActiveRecord: 13.3ms)
```
