### ISSUE TITLE
Rendered ActiveModel::Serializer::Null with ActiveModel::Errors

### ISSUE THREAD

**Issue by ggabrakadabra** [ga-wdi-boston/full-stack-project#640]
I added create to my front end for movies.
create was working on my backend, but on the frontend when I run create it gives this error in the backend server

```rb
Started POST "//movies" for 127.0.0.1 at 2017-02-20 12:46:14 -0500
Processing by MoviesController#create as */*
  Parameters: {"movie"=>{"title"=>"yuouu"}, "submit"=>"Add Movie"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "98a9a8c9fbf1fbf5b8b751d7a64b251c"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.1ms)
Completed 422 Unprocessable Entity in 6ms (Views: 0.6ms | ActiveRecord: 0.6ms)
```

this is my front end code

events.js
```
const onCreateMovies = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.createMovies(data)
  .done(ui.success)
  .fail(ui.fail)
  ;
};
```

api.js
```
const createMovies = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/movies',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};
```
this is my handler
```
  $('#create-movie').on('submit', onCreateMovies);
```

and this is my html

```
        <form id="create-movie">
          <fieldset>
            <legend id="create-movie-title">Create Movie</legend>
            <input class="add-movie" type="text" name="movie[title]" value="" placeholder="movie title">
            <input class="add-movie" type="submit" name="submit" value="Add Movie">
          </fieldset>
        </form>
```

How can I make this work from the frontend?

**Comment by ggabrakadabra** [comment]
I think this might be a backend problem so here are my related files for that.

movie.rb
```
# frozen_string_literal: true

# :nodoc:
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments, through: :users
  has_many :users
  validates :title, presence: true
  validates :user_id, presence: true
end
```

movie_controller
```
# frozen_string_literal: true

# :nodoc:
class MoviesController < OpenReadController
  before_action :set_movie, only: [:update, :destroy]

  # GET /movies
  def index
    @movie = Movie.all

    render json: @movie
  end

  # GET /movies/1
  def show
    @movie = Movie.find(params[:id])
    render json: @movie
  end

  # POST /movies
  def create
    @movie = current_user.movies.build(movie_params)

    if @movie.save
      render json: @movie, status: :created
    else
      render json: @movie.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /movies/1
  def update
    if @movie.update(movie_params)
      head :no_content
    else
      render json: @movie.errors, status: :unprocessable_entity
    end
  end

  # DELETE /movies/1
  def destroy
    @movie.destroy
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    # @movie = current_user.movies.find(params[:id])
    @movie = current_user.movies.find(params[:id])
  end
  private :set_movie

  # Only allow a trusted parameter "white list" through.
  def movie_params
    params.require(:movie).permit(:title)
  end
  private :movie_params
end
```

movie serializer

```
# frozen_string_literal: true

# :nodoc:
class MovieSerializer < ActiveModel::Serializer
  attributes :id, :title
end
```

I don't see anything wrong but there's definitely something going on that I'm missing. Please let me know

**Comment by ggabrakadabra** [comment]
should I nuke and pave?

**Comment by raq929** [comment]
If you can create a movie using curl, then I think you're OK in the back end.

**Comment by raq929** [comment]
I would take the name off of your submit button in the html, because that's causing `getFormFields` to send data about the button to the server. I'm not sure that's the problem, because it seems to be quitting right after it finds the user.
Try that, and see what happens.
If you get the same result, I would double check that the token you're using is valid. (Did you sign or this user in another window or something?)
Is there any more to that error message?

**Comment by ggabrakadabra** [comment]
now I am getting this error

```rb
"{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: movie\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/movies_controller.rb:54:in `movie_params'"},{"id":2,"trace":"app/controllers/movies_controller.rb:22:in `create'"}],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_controller/metal/strong_parameters.rb:310:in `require'"},{"id":3,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":6,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"},{"id":7,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'"},{"id":8,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'"},{"id":9,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":11,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":12,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":13,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":14,"trace":"actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":15,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":16,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":17,"trace":"activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":18,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":19,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":20,"trace":"actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":21,"trace":"activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":22,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":23,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":24,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":25,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":26,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":27,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":28,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":29,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":30,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":31,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":32,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"},{"id":33,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":34,"trace":"activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'"},{"id":35,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":36,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":37,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":38,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":39,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":40,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":41,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":42,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":43,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":44,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":45,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":46,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":47,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":48,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":49,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":50,"trace":"actionpack (5.0.1) lib/…in `block (2 levels) in compile'"},{"id":9,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'"},{"id":11,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'"},{"id":12,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":13,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'"},{"id":14,"trace":"actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'"},{"id":15,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"},{"id":16,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'"},{"id":17,"trace":"activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'"},{"id":18,"trace":"activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'"},{"id":19,"trace":"actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'"},{"id":20,"trace":"actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'"},{"id":21,"trace":"activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'"},{"id":22,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'"},{"id":23,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'"},{"id":24,"trace":"actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'"},{"id":25,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'"},{"id":26,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"},{"id":27,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'"},{"id":28,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'"},{"id":29,"trace":"actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'"},{"id":30,"trace":"actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'"},{"id":31,"trace":"rack (2.0.1) lib/rack/etag.rb:25:in `call'"},{"id":32,"trace":"rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"},{"id":33,"trace":"rack (2.0.1) lib/rack/head.rb:12:in `call'"},{"id":34,"trace":"activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'"},{"id":35,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'"},{"id":36,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'"},{"id":37,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'"},{"id":38,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'"},{"id":39,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'"},{"id":40,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":41,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"},{"id":42,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'"},{"id":43,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":44,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":45,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":46,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":47,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":48,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":49,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":50,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":51,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":52,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":53,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":54,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":55,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":56,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":57,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":58,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":59,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":60,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":61,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":62,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}]}}"
```

and this in the back end server

```
Started POST "//movies" for 127.0.0.1 at 2017-02-20 15:03:03 -0500
Processing by MoviesController#create as */*
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "205de25f15b6cfbd5082e02813893823"], ["LIMIT", 1]]
Completed 400 Bad Request in 3ms (ActiveRecord: 0.4ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: movie):
  
app/controllers/movies_controller.rb:54:in `movie_params'
app/controllers/movies_controller.rb:22:in `create'
```

**Comment by ggabrakadabra** [comment]
I thought I was supposed to have 
```
            <input class="add-movie" type="text" name="movie[title]" placeholder="movie title">
```
because that's how it knows where to store the new movie title?

**Comment by raq929** [comment]
Yes, you do need that. You just don't need name on the submit button. If you put that line back in, I suspect this will work.

**Comment by ggabrakadabra** [comment]
That line is in, but I'm still getting 422 unprocessable entity
and a user must exist but I am logged in

this is my error

```
Started POST "//movies" for 127.0.0.1 at 2017-02-20 15:53:23 -0500
Processing by MoviesController#create as */*
  Parameters: {"movie"=>{"title"=>"gsdgdss"}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "7af2329b335fc3b262db160e60f24b40"], ["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.08ms)
Completed 422 Unprocessable Entity in 23ms (Views: 2.8ms | ActiveRecord: 0.7ms)
```

**Comment by ggabrakadabra** [comment]
I think it might be a problem with my validation between my users, movies, comments and favorites. 

movie.rb
```
# frozen_string_literal: true

# :nodoc:
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments, through: :users
  has_many :users
  validates :title, presence: true
  validates :user_id, presence: true
end
```

comment.rb
```
# frozen_string_literal: true

# :nodoc:
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates :user, presence: true
  validates :movie, presence: true
  validates :note, presence: true
end
```

user.rb
```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :favorites
  has_many :movies, through: :comments
  has_many :comments
end
```

favorites.rb
```
# frozen_string_literal: true

# :nodoc:
class Favorite < ApplicationRecord
  belongs_to :user
  has_many :movies, through: :users
  has_many :users
  validates :movie_id, presence: true
end
```

I think this is where my problem is.

Comments are supposed to be my join table between users and movies and I also added in favorites but that's a one to many with users

**Comment by ggabrakadabra** [comment]
Can you help me correct my relationships?

**Comment by laurpaik-zz** [comment]
How do your Movie and Favorite both have many users and belong to user? (genuinely curious if that kind of relationship is allowed)

**Comment by ggabrakadabra** [comment]
Changed it to this

```
# frozen_string_literal: true
class User < ApplicationRecord
  include Authentication
  has_many :favorites
  has_many :movies, through: :comments
  has_many :comments
end
```

```
# frozen_string_literal: true

# :nodoc:
class Movie < ApplicationRecord
  has_many :users, through: :comments
  has_many :comments
  validates :title, presence: true
end
```

```
# frozen_string_literal: true

# :nodoc:
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :movie_id, presence: true
end
```

```
# frozen_string_literal: true

# :nodoc:
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user
  validates :user, presence: true
  validates :movie, presence: true
end
```
