### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by novakw267** [ga-wdi-boston/full-stack-project#643]
I am getting a no method error from my server after logging into a profile and trying to create a new post in node. 

create
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/blog_templates"
curl "${API}${URL_PATH}" \
  --include \
  --request POST\
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "blog_template": {
      "blog_title": "'"${BLOG_TITLE}"'",
      "subject": "'"${SUBJECT}"'",
      "body": "'"${BODY}"'"
    }
  }'
```
add profiles to blog
```
class AddProfileToBlogTemplates < ActiveRecord::Migration[5.0]
  def change
    add_reference :blog_templates, :profile, index: true, foreign_key: true, null: false
  end
end
```
blog template controller
```# frozen_string_literal: true

# :nodoc:
class BlogTemplatesController < OpenReadController
  before_action :set_blog_template, only: [:show, :update, :destroy]

  # GET /blog_templates
  def index
    @blog_templates = BlogTemplate.all

    render json: @blog_templates
  end

  # GET /blog_templates/1
  def show
    render json: @blog_template
  end

  # POST /blog_templates
  def create
    @blog_template = current_user.BlogTemplate.new(blog_template_params)

    if @blog_template.save
      render json: @blog_template, status: :created
    else
      render json: @blog_template.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /blog_templates/1
  def update
    if @blog_template.update(blog_template_params)
      render json: @blog_template
    else
      render json: @blog_template.errors, status: :unprocessable_entity
    end
  end

  # DELETE /blog_templates/1
  def destroy
    @blog_template.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog_template
    @blog_template = BlogTemplate.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def blog_template_params
    params.require(:blog_template).permit(:blog_title, :subject, :body)
  end
  private :set_blog_template, :blog_template_params
end
```
command in command line
```
TOKEN="****(i am posting a token for the user)" BLOG_TITLE='Testing' SUBJECT='OMG maybe?' BODY='Did it work, did it work?' sh scripts/blog_templates/create.sh
```
finally  the server error
```
Started POST "/blog_templates" for 127.0.0.1 at 2017-02-20 15:14:44 -0500
Processing by BlogTemplatesController#create as */*
  Parameters: {"blog_template"=>{"blog_title"=>"Testing", "subject"=>"OMG maybe?", "body"=>"Did it work, did it work?"}}
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "aac42e7a9547fd62890baae7c2266c92"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.7ms)


  
NoMethodError (undefined method `BlogTemplate' for #<User:0x007f82abc6a568>):
  
app/controllers/blog_templates_controller.rb:21:in `create'
``` 
I did the same thing when I linked my user to my profile and I am able to create one profile per user which is what I want and the profile is only crudable when I am logged in as the correct user.

**Comment by raq929** [comment]
`current_user` does not have a BlogTemplates method. Look at the `ExamplesController`.
I think what you want here is `current_user.blog_templates.build`.

**Comment by novakw267** [comment]
That was an ideration of that I hadn't tried... However I still received a similar error
```
Started POST "/blog_templates" for 127.0.0.1 at 2017-02-20 16:06:16 -0500
Processing by BlogTemplatesController#create as */*
  Parameters: {"blog_template"=>{"blog_title"=>"Testing", "subject"=>"OMG maybe?", "body"=>"Did it work, did it work?"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "aac42e7a9547fd62890baae7c2266c92"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.3ms)


  
NoMethodError (undefined method `blog_templates' for #<User:0x007f82a6387770>):
  
app/controllers/blog_templates_controller.rb:21:in `create'
```

**Comment by laurpaik-zz** [comment]
Did you try 
```
TOKEN="****(i am posting a token for the user)" ID=<id number that matches your token> BLOG_TITLE='Testing' SUBJECT='OMG maybe?' BODY='Did it work, did it work?' sh scripts/blog_templates/create.sh
```
?

**Comment by novakw267** [comment]
Unfortunately same result.

**Comment by raq929** [comment]
What do your models look like? Have you defined the relationship there?

**Comment by novakw267** [comment]
I at least think I have those set up correctly 
profile model
```
# frozen_string_literal: true

# :nodoc:
class Profile < ApplicationRecord
  belongs_to :user
  has_many :blog_templates
  validates :username, presence: true
end
```
blog model
```
# frozen_string_literal: true

# :nodoc:
class BlogTemplate < ApplicationRecord
  belongs_to :profile
  delegate :blog_templates, to: :profiles
  validates :blog_title, presence: true
  validates :subject, presence: true
  validates :body, presence: true
end
```
This is my add profile to blogs
```
# frozen_string_literal: true

# :nodoc:
class AddProfileToBlogTemplates < ActiveRecord::Migration[5.0]
  def change
    add_reference :blog_templates, :profile, index: true, foreign_key: true,
                   null: false
  end
end
```

**Comment by raq929** [comment]
OK. So current_user doesn't actually have `blog_templates`, which explains why you're getting this error. 
I'd try adding a `has_many`/`through` relationship to your user model.
You can find info on this in the `rails-api-many-to-many` repo, or just google `rails has many through`

**Comment by novakw267** [comment]
Sorry I am little confused why I would need that, because I am not using a join table. I am also not doing a many to many. I was trying to structure a one to many of one profile to many blog posts. Profile is just an extra layer on top of the user. I could technically just go user straight to blog, and forgo to the profile entirely?

**Comment by laurpaik-zz** [comment]
I think you don't need it to be a many-to-many to have a has_many/through... My understanding was if you go through one relationship to get to another, a has_many/through is possible

**Comment by novakw267** [comment]
I thought the whole point of the profile was to keep it a step away from user for security, and to be able to access the auth of user through profile without directly connecting to it?

**Comment by raq929** [comment]
Try `current_user.profile.blog_templates.build()` instead.

**Comment by raq929** [comment]
On further thought/discussion, it's not actually a has_many/through relationship, because blog_templates has the profile id, and profile has the user id. If it were has_many/through, both profile would hold user_id and blog_template_id. 
(This is not relevant to what we're trying now, but i wanted to add the explanation.)

**Comment by raq929** [comment]
If you try the above and it doesn't work, come see me. (Classroom 6)

**Comment by novakw267** [comment]
Not sure if this is helpful but adding 
```
# frozen_string_literal: true

# :nodoc:
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_one :profile
  has_many :blog_templates, through: :profile
end
```
Resulted in
```
Started POST "/blog_templates" for 127.0.0.1 at 2017-02-21 10:59:02 -0500
Processing by BlogTemplatesController#create as */*
  Parameters: {"blog_template"=>{"blog_title"=>"Testing", "subject"=>"OMG maybe?", "body"=>"Did it work, did it work?"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "bfdac5f29d9e2cb6e2a0fc8be3d10f95"], ["LIMIT", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.11ms)
Completed 422 Unprocessable Entity in 75ms (Views: 4.2ms | ActiveRecord: 4.4ms)
``` 
and then taking that out again I tried the new command you gave me that gave me the same no method error with user as the method is referenced 
```
Started POST "/blog_templates" for 127.0.0.1 at 2017-02-21 11:01:55 -0500
Processing by BlogTemplatesController#create as */*
  Parameters: {"blog_template"=>{"blog_title"=>"Testing", "subject"=>"OMG maybe?", "body"=>"Did it work, did it work?"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "bfdac5f29d9e2cb6e2a0fc8be3d10f95"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 37ms (ActiveRecord: 0.3ms)


  
NameError (undefined local variable or method `user' for #<BlogTemplatesController:0x007faba18a5800>):
  
app/controllers/blog_templates_controller.rb:21:in `create'
```
I will also come see you now.

**Comment by novakw267** [comment]
So in the blog_template controller we changed 
```
@blog_template = current_user.profile.blog_templates.build(blog_template_params)
```
Which when tested in pry worked and created a  blog, so that meant it wasn't connecting beyond the database. 

And in the Blog_template serializer we changed
```
# frozen_string_literal: true

# :nodoc:
class BlogTemplateSerializer < ActiveModel::Serializer
  attributes :id, :blog_title, :subject, :body, :editable

  def editable
    scope == object.profile.user
  end
end
``` 
By adding the .profile.user instead of just .user allowed for the bridge between the profile and the user.
