### ISSUE TITLE
AJAX requests

### ISSUE THREAD

**Issue by kaylal12** [ga-wdi-boston/full-stack-project#65]
Everything seems to be working with curl so now i want to create the ajax requests.
I have made a working ajax request for registration so I am kind of aware of how the format will be.
My ajax request for login seems to be working but i receive a weird error.

```
$("#login").on('submit', function(event) {
    $.ajax({
      method: 'POST',
      url: inspire_url + '/login',
      data: {
        credentials: {
          email: $('#user_email').val(),
          password: $('#user_password').val()
        }
      }
    }).done(function(){
      $("#login").hide();
      $("#logout").show();
    }).fail(function(){
      console.log("error");
    });
  });
```

```
 User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "abc@abc.com"]]
  SQL (0.7ms)  UPDATE "users" SET "token" = '621eb9319c5073277d286e5aaa4f810c', "updated_at" = '2015-11-12 13:55:55.288396' WHERE "users"."id" = $1  [["id", 2]]
Completed 200 OK in 84ms (Views: 0.4ms | ActiveRecord: 1.3ms)
[2015-11-12 08:55:55] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:14 
    /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `eof?'
    /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/httpserver.rb:80:in `run'
    /usr/local/var/rbenv/versions/2.2.3/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Other than this error, I am not completely sure how to create ajax requests that requires authentication (how do i take the token from the user?)

**Comment by srhoulam** [comment]
Kayla, you need to stringify your request payload. Here are some changes to the options hash passed to `$.ajax`:

``` js
data: JSON.stringify({
  credentials: {
    email: $('#user_email').val(),
    password: $('#user_password').val()
  }
})
```

and one more key-value pair that you need in your AJAX options hash:

``` js
contentType: 'application/json'
```

**Comment by kaylal12** [comment]
That works!

To start on the ajax request for logout i have done:

```
$("#logout").on('click', function(event){
    $.ajax({
      method: 'DELETE',
      url: inspire_url + '/logout' // + id?
      headers: {
        Authorization: 'Token token=' + token
      }
    })
  });
```

How would I reach a specific user id and how do i get the token from the user?

**Comment by gaand** [comment]
The function passed to `.done` should accept a parameter `data` that contains a user object including a token (if you used my project2-api).  You need to save the token somewhere.

**Comment by srhoulam** [comment]
You get the user ID and token from the server's response to your login request. You need to store them for later uses such as logging out, as Antony said.

**Comment by kaylal12** [comment]
```
$("#login").on('submit', function(event) {
    event.preventDefault();
    $.ajax({
      method: 'POST',
      url: inspire_url + '/login',
      data: JSON.stringify({
        credentials: {
          email: $('#user_email').val(),
          password: $('#user_password').val()
        }
      }),
      contentType: 'application/json'
    }).done(function(data){
      $("#login").hide();
      $("#open-register").hide();
      $("#logout").show();
      token = data.user.token;
      id = data.user.id;
    }).fail(function(){
      console.log("error");
    });
  });
```

```
$("#logout").on('click', function(event){
    $.ajax({
      method: 'DELETE',
      url: inspire_url + '/logout/' + id,
      headers: {
        Authorization: 'Token token=' + token
      }
    }).done(function(){
      $("#login").show();
      $("#open-register").show();
    }).fail(function(){
      console.log("error");
    })
  });
```

Got it to work! Thank you!
