### ISSUE TITLE
Cannot create Review on client side 

### ISSUE THREAD

**Issue by AshlenPrice** [ga-wdi-boston/full-stack-project#674]
I'm trying to complete my createReview function on the client side and when I submit the call I keep getting a "404 bad request".  

I get the same error in the console as I do in my server. It says I have fields empty/missing. I went to my back end to make sure that I could still create reviews on the back end, and I still can. I'm passing in the same data on the front end as I am on the back. The request seems to be going through just failing to create the record. Having a user ID in the request is not required, but I tried it both ways. 

Please help.

api.js
``` js
const createReview = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/reviews',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};
```
events.js
```js
const onCreateReview = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);
  api.createReview(data)
    .then((response) => {
      store.log = response.log;
      return store.log;
    })
    .then(ui.onCreateSuccess)
    .catch(ui.onError);
};
```

ui.js 
```js
const onCreateSuccess =function() {
  console.log('Successful log');
};
```
This is what my server says 
```
Started POST "/reviews" for 127.0.0.1 at 2017-02-21 21:16:48 -0500
Processing by ReviewsController#create as */*
  Parameters: {"content"=>{"review_content"=>"Good book", "user_id"=>"2"}, "content\""=>{"book_id"=>{"\""=>"2"}}}
  User Load (54.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "8de7d533e292318f8c83770d6854ce3f"], ["LIMIT", 1]]
Completed 400 Bad Request in 184ms (ActiveRecord: 54.2ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: review):
  
app/controllers/reviews_controller.rb:51:in `review_params'
app/controllers/reviews_controller.rb:19:in `create'
```

This is what my Reviews controller looks like
```ruby
# frozen_string_literal: true
class ReviewsController < OpenReadController
  before_action :set_review, only: [:update, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all

    render json: @reviews
  end

  # GET /reviews/1
  def show
    render json: Review.find(params[:id])
  end

  # POST /reviews - need to add user to this. Only a user can create
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /reviews/1
  def update
    if @review.update(review_params)
      render json: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end

  # DELETE /reviews/1
  def destroy
    @review.destroy

    head :no_content
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:review_content, :book_id)
  end
  private :set_review, :review_params
end
```
![image](https://cloud.githubusercontent.com/assets/24688275/23194542/b9b26b8e-f87c-11e6-95fe-5f23124b200f.png)

**Comment by bernardlee** [comment]
Your server's log displaying `Parameters: {"content"=>{"review_content"=>"Good book", "user_id"=>"2"}, "content\""=>{"book_id"=>{"\""=>"2"}}}` means that you're acquiring and sending your data in the wrong form.

**Comment by raq929** [comment]
What does your HTML look like? `getFormFields` formats your data based on the names in the form.

**Comment by AshlenPrice** [comment]
Awesome thank you  Bernard! Now I have an unprocessable entity 
![image](https://cloud.githubusercontent.com/assets/24688275/23195629/9ffe1138-f882-11e6-8861-ccd00453bfc0.png)
This is what my  server says 
```
Started POST "/reviews" for 127.0.0.1 at 2017-02-21 22:09:16 -0500
Processing by ReviewsController#create as */*
  Parameters: {"review"=>{"review_content"=>"Greatness"}, "review\""=>{"book_id"=>{"\""=>"3"}}}
  User Load (20.1ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "8a7b07740acf22903a6148def809e6d1"], ["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.8ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.8ms)
Completed 422 Unprocessable Entity in 166ms (Views: 14.4ms | ActiveRecord: 21.1ms)
```
That's my serializer
```ruby
# frozen_string_literal: true
class ReviewSerializer < ActiveModel::Serializer
  attributes :id, :review_content, :book_id, :user_id
 #  def editable
 #    scope == object.user
 # end
end
```
My model 
```ruby
# frozen_string_literal: true
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :review_content, presence: true
  validates :book, presence: true
  validates :user, presence: true
end
```
This is my script
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/reviews"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN"\
  --data '{
    "review": {
      "review_content": "'"${REVIEW_CONTENT}"'",
      "book_id": "'"${BOOK_ID}"'"
        }
  }'

echo
```

**Comment by AshlenPrice** [comment]
@raq929 I fixed that first issue. I'm now on to the next.

**Comment by raq929** [comment]
What's your schema for this? It looks like your model requires a `book` field, but you're only giving it `book_id`. Which is the right thing to do - if your table does have the separate `book` column, I would remove it.

**Comment by raq929** [comment]
Does that curl script work? Because if yes, I'm probably wrong. 😝

**Comment by AshlenPrice** [comment]
This is my schema
```ruby
  create_table "reviews", force: :cascade do |t|
    t.text     "review_content"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.integer  "user_id"
    t.integer  "book_id"
    t.index ["book_id"], name: "index_reviews_on_book_id", using: :btree
    t.index ["user_id"], name: "index_reviews_on_user_id", using: :btree
  end
```
I notice it has 2 book id one as an integer and another as an index. 
My curl script works, I can create reviews.
Would remove it by running a migration?

**Comment by raq929** [comment]
Take a look at how these parameters:
`{"review"=>{"review_content"=>"Greatness"}, "review\""=>{"book_id"=>{"\""=>"3"}}}`
Are different from these ones:
```
--data '{
    "review": {
      "review_content": "'"${REVIEW_CONTENT}"'",
      "book_id": "'"${BOOK_ID}"'"
        }
  }'
```

And then post your HTML please, because I think it's a problem with how you're naming things in the form.

**Comment by AshlenPrice** [comment]
HTML
```html
<!-- Create a new review -->
    <form class='create-review' id="review-post">
           <fieldset>
             <div class="form-group">
               <input type="text" name="review[review_content]" placeholder="Add your review">
               <input type="text" name=review"[book_id]" placeholder="Book id">
               <!-- <input type="text" name="content[user_id]" id="user-id"> -->
             </div>
             <button type="submit" class="btn btn-default">Create Review</button>
         </fieldset>
         </form>
```

Also is the difference ```"review\""=>{"book_id"=>{"\""=>"3"}``` and do I need to label that in the form ```book_id```

**Comment by raq929** [comment]
The problem is here: `name=review"[book_id]" `
Your quotes are in the wrong place. I'm actually shocked that `getFormFields` worked at all.
@gaand wrote you a damn robust function there.

**Comment by raq929** [comment]
(I think if you move the quotes, your data will be in the right place, and this will work.)

**Comment by AshlenPrice** [comment]
AMAZING!!!!! Thanks, Rachel that worked!
