### ISSUE TITLE
No method error 

### ISSUE THREAD

**Issue by wilsonkaya** [ga-wdi-boston/full-stack-project#676]
I am trying to call SendSmsJob method in my create controller but it gives me a no method error. 

```
class SMS
  def initialize(to_phone_number)
    @to_phone_number = to_phone_number
  end

  def client
    Twilio::REST::Client.new Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_token
  end

  def send(body)
    client.account.messages.create(
      :messaging_service_sid => Rails.application.secrets.twilio_messaging_service_sid,
      :to => @to_phone_number,
      :body => body
    )
  end
end
```

```
class SendSmsJob < ApplicationJob
  # queue_as :default

  def perform(message)
    SMS.new(message.to).send(message.body)
  end
end
```

```
# frozen_string_literal: true
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @message.update(from: '+15083068064', status: 'pending', direction: 'outbound-api')

    if @message.save
      SendSmsJob(@message)
      render json: @message, status: :created
    else
      render json: @message.errors, status: :unprocessable_entity
    end
  end

  def message_params
    params.require(:message).permit(:body)
  end
end

```

**Comment by raq929** [comment]
Please paste the error. It will tell you what's not a method, and then you have to figure out:
a) Should that actually be a method?
b) If yes, how do you make it one (probably a relationship)
c) If no, what else can you use.

Please type ruby or js after the first three backtics to format your code with colors so we can read it more easily. Thanks!

**Comment by wilsonkaya** [comment]
updated
```
  
  
NoMethodError (undefined method `SendSmsJob' for #<MessagesController:0x007fd28903f058>):
  
app/controllers/messages_controller.rb:7:in `create'
Started POST "/messages" for 127.0.0.1 at 2017-02-22 09:44:21 -0500
Processing by MessagesController#create as */*
  Parameters: {"message"=>{"to"=>"+15088080562", "body"=>"FATIH"}}
Unpermitted parameter: to
   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO "messages" ("from", "status", "body", "direction", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["from", "+15083068064"], ["status", "pending"], ["body", "FATIH"], ["direction", "outbound-api"], ["created_at", 2017-02-22 14:44:21 UTC], ["updated_at", 2017-02-22 14:44:21 UTC]]
   (12.3ms)  COMMIT
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
Completed 500 Internal Server Error in 56ms (ActiveRecord: 13.0ms)


  
NoMethodError (undefined method `SendSmsJob' for #<MessagesController:0x007fd2883a1df0>):
  
app/controllers/messages_controller.rb:8:in `create'



```

**Comment by raq929** [comment]
Makes sense to me, ruby definitely doesn't have a SendSmsJob method. Is this something you're getting from a gem? I would check their documentation and make sure you're using the correct method/spelling/capitalization.

Also, if you aren't totally sure you've met requirements and have a bug free project to show tomorrow, please concentrate on that and add this later. 😄

**Comment by wilsonkaya** [comment]
I believe my projects met with requirements. I have spent so much time to figure this out. So I would be glad to have a one on one to figure this out.

**Comment by bernardlee** [comment]
Sure.

**Comment by wilsonkaya** [comment]
Thank you.

**Comment by jrhorn424** [comment]
`ActiveJob` had to be activated for the API. Additionally, an instance of the API wrapper had to be created before the instance method could be called on it.
