### ISSUE TITLE
problem with db migrate

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#680]
When I run 
```
bin/rake db:migrate VERSION=0
```
then
```

bin/rake db:migrate db:seed db:examples

``` 
I get the following error
```
$ bin/rake db:migrate db:seed db:examples
Running via Spring preloader in process 69640
== 20170221212400 AddTrailsToReviews: migrating ===============================
-- add_reference(:reviews, :user, {:foreign_key=>true, :index=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "user_id" of relation "reviews" already exists
: ALTER TABLE "reviews" ADD "user_id" integer
/Users/scottlandry/wdi/projects/trail-rater/db/migrate/20170221212400_add_trails_to_reviews.rb:4:in `change'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "user_id" of relation "reviews" already exists
: ALTER TABLE "reviews" ADD "user_id" integer
/Users/scottlandry/wdi/projects/trail-rater/db/migrate/20170221212400_add_trails_to_reviews.rb:4:in `change'
-e:1:in `<main>'
PG::DuplicateColumn: ERROR:  column "user_id" of relation "reviews" already exists
/Users/scottlandry/wdi/projects/trail-rater/db/migrate/20170221212400_add_trails_to_reviews.rb:4:in `change'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
~/wdi/projects/trail-rater (inprogress)
$ 

```

my code is for add_user-to_reviews.rb

```
# frozen_string_literal: true
class AddUsersToReviews < ActiveRecord::Migration[5.0]
  def change
    add_reference :reviews, :user, foreign_key: true, index: true
  end
end

```
my code for add_trails_to_rwviews.rb
```
# frozen_string_literal: true
class AddTrailsToReviews < ActiveRecord::Migration[5.0]
  def change
    add_reference :reviews, :user, foreign_key: true, index: true
  end
end

```
i have tried changing references to column and back but i'm not sure why it is telling me that the relationship already exists

**Comment by raq929** [comment]
Your code for add trails to reviews and add user to reviews is exactly the same. I suspect you'll want to change the one for trails.

**Comment by Soboscott** [comment]
Thank you!

**Comment by Soboscott** [comment]
```

# frozen_string_literal: true
class AddTrailsToReviews < ActiveRecord::Migration[5.0]
  def change
    add_reference :reviews, :trails, foreign_key: true, index: true
  end
end

```

**Comment by jrhorn424** [comment]
I believe the migration has a typo in it and it may pop up as an issue at some point. The fix would be:

```diff
-    add_reference :reviews, :trails, foreign_key: true, index: true
+    add_reference :reviews, :trail, foreign_key: true, index: true
```

**Comment by jrhorn424** [comment]
You can verify by inspecting your schema for the `reviews` table. If it is incorrect, it will have a column named `trails_id`. If it is correct, it should say `trail_id`. (pluralization)

**Comment by Soboscott** [comment]
Thank you !
