### ISSUE TITLE
PATCH Update action through modal

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/full-stack-project#682]
Goal: update a climb with a generated id, meaning that the form fields are only the date and grade.
Before, I had to enter the id, date, and grade. I want to make the id automatic.

The backend expects 'data' which is the id, date, and grade.
I am having trouble having the data passed include the id when there is no form field for it, since I want that automized (user does have to enter an id).

Api:
```javascript
const update = function (data, id) {
  return $.ajax({
    url: config.apiOrigin + '/climbs/' + id,
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};
```

events:
```javascript
const onUpdate = function (event) {
  event.preventDefault();

  let id = $(event.target).data('id');
  let data = getFormFields(event.target);

  console.log(data);

  api.update(data, id)
    .then(ui.updateSuccess)
    .then(onIndex)
    .catch(ui.updateFailure);
};
```

handlebars
```handlebars
      <td><button  data-id="{{climb.id}}" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#updateClimbModal{{climb.id}}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
      <div id="updateClimbModal{{climb.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createClimbModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="createClimbModalLabel">Update Climb</h4>
            </div>
            <form class="update-climb"  data-id="{{climb.id}}">  // <= the climb's id is assigned to the form here
              <fieldset>
                <input class="clear-input-update" type="date" name="climb[date]" placeholder="date: e.g. 2000-12-20"><br><br>
                <select  class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButtonUpdate" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" name="climb[grade]">
                  <option placeholder="Select"></option>
                  <option value = "V0">V0</option>
                  <option value = "V1">V1</option>
                  <option value = "V2">V2</option>
                  <option value = "V2+">V2+</option>
                </select>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <input data-id="{{climb.id}}" type="submit" class="btn update btn-primary" name="submit" value="Submit">
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
```

The error that this code results in:
![screen shot 2017-02-22 at 10 59 16 am](https://cloud.githubusercontent.com/assets/24608045/23219839/1e354d30-f8ee-11e6-9863-8aca7a8a426c.png)

I need the data that is passed to the back end to be what it expects: id, date, grade, while also passing the id to the URL in the api.

**Comment by doremaxime** [comment]
The server error in terminal:
```terminal
Started PATCH "/climbs/83" for 127.0.0.1 at 2017-02-22 11:02:55 -0500
Processing by ClimbsController#update as */*
  Parameters: {"id"=>"83"}
  User Load (2.0ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "8d5da395cc9ce3b6bb8f8558573cf686"], ["LIMIT", 1]]
  Climb Load (1.1ms)  SELECT  "climbs".* FROM "climbs" WHERE "climbs"."user_id" = $1 AND "climbs"."id" = $2 LIMIT $3  [["user_id", 6], ["id", 83], ["LIMIT", 1]]
Completed 400 Bad Request in 62ms (ActiveRecord: 3.1ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: climb):
  
app/controllers/climbs_controller.rb:55:in `climb_params'
app/controllers/climbs_controller.rb:32:in `update'
```

**Comment by doremaxime** [comment]
I console logged the id before i it is sent to the api and it logs the correct id. This leads me to believe the URL is correct and that it is just the data that needs tweaking.

**Comment by raq929** [comment]
Your data isn't formatted correctly. Your climb params requires and object with `climb` at the top level: `{ "climb": { "id": 2}}` but you are sending `{"id"=>"83"}`
You also may want to watch out for numbers vs. strings.

**Comment by doremaxime** [comment]
By 'watch out for numbers vs. strings', are you talking about the id of the url?

**Comment by jrhorn424** [comment]
What's your handler registration look like for `onUpdate`?

**Comment by jrhorn424** [comment]
> By 'watch out for numbers vs. strings', are you talking about the id of the url?

Yes, but I don't think that's an issue here. @raq929's other point (about data format) is more cogent to the issue at hand.

**Comment by doremaxime** [comment]
the click handler in events.js:
```javascript
  $('.index').on('click', '.update', onUpdate);
```
I was having lunch so i'm trying out having **climb** as the top level right now

**Comment by jrhorn424** [comment]
I don't see anything that would match `.update` in your pasted markup above.

You should never listen for `clicks` on form buttons. Instead, target the form and listen for the `submit` event. This is the **root** cause of your problem. :wink:

**Comment by doremaxime** [comment]
I have it as ```click``` because my delete action has it like that and it works. Furthermore, If I change the update to ```submit```, it just refreshes the page.

the ```update``` is in the last input of the handlebars

**Comment by jrhorn424** [comment]
> I have it as click because my delete action has it like that and it works

That is not a justification to use it for update. That is not the pattern we established in the `jquery-ajax-*` lessons.

Using click for delete is OK. That doesn't mean it's OK for update.

> Furthermore, If I change the update to submit, it just refreshes the page.

That's because you have to `event.preventDefault`. As we did in `jquery-ajax-*`.

> the update is in the last input of the handlebars

I'm not sure what you mean here.

**Comment by doremaxime** [comment]
you said: I don't see anything that would match ```.update``` in your pasted markup above.
So I was saying where it was.

I do have ```event.preventDefault``` in my onUpdate function though.

**Comment by jrhorn424** [comment]
> > I don't see anything that would match .update in your pasted markup above.
>
> So I was saying where it was.

Ah, thank you! :smile:

I'll continue poking around.

**Comment by jrhorn424** [comment]
When I search through the following, I do not see anywhere `class="update"`:

```
      <td><button  data-id="{{climb.id}}" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#updateClimbModal{{climb.id}}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
      <div id="updateClimbModal{{climb.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createClimbModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="createClimbModalLabel">Update Climb</h4>
            </div>
            <form class="update-climb"  data-id="{{climb.id}}">  // <= the climb's id is assigned to the form here
              <fieldset>
                <input class="clear-input-update" type="date" name="climb[date]" placeholder="date: e.g. 2000-12-20"><br><br>
                <select  class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButtonUpdate" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" name="climb[grade]">
                  <option placeholder="Select"></option>
                  <option value = "V0">V0</option>
                  <option value = "V1">V1</option>
                  <option value = "V2">V2</option>
                  <option value = "V2+">V2+</option>
                </select>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <input data-id="{{climb.id}}" type="submit" class="btn update btn-primary" name="submit" value="Submit">
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
```

**Comment by jrhorn424** [comment]
>> Furthermore, If I change the update to submit, it just refreshes the page.
>
>  target the form and listen for the submit event

Are you targeting the form, or a button?

**Comment by doremaxime** [comment]
```<input data-id="{{climb.id}}" type="submit" class="btn **update** btn-primary" name="submit" value="Submit">```

I target the div, which inside has a handlebar generated button, which opens a modal, and inside is the form, which has inputs. Each row has an edit button which opens it's modal. When i click submit inside the modal, it should know which climb id it is, and also take the date and grade to send all three to the server.

**Comment by jrhorn424** [comment]
Thanks for your patience. I think I need to take my own advice and ❄️ 🐢 .

You are indeed targeting an input button.

> **target the form and listen for the submit event**

For `submit` events to work properly, you must target the form element, not it's submit button.

**Comment by doremaxime** [comment]
No worries :)

So something like this?:

```javascript
const addHandlers = () => {
document.getElementById("updateClimbModal{{climb.id}}").addEventListener("submit", onUpdate);
};
```

The modal climb.id is also being generated so I am wondering what element I can use to target since they are all generated to be unique.

**Comment by MicFin** [comment]
Please come over to my lair in the kitchen so I can look at this.

**Comment by MicFin** [comment]
@doremaxime please post the solution and close.

**Comment by doremaxime** [comment]
There were a few things wrong but here is the working code:

handlebars
```javascript
      <td><button  data-id="{{climb.id}}" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#updateClimbModal{{climb.id}}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
      <div id="updateClimbModal{{climb.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createClimbModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="createClimbModalLabel">Update Climb</h4>
            </div>
            <form class="update-climb"  data-climb="{{climb.id}}">
              <fieldset>
                <input class="clear-input-update" type="date" name="climb[date]"><br><br>
                <select  class="btn btn-secondary dropdown-toggle" type="button" name="climb[grade]" id="dropdownMenuButtonUpdate" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <option></option>
                  <option value = "V0">V0</option>
                  <option value = "V1">V1</option>
                  <option value = "V2">V2</option>
                </select>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <input data-id="{{climb.id}}" type="submit" class="btn update btn-primary" name="submit" value="Submit">
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>
</td>
      <td><button data-id="{{climb.id}}" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#destroyClimbModal{{climb.id}}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
        <div id="destroyClimbModal{{climb.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="destroyClimbModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="destroyClimbModalLabel">Are you sure?</h4>
              </div>
              <div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Nope</button>
                <input data-id="{{climb.id}}" type="submit" class="btn destroy btn-primary" name="submit" value="Yaaaasss"><br><br>
              </div>
            </div>
          </div>
        </div>
      </td>
```
ui:
```javascript
const updateSuccess = (id) => {
  console.log(id);
  debugger;
  $('.updateClimbModal'+id).modal('toggle');
  $('.modal-backdrop').remove();
};
```

Events:
```javascript
const onUpdate = function (event) {
  event.preventDefault();
  
  let id = $(event.target).data('climb');
  let userInput = getFormFields(event.target);

  api.update(userInput, id)
    .then(ui.updateSuccess(id))
    .then(onIndex)
    .catch(ui.updateFailure);
};

const addHandlers = () => {
  $('.index').on('submit', '.update-climb', onUpdate);
};
```

**Comment by jrhorn424** [comment]
@doremaxime Thanks for the excellent solution write-up!
