### ISSUE TITLE
I am getting a 500 error when I try to sign in

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#700]
it is pointing to my events.js line 13

```js

'use strict';

const getFormFields = require('../../../lib/get-form-fields');

const api = require('./api');
const ui = require('./ui');

const store = require('../store');

const onSignUp = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  api.signUp(data)
    .then(ui.signUpSuccess)
    .catch(ui.signUpFail);
};

const onSignIn = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);

  api.signIn(data)
    .then((response) => {
      store.user = response.user;
      return store.user;
    })
    .then(ui.signInSuccess)
    .catch(ui.signInFail);
};

const onChangePassword = function (event) {
  event.preventDefault();

  let data = getFormFields(event.target);

  api.changePassword(data)
    .then(ui.changePassSuccess)
    .catch(ui.changePassFail)
    ;
};

const onSignOut = function (event) {
  event.preventDefault();

  api.signOut()
    .then(() => {
      delete store.user;
      return store;
    })
    .then(ui.signOutSuccess)
    .catch(ui.failure);
};

const addHandlers = () => {
  $('#sign-up').on('submit', onSignUp);
  $('#sign-in').on('submit', onSignIn);
  $('#change-password').on('submit', onChangePassword);
  $('#sign-out').on('click', onSignOut);
};

module.exports = {
  addHandlers,
};

```
and my api.js line 7

```js
'use strict';

const config = require('../config');
const store = require('../store');

const signUp = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-up',
    method: 'POST',
    data,
  });
};

const signIn = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/sign-in',
    method: 'POST',
    data,
  });
};

const changePass = function (data) {
  return $.ajax({
    url: `${config.apiOrigin}/change-password/${store.user.id}`,
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};

const signOut = function () {
  return $.ajax({
    url: `${config.apiOrigin}/sign-out/${store.user.id}`,
    method: 'DELETE',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

module.exports = {
  signUp,
  signIn,
  changePass,
  signOut,
};

```
I can't find the error, 
I tried db nuke pave and reset my rails server
but still have the same issue

**Comment by raq929** [comment]
Please post the error that you get on the client side and the error that you see on your server.

I'm assuming you can log in via curl, but please double check that.

**Comment by Soboscott** [comment]
this is the rails server:

```

Started POST "/sign-up" for 127.0.0.1 at 2017-02-22 18:17:48 -0500
Started POST "/sign-up" for 127.0.0.1 at 2017-02-22 18:17:48 -0500
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  ActiveRecord::SchemaMigration Load (0.9ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by UsersController#signup as */*
Processing by UsersController#signup as */*
  Parameters: {"credentials"=>{"email"=>"al", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
  Parameters: {"credentials"=>{"email"=>"al", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
   (65.7ms)  BEGIN
   (1.0ms)  BEGIN
  User Exists (0.7ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "al"], ["LIMIT", 1]]
  User Exists (1.5ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "al"], ["LIMIT", 1]]
  SQL (1.1ms)  INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "al"], ["token", "43e14da371823b312dce7bc2da741016"], ["password_digest", "$2a$10$HdDsZfr8tZWO4U5DIxGNG.7ee1XVsryvXQTJJFefPtJstm1aVy.ai"], ["created_at", 2017-02-22 23:17:48 UTC], ["updated_at", 2017-02-22 23:17:48 UTC]]
   (6.3ms)  COMMIT
  User Exists (0.6ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND ("users"."id" != $2) LIMIT $3  [["email", "al"], ["id", 1], ["LIMIT", 1]]
  SQL (12.9ms)  INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "al"], ["token", "4a315ff785553f2296295b643435270d"], ["password_digest", "$2a$10$.JNIFxeDOO7y09HASVzE7uBGtIhPyo501t0qs6JecEEh7NPi2k.rq"], ["created_at", 2017-02-22 23:17:48 UTC], ["updated_at", 2017-02-22 23:17:48 UTC]]
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 176ms (ActiveRecord: 17.0ms)


  
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(al) already exists.
: INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"):
  
app/controllers/users_controller.rb:7:in `signup'
[active_model_serializers] Rendered UserSerializer with ActiveModelSerializers::Adapter::Json (2.8ms)
Completed 201 Created in 275ms (Views: 100.5ms | ActiveRecord: 77.4ms)


```

**Comment by raq929** [comment]
This is for sign-up, not sign-in. Which one are you having the problem for?

For this, you're getting an error because this user already exists, and emails must be unique.

**Comment by Soboscott** [comment]
I am using random user name and email and getting : 

```

app/controllers/users_controller.rb:7:in `signup'
Started POST "/sign-up" for 127.0.0.1 at 2017-02-22 18:53:37 -0500
Started POST "/sign-up" for 127.0.0.1 at 2017-02-22 18:53:37 -0500
Processing by UsersController#signup as */*
Processing by UsersController#signup as */*
  Parameters: {"credentials"=>{"email"=>"wa", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
  Parameters: {"credentials"=>{"email"=>"wa", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
   (62.7ms)  BEGIN
   (2.4ms)  BEGIN
  User Exists (1.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "wa"], ["LIMIT", 1]]
  User Exists (2.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "wa"], ["LIMIT", 1]]
  SQL (1.6ms)  INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "wa"], ["token", "53745c6c8e48b53c053caf3b3c3620f0"], ["password_digest", "$2a$10$En/Started POST "/sign-up" for 127.0.0.1 at 2017-02-22 19:04:43 -0500
Processing by UsersController#signup as */*
  Parameters: {"credentials"=>{"email"=>"def", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
Started POST "/sign-up" for 127.0.0.1 at 2017-02-22 19:04:44 -0500
Processing by UsersController#signup as */*
   (1.2ms)  BEGIN
  Parameters: {"credentials"=>{"email"=>"def", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
  User Exists (69.9ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "def"], ["LIMIT", 1]]
   (1.1ms)  BEGIN
  SQL (1.1ms)  INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "def"], ["token", "d623775df545c448e7d5fd45b8ee7a6c"], ["password_digest", "$2a$10$vUJUOQaGPAzNOoZcgxNL8OLIDPZOFx0H69kliJlgV/BlpoD5E6eMm"], ["created_at", 2017-02-23 00:04:44 UTC], ["updated_at", 2017-02-23 00:04:44 UTC]]
  User Exists (2.0ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "def"], ["LIMIT", 1]]
   (1.8ms)  COMMIT
  SQL (1.2ms)  INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["email", "def"], ["token", "38ff9ab9b76dc84afcef339c86ec4e1e"], ["password_digest", "$2a$10$.tGYUyXNaWA4Alxy5Mcw7uDkXFSPEfAcdkugVOM963DZpNZhmjd0y"], ["created_at", 2017-02-23 00:04:44 UTC], ["updated_at", 2017-02-23 00:04:44 UTC]]
  User Exists (0.8ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = $1 AND ("users"."id" != $2) LIMIT $3  [["email", "def"], ["id", 5], ["LIMIT", 1]]
[active_model_serializers] Rendered UserSerializer with ActiveModelSerializers::Adapter::Json (0.2ms)
Completed 201 Created in 148ms (Views: 0.7ms | ActiveRecord: 74.7ms)


   (1.5ms)  ROLLBACK
Completed 500 Internal Server Error in 78ms (ActiveRecord: 5.8ms)


  
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(def) already exists.
: INSERT INTO "users" ("email", "token", "password_digest", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"):
  
app/controllers/users_controller.rb:7:in `signup'

```

**Comment by raq929** [comment]
Can you sign up via curl request?

**Comment by Soboscott** [comment]
yes, I can:
```
rails-api-template_development=# SELECT * FROM users;
 id | email |              token               |                       password_digest                        |         created_at         |         updated_at         
----+-------+----------------------------------+--------------------------------------------------------------+----------------------------+----------------------------
  1 | al    | 43e14da371823b312dce7bc2da741016 | $2a$10$HdDsZfr8tZWO4U5DIxGNG.7ee1XVsryvXQTJJFefPtJstm1aVy.ai | 2017-02-22 23:17:48.789843 | 2017-02-22 23:17:48.789843
  3 | wa    | 53745c6c8e48b53c053caf3b3c3620f0 | $2a$10$En/GSJvGFmZt6DK.ePTrauSRawa.EV2ZNY2yBtMXOTi3lgDnzA/w6 | 2017-02-22 23:53:37.619544 | 2017-02-22 23:53:37.619544
  5 | def   | d623775df545c448e7d5fd45b8ee7a6c | $2a$10$vUJUOQaGPAzNOoZcgxNL8OLIDPZOFx0H69kliJlgV/BlpoD5E6eMm | 2017-02-23 00:04:44.130681 | 2017-02-23 00:04:44.130681
(3 rows)

rails-api-template_development=# \q
~/wdi/projects/trail-rater (inprogress)
$ EMAIL="new" PASSWORD="hi" sh scripts/sign-up.sh
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"2d8ab0b07fd27f700991e784782871de"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 9eb58f49-eb90-466b-8b39-1b5faf34911f
X-Runtime: 0.150421
Vary: Origin
Transfer-Encoding: chunked

{"user":{"id":7,"email":"new"}}
~/wdi/projects/trail-rater (inprogress)
$ 

```

**Comment by raq929** [comment]
Are you still at GA? If yes come see me. If no, can I see your server log from the successful curl request?

**Comment by Soboscott** [comment]
copy pasta

**Comment by jrhorn424** [comment]
The application and vendor bundles were being included twice. :+1:
