### ISSUE TITLE
HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#714]
I am getting a NoMethod error when I try to create a review through a curl request.
my command line is:
```
$ COMMENT="too long" TRAIL_ID=2 TOKEN="BAhJIiVhOTE1NTY5ZjhiMWVkMGUxMTFkOWM5ZGI1ODNjNzIwZQY6BkVG--d927e4cfc08c86825eab727d6f47a3486ff99515" sh scripts/reviews/create.sh 

```
the server is showing : 

```


  
NoMethodError (undefined method `review' for #<User:0x007fd5165db540>):
  
app/controllers/reviews_controller.rb:14:in `create'
Started POST "/reviews" for 127.0.0.1 at 2017-03-02 15:21:23 -0500
Processing by ReviewsController#create as */*
  Parameters: {"review"=>{"comments"=>"too long", "trail_id"=>"2"}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "a915569f8b1ed0e111d9c9db583c720e"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 18ms (ActiveRecord: 0.4ms)


  
NoMethodError (undefined method `review' for #<User:0x007fd517038a38>):
  
app/controllers/reviews_controller.rb:14:in `create'

```

my code for reviews_controller is:

```

# frozen_string_literal: true
class ReviewsController < OpenReadController
  before_action :set_review, only: [:destroy]

  # GET /reviews
  def index
    @reviews = Review.all

    render json: @reviews
  end

  # POST /reviews
  def create
    @reviews = current_user.review.build(review_params)

    if @review.save
      render json: @review, status: :created, location: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
  # DELETE /reviews/1

  def destroy
    @review.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:comments, :trail_id)
  end
end

```
the server is pointing to line 14

```
  def create
    @reviews = current_user.review.build(review_params)

    if @review.save
      render json: @review, status: :created, location: @review
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
```
I compared it with the bdd repo we did in class and that one did not have the location: symbol.
I tried it with and without the location: with the same error.

**Comment by bernardlee** [comment]
What does the `User` model look like?

**Comment by Soboscott** [comment]
reviews:

```
# frozen_string_literal: true
class Review < ApplicationRecord
end
```
Trails:
```

# frozen_string_literal: true
class Trail < ApplicationRecord
  has_many :reviews
end

```
and users:

```
class User < ApplicationRecord
  include Authentication
  has_many :trails, through: :reviews
end
```
I didn't think to look here. should I change the reviews model to:

```
class Review < ApplicationRecord
  has_many :users
  has_many :trails
end
```

**Comment by Soboscott** [comment]
I tried changing the model and am getting this 500 error:

```Started POST "/reviews" for 127.0.0.1 at 2017-03-02 19:52:43 -0500
  
TypeError (no implicit conversion of Symbol into Integer):
  
config/routes.rb:4:in `[]'
config/routes.rb:4:in `block in <top (required)>'
config/routes.rb:2:in `<top (required)>'
```

**Comment by Soboscott** [comment]
my routes looks like:

```Rails.application.routes.draw do
  resources :reviews, except: [:new, :edit]
  resources :trails [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```

**Comment by Soboscott** [comment]
I made changes to add except: to my model:

```Rails.application.routes.draw do
  resources :reviews, except: [:new, :edit]
  resources :trails, except: [:new, :edit]
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
end
```
but still get this error:


```

Started POST "/reviews" for 127.0.0.1 at 2017-03-02 19:56:01 -0500
Processing by ReviewsController#create as */*
  Parameters: {"review"=>{"comments"=>"too long", "trail_id"=>"2"}}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "a915569f8b1ed0e111d9c9db583c720e"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 49ms (ActiveRecord: 12.7ms)


  
NoMethodError (undefined method `reviews' for #<User:0x007fd5162628a0>):
  
app/controllers/reviews_controller.rb:14:in `create'


```

**Comment by bernardlee** [comment]
`User` is missing an association and `Review`'s associations are incorrect.

**Comment by Soboscott** [comment]
I was looking at the BDD repo and rubyonrails.org and I think the associations should be:
user:
```
class User < ApplicationRecord
  include Authentication
  has_many :reviews
  has_many :trails, through: :reviews
end
```


and reviews : 

```
class Review < ApplicationRecord
  belongs_to :user
  validates :trails, :user, presence: true
end

```
am I on the right track?

**Comment by bernardlee** [comment]
The `User` model looks correct, but `Review` is missing an association and the validation is incorrect.  Check the documentation for [Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html) on [Ruby on Rails Guides](http://guides.rubyonrails.org).

**Comment by Soboscott** [comment]
I made the changes above, and am getting the following error:
Rails server:
```^[[AStarted POST "/reviews" for 127.0.0.1 at 2017-03-03 15:46:36 -0500
Processing by ReviewsController#create as */*
  Parameters: {"review"=>{"comments"=>"YES", "trail_id"=>"2"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "f21ab41597d4b005fa7b076e89a0f0e9"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 37ms (ActiveRecord: 7.0ms)


  
NoMethodError (undefined method `save' for nil:NilClass):
  
app/controllers/reviews_controller.rb:16:in `create'
```

my reviews controller:
```

# frozen_string_literal: true
class ReviewsController < OpenReadController
  before_action :set_review, only: [:destroy]

  # GET /reviews
  def index
    @reviews = Review.all

    render json: @reviews
  end

  # POST /reviews
  def create
    @reviews = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
  # DELETE /reviews/1

  def destroy
    @review.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def review_params
    params.require(:review).permit(:comments, :trail_id)
  end
end
```
I checked this against the bdd repo and can't find the difference.
here is the bdd examples controller:

```# frozen_string_literal: true
class ExamplesController < OpenReadController
  before_action :set_example, only: [:update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all

    render json: @examples
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    render json: Example.find(params[:id])
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = current_user.examples.build(example_params)

    if @example.save
      render json: @example, status: :created
    else
      render json: @example.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    if @example.update(example_params)
      head :no_content
    else
      render json: @example.errors, status: :unprocessable_entity
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy

    head :no_content
  end

  def set_example
    @example = current_user.examples.find(params[:id])
  end

  def example_params
    params.require(:example).permit(:text)
  end

  private :set_example, :example_params
end

```

**Comment by Soboscott** [comment]
got it 
```
class ReviewSerializer < ActiveModel::Serializer
  attributes :id, :comments, :user_id
  # user :user_id
end
```
