### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#718]
I'm getting a 400 error when I try to create a review.
here is the server message:

```

Started POST "/sign-in" for 127.0.0.1 at 2017-03-05 09:31:31 -0500
Processing by UsersController#signin as */*
  Parameters: {"credentials"=>{"email"=>"sa@sa.com", "password"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "sa@sa.com"], ["LIMIT", 1]]
  SQL (6.5ms)  UPDATE "users" SET "token" = '155ff37c62586cfbc2ab82b1ca91b010', "updated_at" = '2017-03-05 14:31:31.787389' WHERE "users"."id" = $1  [["id", 21]]
[active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (0.18ms)
Completed 200 OK in 75ms (Views: 0.6ms | ActiveRecord: 6.8ms)


Started POST "/reviews" for 127.0.0.1 at 2017-03-05 09:31:55 -0500
Processing by ReviewsController#create as */*
  Parameters: {"post"=>{"animal_type"=>"w", "date_seen"=>"2017-12-31", "location"=>"q", "comment"=>"z"}, "submit"=>"Create Entry"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "155ff37c62586cfbc2ab82b1ca91b010"], ["LIMIT", 1]]
Completed 400 Bad Request in 20ms (ActiveRecord: 2.8ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: review):
  
app/controllers/reviews_controller.rb:37:in `review_params'
app/controllers/reviews_controller.rb:14:in `create'
Started POST "/sign-in" for 127.0.0.1 at 2017-03-04 20:46:26 -0500
Processing by UsersController#signin as */*
  Parameters: {"credentials"=>{"email"=>"aw@aw.com", "password"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "aw@aw.com"], ["LIMIT", 1]]
  SQL (6.4ms)  UPDATE "users" SET "token" = 'c51cc0019f0f69e32a35cdd1dde1d50c', "updated_at" = '2017-03-05 01:46:26.255261' WHERE "users"."id" = $1  [["id", 19]]
[active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (0.25ms)
Completed 200 OK in 73ms (Views: 0.6ms | ActiveRecord: 6.7ms)


Started POST "/posts" for 127.0.0.1 at 2017-03-04 20:46:54 -0500
  


```

the inspector is pointing to an error in line 17 of both api.js and event.js
My code in reviews/api.js is :

```javascript

'use strict';

const config = require('../config');
const store = require('../store');

const getIndex = function () {
  return $.ajax({
    url: config.apiOrigin + '/reviews',
    method: 'GET',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

const create = function (data) {
  return $.ajax({
    url: config.apiOrigin + '/reviews',
    method: 'POST',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};

const update = function (id, data) {
  return $.ajax({
    url: config.apiOrigin + '/reviews/' + id,
    method: 'PATCH',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
    data,
  });
};

const destroy = function (id) {
  return $.ajax({
    url: config.apiOrigin + '/reviews/' + id,
    method: 'DELETE',
    headers: {
      Authorization: `Token token=${store.user.token}`,
    },
  });
};

module.exports = {
  getIndex,
  create,
  update,
  destroy,
};

```

and my code in reviews/event.js is : 

```javascript

'use strict';

const logApi = require('./api');
const logUi = require('./ui');
const getFormFields = require('../../../lib/get-form-fields');

const onIndex = function (event) {
  event.preventDefault();
  logApi.getIndex()
    .then(logUi.indexSuccess)
    .catch(logUi.failure);
};

const onCreate = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  logApi.create(data)
    .then(logUi.createSuccess)
    .then(logApi.getIndex)
    .then(logUi.indexSuccess)
    .catch(logUi.createEntryFailure);
};

const onUpdate = function (event) {
  event.preventDefault();
  let data = getFormFields(event.target);
  let id = data.post.id;
  logApi.update(id, data)
    .then(logUi.updateSuccess)
    .then(logApi.getIndex)
    .then(logUi.indexSuccess)
    .catch(logUi.updateEntryFailure);
};

const onRemovePost = (event) => {
  event.preventDefault();
  let id = event.target.getAttribute('data-id');
  logApi.destroy(id)
    .then(logUi.removePostSuccess)
    .then(logApi.getIndex)
    .then(logUi.indexSuccess)
    .catch(logUi.failure);
};

const unhideUpdate = () => {
  $('#update-entry').removeClass('hidden');
  $('#create-entry').addClass('hidden');
};

const hideUpdate = () => {
  $('#status-box').text('Update Cancelled');
  $('.create-entry-message').text('');
  $('.update-entry-message').text('');
  $('.update-field').val('');
  $('#update-entry').addClass('hidden');
  $('#create-entry').removeClass('hidden');
};

const addAjaxHandlers = () => {
  $('#get-index-button').on('click', onIndex);
  $('#create-entry').on('submit', onCreate);
  $('#entry-container').on('click', '#removePost', onRemovePost);
  $('#show-update-form').on('click', unhideUpdate);
  $('#update-entry').on('submit', onUpdate);
  $('#cancel-update').on('click', hideUpdate);
};

module.exports = {
  addAjaxHandlers,
  onIndex,
};


```
I looked at other issues created in this repo as well as several stackoverflow examples and was not able to find any kind of pattern match.
I'm not seeing where the code in those places is wrong.
My guess is that it is in another part of my app, I tried following the "path" of the POST but it all looks like it should work.  I might be looking at it and not seeing a typo or it is missing a piece of punctuation.  

I tried running a CURL request with the following command:

```
{"user":{"id":22,"email":"","token":"BAhJIiU5MWY2ZjNhOTJiZDIyODQ4ZWYyYzg1NWI3ZjFiN2ExZAY6BkVG--0f70f773d15f433c2e0860c96f49f212aa7a4c43"}}
~/wdi/projects/trail-rater (master)
$ TOKEN="BAhJIiU5MWY2ZjNhOTJiZDIyODQ4ZWYyYzg1NWI3ZjFiN2ExZAY6BkVG--0f70f773d15f433c2e0860c96f49f212aa7a4c43" COMMENT="nice" sh scripts/reviews/create.sh 
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Request-Id: c927aaac-dc47-4418-8987-99f1f54c7ce3
X-Runtime: 0.025758
Vary: Origin
Content-Length: 9726

```

My reviews controller is:

```ruby
# frozen_string_literal: true
class UsersController < ProtectedController
  skip_before_action :authenticate, only: [:signup, :signin]

  # POST '/sign-up'
  def signup
    user = User.create(user_creds)
    if user.valid?
      render json: user, status: :created
    else
      render json: user.errors, status: :bad_request
    end
  end

  # POST '/sign-in'
  def signin
    creds = user_creds
    if (user = User.authenticate creds[:email],
                                 creds[:password])
      render json: user, serializer: UserLoginSerializer, root: 'user'
    else
      head :unauthorized
    end
  end

  # DELETE '/sign-out/1'
  def signout
    if current_user == User.find(params[:id])
      current_user.logout
      head :no_content
    else
      head :unauthorized
    end
  end

  # PATCH '/change-password/:id'
  def changepw
    if !current_user.authenticate(pw_creds[:old]) ||
       (current_user.password = pw_creds[:new]).blank? ||
       !current_user.save
      head :bad_request
    else
      head :no_content
    end
  end

  def index
    render json: User.all
  end

  def show
    user = User.find(params[:id])
    render json: user
  end

  def update
    head :bad_request
  end

  private

  def user_creds
    params.require(:credentials)
          .permit(:email, :password, :password_confirmation)
  end

  def pw_creds
    params.require(:passwords)
          .permit(:old, :new)
  end

  private :user_creds, :pw_creds
end


```
I know it's long but I am just trying to be thorough.
thanks for helping.

**Comment by bernardlee** [comment]
> I'm getting a 400 error when I try to create a review.
> here is the server message:

I'm assuming that we're supposed to be looking at the second block since it has the response status of 400.
```
Started POST "/reviews" for 127.0.0.1 at 2017-03-05 09:31:55 -0500
Processing by ReviewsController#create as */*
  Parameters: {"post"=>{"animal_type"=>"w", "date_seen"=>"2017-12-31", "location"=>"q", "comment"=>"z"}, "submit"=>"Create Entry"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "155ff37c62586cfbc2ab82b1ca91b010"], ["LIMIT", 1]]
Completed 400 Bad Request in 20ms (ActiveRecord: 2.8ms)
```
Notice the "Parameters" there.

> the inspector is pointing to an error in line 17 of both api.js and event.js
> My code in reviews/api.js is :

I don't see anything wrong with those two files.

> I tried running a CURL request with the following command:

Why is the `email` key in the JSON response an empty string?  You might be getting this error because of 
your `ReviewsController`'s parameters as indicated above.

> My reviews controller is:

I think that you pasted the wrong file.

**Comment by Soboscott** [comment]
I got this error "fixed"... and on to the next.
thank you for helping.

**Comment by bernardlee** [comment]
What did you do to fix it?

**Comment by Soboscott** [comment]
I changed the review_params and took out the id requirements:

```
  def review_params
    params.require(:review).permit(:comment)

```
