### ISSUE TITLE
ActionController::ParameterMissing (param is missing or the value is empty: review):

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/full-stack-project#720]
I have been working on this for a few hours, I have tried to find out where the missing param or empty value is.  I have simplified the review to validate just a comment.
 this is the error message when I try to create a review:

```

Started POST "/sign-in" for 127.0.0.1 at 2017-03-05 19:16:32 -0500
Processing by UsersController#signin as */*
  Parameters: {"credentials"=>{"email"=>"me@me.com", "password"=>"[FILTERED]"}, "submit"=>"Let's Go!"}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "me@me.com"], ["LIMIT", 1]]
  SQL (0.5ms)  UPDATE "users" SET "token" = '5a2f300b2dd42082b02a754195b668fa', "updated_at" = '2017-03-06 00:16:32.385756' WHERE "users"."id" = $1  [["id", 23]]
[active_model_serializers] Rendered UserLoginSerializer with ActiveModelSerializers::Adapter::Json (0.24ms)
Completed 200 OK in 82ms (Views: 0.6ms | ActiveRecord: 2.7ms)


Started POST "/reviews" for 127.0.0.1 at 2017-03-05 19:16:43 -0500
Processing by ReviewsController#create as */*
  Parameters: {"post"=>{"trail_name"=>"hope", "date_seen"=>"2017-01-01", "comment"=>"pray"}, "submit"=>"Create Entry"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "5a2f300b2dd42082b02a754195b668fa"], ["LIMIT", 1]]
Completed 400 Bad Request in 6ms (ActiveRecord: 0.2ms)

  
ActionController::ParameterMissing (param is missing or the value is empty: review):
  
app/controllers/reviews_controller.rb:37:in `review_params'
app/controllers/reviews_controller.rb:14:in `create'


```

My reviews model is:

```ruby

# frozen_string_literal: true
class Review < ApplicationRecord
  belongs_to :user
  # validates :trail_name, presence: true
  # validates :date_seen, presence: true
  # validates :location, presence: true
  validates :comment, presence: true
end

```
I commented out everything but the :comment validation.

my reviews controller is:

```ruby

# frozen_string_literal: true
class ReviewsController < OpenReadController
  before_action :set_review, only: [:show, :index, :destroy]

  # GET /reviews
  def index
    @reviews = Review.all

    render json: @reviews
  end

  # POST /reviews
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end
  # DELETE /reviews/1

  def destroy
    @review.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  # Only allow a trusted parameter through.
  def review_params
    params.require(:review).permit(:comment)
  end
  # private :review_params
end

```
the error is pointing to lines 37 and 14 but I don't see where my code is wrong.
lines 12 to 21:

```ruby

  # POST /reviews
  def create
    @review = current_user.reviews.build(review_params)

    if @review.save
      render json: @review, status: :created
    else
      render json: @review.errors, status: :unprocessable_entity
    end
  end

```
and lines 36 to 38:

```ruby

def review_params
    params.require(:review).permit(:comment)
  end

```

**Comment by bernardlee** [comment]
```
Started POST "/reviews" for 127.0.0.1 at 2017-03-05 19:16:43 -0500
Processing by ReviewsController#create as */*
  Parameters: {"post"=>{"trail_name"=>"hope", "date_seen"=>"2017-01-01", "comment"=>"pray"}, "submit"=>"Create Entry"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "5a2f300b2dd42082b02a754195b668fa"], ["LIMIT", 1]]
Completed 400 Bad Request in 6ms (ActiveRecord: 0.2ms)
```
Compare the parameters that you're sending with your request with the parameters allowed by `ReviewsController#review_params`.

**Comment by Musomoka** [comment]
Hi just spent time a day dealing with this as well. 
Try  using "@review = current_user.reviews.build" in your index page, before you pass it params in your create action.

**Comment by nandocastro031069-eng** [comment]
+34 603 71 11 74

**Comment by nandocastro031069-eng** [comment]
+34 603 71 11 74
