### ISSUE TITLE
Error #500 on POST curl request

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/full-stack-project#736]
I am having a similar issue as #729. I tried to run the following curl request: 

```
curl --include --request POST http://localhost:4741/items \
  --header "Content-Type: application/json" \
  --data '{
    "item": {
      "food_name": "black beans",
      "purchase_date": "2017-04-27",
      "exp_date": "2017-06-01",
      "store_name": "Trader Joes",
      "quantity": true,
      "purchased": true
    }
  }'
```

I received the following error: 
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Request-Id: 32a0eb5d-c822-4425-bcaf-c528e4972f49
X-Runtime: 0.042772
Vary: Origin
Content-Length: 11478

{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `items' for nil:NilClass\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/controllers/items_controller.rb:21:in `create'"}],"Framework Trace":[{"id":1,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":2,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":3,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in 
```

Here is my item controller: 
```
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = current_user.items

    render json: @items
  end

  # GET /items/1
  # GET /items.json
  def show
    render json: @items
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    if @item.save
      render json: @item, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def set_item
    # @item = Item.find(params[:id])
    @item = current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:id)
  end
end
```

According to the error message, the issue is with this line: `@item = current_user.items.build(item_params)`. This code seems to be consistent with what was in issue #729. Therefore, I'm wondering whether I've incorrectly defined the `item_params` method? 

Thank you!

**Comment by scottyscripts** [comment]
Can you please post code from your routes.rb file?

**Comment by scottyscripts** [comment]
take a closer look at the exception part of the response

**Comment by naributler** [comment]
Here's my routes.rb file: 

```
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :examples, except: [:new, :edit]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  resources :users, only: [:index, :show]
  resources :items, except: [:new, :edit]
end
```

**Comment by naributler** [comment]
@aeabbott helped me solve this issue! I needed to inherit the `ItemsController` from `ProtectedController`. When I run the curl request, I now get a different error (401 unauthorized). I think this is because my token expired, so I'll work on updating that now.
