### ISSUE TITLE
Error 400 - ParameterMissing 

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/full-stack-project#750]
This seems like the same issue as #737 (and many others in the issue cue). I've read through these threads, but I'm still struggling to find my error. 

My curl request returned as 201 Created: 

```
  API="${API_ORIGIN:-http://localhost:4741}"
  URL_PATH="/items"
  curl "${API}${URL_PATH}" \
   --include \
   --request POST \
   --header "Content-Type: application/json" \
   --header "Authorization: Token token=$TOKEN" \
   --data '{
     "item": {
       "food_name": "carrots",
       "purchase_date": "2017-04-27",
       "exp_date": "2017-06-01",
       "store_name": "Trader Joes",
       "quantity": "true",
       "purchased": "true"
     }
   }'
```

Response: 
```
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Location: http://localhost:4741/items/20
Content-Type: application/json; charset=utf-8
ETag: W/"59d6f525d6643846b9e97d346b329af5"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 6e9828dd-6190-4733-be17-7c344c8bb774
X-Runtime: 0.025515
Vary: Origin
Transfer-Encoding: chunked

{"item":{"id":20,"food_name":"carrots","purchase_date":"2017-04-27","exp_date":"2017-06-01","store_name":"Trader Joes","quantity":true,"purchased":true}}
```

Then, I created an "add-item" form in index.html: 

```
      <!-- Add Item -->
      <form id="add-item" class="pure-form pure-form-aligned">
        <fieldset>
          <div class="pure-control-group">
            <label for="name">food name</label>
            <input id="food-item" type="text" placeholder="item name" name="item[food_name]">
            <span class="pure-form-message-inline">This is a required field.</span>
          </div>

          <div class="pure-control-group">
            <label for="purchase-date">purchase date</label>
            <input id="purchase-date" type="date" placeholder="puchase date" name="item[purchase_date]">
            <span class="pure-form-message-inline">This is a required field.</span>
          </div>

          <div class="pure-control-group">
            <label for="exp-date">expiration date</label>
            <input id="exp-date" type="date" placeholder="exp date" name="item[exp_date]">
            <span class="pure-form-message-inline">This is a required field.</span>
          </div>

          <div class="pure-control-group">
            <label for="store">store name</label>
            <input id="store-name" type="text" placeholder="store name" name="item[store_name]">
          </div>

          <div class="pure-control-group">
            <label for="store">quantity</label>
            <input id="quantity" type="boolean" placeholder="quantity" name="item[quantity]" value="true">
          </div>

          <div class="pure-control-group">
            <label for="store">purchased</label>
            <input id="purchased" type="boolean" placeholder="purchased" name="item[purchased]" value="true">
          </div>

          <div class="pure-controls">
            <input type="submit" name="submit" value="Add" class="pure-button pure-button-primary">
          </div>
        </fieldset>
      </form>
```

Then, I wrote the AJAX call: 

```
const addNewItem = function (event) {
  event.preventDefault()
  const data = getFormFields(event.target)
  api.addNewItem(data)
    .done(ui.addNewItemSuccess)
    .fail(ui.addNewItemFail)
  console.log('addNewItem ran!')
}

const addNewItem = function (data) {
  console.log(data)
  return $.ajax({
    url: config.apiOrigin + '/items',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    }
  })
}

const addNewItemSuccess = (data) => {
  console.log('addNewItemSuccess worked!')
  store.item = data.item
}

const addNewItemFail = (error) => {
  console.error(error)
  console.log('addNewItem failed!')
}
```
Here's the error I'm seeing when I test out this code: 
<img width="731" alt="screen shot 2017-04-28 at 8 34 08 am" src="https://cloud.githubusercontent.com/assets/20606223/25528823/860f4a78-2bed-11e7-977a-98bd9b56b343.png">

It looks like an object is being created that contains the fields I want, but there is an issue updating the back-end. Here are more details about the error: 
```
Completed 400 Bad Request in 16ms (ActiveRecord: 8.9ms)

ActionController::ParameterMissing (param is missing or the value is empty: item):

app/controllers/items_controller.rb:52:in `item_params'
app/controllers/items_controller.rb:21:in `create'
```

Here's the affected code in my item controller: 
```
  def item_params
    params.require(:item).permit(:exp_date, :food_name, :purchase_date, :purchased, :quantity, :store_name)
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      render json: @item, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end
```

I believe I'm permitting all of the necessary fields. Any help would be appreciated. Thank you!

**Comment by naributler** [comment]
Thank you, @rrdaniels85, for helping me debug this issue!! 

I forgot to pass `data` into the AJAX call, so data was not being returned. Once I amended the AJAX call, it worked!
