### ISSUE TITLE
Filter Index Results

### ISSUE THREAD

**Issue by naributler** [ga-wdi-boston/full-stack-project#754]
I'm trying to filter my index so that I can return two difference slices of data (a list of food I currently have, a list of items that are on my grocery list). 

Here's the code for generating a list of food items I have: 

items_controller: 
```
  def index
    @items = current_user.items
    @foods = @items.filter

    # Only return the items that exist/have not been consumed
    render json:
      if (quantity = params[:quantity])
        @items.where(quantity: true)
      # elsif (quantity = params[:quantity])
      #   @items.where(quantity: false)
      end
  end
```
curl request: 
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/items?quantity=true"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"
```
response: 
```
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"d60ae4419299dfec734b6a42edab8c86"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: f3e2eddb-cfa9-4053-9bdb-c2b58864581e
X-Runtime: 0.051923
Vary: Origin
Transfer-Encoding: chunked

{"items":[{"id":20,"food_name":"carrots","purchase_date":"2017-04-27","exp_date":"2017-06-01","store_name":"Trader Joes","quantity":true,"purchased":true},{"id":21,"food_name":"potatoes","purchase_date":"2017-04-28","exp_date":"2017-05-28","store_name":"Trader Joes","quantity":true,"purchased":true},{"id":22,"food_name":"pineapple","purchase_date":"2017-04-28","exp_date":"2017-05-28","store_name":"Trader Joes","quantity":true,"purchased":true}]}
``` 

This is the correct response - I am able to retrieve only the rows that have a quantity of "true".

Now, I'm trying to do the opposite and retrieve only the rows where quantity has a value of "false". Here's my code: 

items_controller: 
```
  def index
    @items = current_user.items

    # Only return the items that exist/have not been consumed
    render json:
      if (quantity = params[:quantity])
        @items.where(quantity: true)
      elsif (quantity = params[:quantity])
        @items.where(quantity: false)
      end
  end
```
curl request: 
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/items?quantity=false"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"
```
curl response:
```
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"d60ae4419299dfec734b6a42edab8c86"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 69d66524-9b8b-4498-a672-92e9f6e52bf9
X-Runtime: 0.022869
Vary: Origin
Transfer-Encoding: chunked

{"items":[{"id":20,"food_name":"carrots","purchase_date":"2017-04-27","exp_date":"2017-06-01","store_name":"Trader Joes","quantity":true,"purchased":true},{"id":21,"food_name":"potatoes","purchase_date":"2017-04-28","exp_date":"2017-05-28","store_name":"Trader Joes","quantity":true,"purchased":true},{"id":22,"food_name":"pineapple","purchase_date":"2017-04-28","exp_date":"2017-05-28","store_name":"Trader Joes","quantity":true,"purchased":true}]}
```

The response is exactly the same as the previous curl request. I'm still filtering on rows that have a quantity of "true". I'm lost on how to set up the items controller so that I can make multiple `GET` requests from the same index function for different slices of the data.

**Comment by naributler** [comment]
Updating - 

Here's an article that seems to address the issue: https://codereview.stackexchange.com/questions/62856/rails-controller-method-that-conditionally-filters-results

Should I use `scope` to define the target slice of data and then index based on that scope?

**Comment by scottyscripts** [comment]
Be aware of what you actually checking in your conditional statement. Are they currently the same thing? Generally, instead of setting the parameter to true or false, we could either send or not send `quantity` as a param. This way if it exists, we know it's true. If we don't send that param, we know it's false.

**Comment by naributler** [comment]
I just tried this: 
```
  def index
    @items = current_user.items

    render json:
      # Only return the items that exist/have not been consumed
      if (quantity = params[:quantity])
        @items.where(quantity: true)
      # Return items that have been consume, need to be purchased
      else
        @items.where(quantity: false)
      end
  end
```
However, it returns the same result as before. Is this what you meant by sending/not sending `quantity` as a param?

**Comment by payne-chris-r** [comment]
This scares me:
```ruby
if (thingOne = thingTwo)
```

**Comment by naributler** [comment]
Better?
```
  def index
    @items = current_user.items

    render json:
      # Only return items that exist/have not been consumed
      if params[:quantity]
        @items.where(quantity: true)
      # Return items that have been consumed, need to be purchased
      else
        @items.where(quantity: false)
      end
  end
```

**Comment by payne-chris-r** [comment]
Better.

**Comment by payne-chris-r** [comment]
Are you passing in :quantity with your request?

**Comment by naributler** [comment]
I think so? Here's the curl: 
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/items?quantity=false"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"
```
Here's my entire items controller: 
```
class ItemsController < ProtectedController
  before_action :set_item, only: [:show, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = current_user.items

    render json:
      # Only return the items that exist/have not been consumed
      if params[:quantity]
        @items.where(quantity: true)
      # Return items that have been consume, need to be purchased
      else
        @items.where(quantity: false)
      end
  end

  # GET /items/1
  # GET /items.json
  def show
    render json: @items
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)

    if @item.save
      render json: @item, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def update
    # @item = current_user.find(params[:id])

    if @item.update(item_params)
      head :no_content
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy

    head :no_content
  end

  def set_item
    # @item = Item.find(params[:id])
    @item = current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:exp_date, :food_name, :purchase_date, :purchased, :quantity, :store_name)
  end
end
```
I think I'm passing in :quantity, thought that's going in through the `item_params` method. Should I use `item_params` instead of `params`?

**Comment by payne-chris-r** [comment]
It's up to you. Does it work? If it works, the way you're doing it is fine.

**Comment by naributler** [comment]
No, it doesn't work. I tried this: 
```
  def index
    @items = current_user.items

    render json:
      # Only return the items that exist/have not been consumed
      if item_params[:quantity]
        @items.where(quantity: true)
      # Return items that have been consume, need to be purchased
      else
        @items.where(quantity: false)
      end
  end
```
It throws a 400 error when I run the curl request: 
```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Request-Id: 939ed70f-9679-4c99-af26-b54ee227b5f3
X-Runtime: 0.065166
Vary: Origin
Content-Length: 11852

{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: item\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/items_controller.rb:59:in `item_params'"},{"id":2,"trace":"app/controllers/items_controller.rb:11:in `index'"}],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_controller/metal/strong_parameters.rb:310:in `require'"},{"id":3,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":6,"trace":"actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'"},{"id":7,"trace":"activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'"},{
```

**Comment by naributler** [comment]
Could I have a 1on1 with someone this afternoon and review a couple of Rails concepts? I don't really understand how to slice data by certain parameters in the controller. I've been copying in code from the game-project-api without really understanding what it is doing.

Unrelated to this issue, but I'm also unclear about how to modify an existing table and add a calculated column. It would be great to review this with someone in a 1on1 before attempting a migration.

**Comment by payne-chris-r** [comment]
Please open an issue for both. I can help you with one, the other or both, but please write down what you would like the migration to accomplish and why in a separate issue. 

I'm glad you had the insight to ask "why" about your copied code. It's a really good sign.

**Comment by payne-chris-r** [comment]
As far as this issue is concerned, can you post the curl request that is giving you that 400 error please?

**Comment by naributler** [comment]
Thanks, Chris! I'll open another issue to address my migration questions. 

Here's the curl request that is giving a 400 error: 
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/items?quantity=true"
curl "${API}${URL_PATH}" \
  --include \
  --request GET \
  --header "Authorization: Token token=$TOKEN"
```
Here's the response: 
```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Request-Id: 99a571e1-d5d8-4a8b-9304-b1444b6a12ec
X-Runtime: 0.039385
Vary: Origin
Content-Length: 11852

{"status":400,"error":"Bad Request","exception":"#\u003cActionController::ParameterMissing: param is missing or the value is empty: item\u003e","traces":{"Application Trace":[{"id":1,"trace":"app/controllers/items_controller.rb:59:in `item_params'"},{"id":2,"trace":"app/controllers/items_controller.rb:11:in `index'"}],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_controller/metal/strong_parameters.rb:310:in `require'"},{"id":3,"trace":"actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'"},{"id":4,"trace":"actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'"},{"id":5,"trace":"actionpack (5.0.1) lib/action_controller/met
```
Here's the items controller: 
```
  def index
    @items = current_user.items

    render json:
      # Only return the items that exist/have not been consumed
      if item_params[:quantity]
        @items.where(quantity: true)
      # Return items that have been consume, need to be purchased
      else
        @items.where(quantity: false)
      end
  end
```

**Comment by scottyscripts** [comment]
make sure that the parameter you require in `def item_params` in your items_controller is being passed during your request!

**Comment by naributler** [comment]
Thank you so much, @payne-chris-r!! 

I made several mistakes here - `if params[:quantity]` checks whether the value passed in is truthy or falsey. Since I'm passing in a string, the if statement always evaluated as truthy and executed the code that filters on rows where quantity is true. Therefore, I needed to modify the if statement. Here's the final code: 
```
  def index
    @items = current_user.items
    puts params[:quantity]
    puts params[:quantity].class

    render json:
      # Only return the items that exist/have not been consumed
      if (params[:quantity] == 'true')
        @items.where(quantity: true)
      # Return items that have been consume, need to be purchased
      else
        @items.where(quantity: false)
      end
  end
```
The if statement evaluates whether params[:quantity] is equal to the string "true". If the value is "true", only rows where the value of quantity is true will show. If the value is not "true", only rows where the value of quantity is false will show. Next steps are to make the conversion from boolean to string value more explicit/semantic.
