### ISSUE TITLE
POST request failing - 500 error

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/full-stack-project#771]
When testing a POST request to create a new item in the items table, getting a 500 error:
```
Started POST "/items" for 127.0.0.1 at 2017-04-28 15:56:17 -0400
Processing by ItemsController#create as */*
  Parameters: {"item"=>{"item_name"=>"Doritos", "purchase_date"=>"2017-04-28", "expiry_date"=>"2017-07-02", "price"=>"0.99", "category"=>"Junk Food", "perishable"=>"yes", "shelf_life"=>"", "pantry_id"=>"10", "quantity"=>"42", "item_size"=>"3.5", "item_unit"=>"oz"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "8de856a135b6ef5228a4ff14e3cd3e0e"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.3ms)

NoMethodError (undefined method `items' for #<User:0x007fb2ea3a3d20>):
  
app/controllers/items_controller.rb:20:in `create'
```

curl script:
```sh
#!/bin/bash

API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/items"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "item": {
      "item_name": "'"${NAME}"'",
      "purchase_date": "'"${PDATE}"'",
      "expiry_date": "'"${EDATE}"'",
      "price": "'"${PRICE}"'",
      "category": "'"${CAT}"'",
      "perishable": "'"${PERISH}"'",
      "shelf_life": "'"${LIFE}"'",
      "pantry_id": "'"${PID}"'",
      "quantity": "'"${QTY}"'",
      "item_size": "'"${SIZE}"'",
      "item_unit": "'"${UNIT}"'"
    }
  }'
```

After getting a user session token, executing the curl script with:
```
TOKEN=BAhJIiU4ZGU4NTZhMTM1YjZlZjUyMjhhNGZmMTRlM2NkM2UwZQY6BkVG--6a880e55e79ff58ee060ffada2f055cf4648e7c6 \
NAME='Doritos' \
PDATE='2017-04-28' \
EDATE='2017-07-02' \
PRICE=0.99 \
CAT='Junk Food' \
PERISH=yes \
LIFE='' \
PID=11 \
QTY=42 \
SIZE=3.5 \
UNIT=oz \
sh scripts/item/create-item.sh
```

items_controller.rb file:
```ruby
class ItemsController < OpenReadController
  before_action :set_item, only: [:show, :update, :destroy]
...
  def create
    @item = current_user.items.build(item_params)

    if @item.save
      render json: @item, status: :created, location: @item
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end
...
    def set_item
      @item = current_user.items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:item_name, :purchase_date, :expiry_date, :price, :category, :perishable, :shelf_life, :pantry_id, :quantity, :item_size, :item_unit)
    end
```

I'm not clear why User is looking for an 'items' method per the error message.

Current relationships are:
1 User to Many Pantries
1 Pantry to Many Items

Models are defined as:
user.rb
```ruby
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :pantries
end
```

pantry.rb
```ruby
class Pantry < ApplicationRecord
  belongs_to :pantry_user, class_name: 'User', foreign_key: 'user_id'
  has_many :pantry_items, class_name: 'Item'
end
```

item.rb
```ruby
class Item < ApplicationRecord
  belongs_to :main_pantry, class_name: 'Pantry', foreign_key: 'pantry_id'
end
```

**Comment by payne-chris-r** [comment]
RE: "I'm not clear why User is looking for an 'items' method per the error message." 
It's looking for items because of this line:
```ruby
@item = current_user.items.build(item_params)
```

**Comment by ghost** [comment]
Sorry - I should rephrase the question because asking the correct question is critical!
I'm not sure why the items method is undefined for User.

The item create method is set up like the pantry create method, but the pantry create method is working just fine:
```ruby
def create
    @pantry = current_user.pantries.build(pantry_params)

    if @pantry.save
      render json: @pantry, status: :created, location: @pantry
    else
      render json: @pantry.errors, status: :unprocessable_entity
    end
end
```
Chris, thanks for your response. Typing this out got me thinking:
The only difference is the items relationship (AFAIK) since 
     -user has many pantries
     -pantry has many items
     -user does not directly have any items
     -items is associated to a user through a pantry via user_id

I will see if adding user_id to the items table will resolve this issue and report back on the results.

**Comment by payne-chris-r** [comment]
You don't want to add user_id to the items table

**Comment by payne-chris-r** [comment]
You want to go through the relationship

**Comment by payne-chris-r** [comment]
What DOES a user have?

**Comment by ghost** [comment]
User has all the default columns from the template - haven't made any changes to it. I'll revert the items table changes and take another look at the relationship, thanks!

**Comment by ghost** [comment]
from schema.rb:

```ruby

  create_table "items", force: :cascade do |t|
    t.text     "item_name"
    t.date     "purchase_date"
    t.date     "expiry_date"
    t.decimal  "price",         precision: 8, scale: 2
    t.text     "category"
    t.text     "perishable"
    t.integer  "shelf_life"
    t.integer  "pantry_id"
    t.integer  "quantity"
    t.integer  "item_size"
    t.text     "item_unit"
    t.datetime "created_at",                            null: false
    t.datetime "updated_at",                            null: false
    t.index ["pantry_id"], name: "index_items_on_pantry_id", using: :btree
  end

  create_table "pantries", force: :cascade do |t|
    t.text     "pantry_name"
    t.integer  "user_id"
    t.datetime "created_at",  null: false
    t.datetime "updated_at",  null: false
    t.text     "permission"
    t.index ["user_id"], name: "index_pantries_on_user_id", using: :btree
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["token"], name: "index_users_on_token", unique: true, using: :btree
  end

  add_foreign_key "examples", "users"
  add_foreign_key "items", "pantries"
  add_foreign_key "pantries", "users"
end
```

**Comment by payne-chris-r** [comment]
So user.pantries is a thing
And user.items isn't. 
If a user has_many pantries
And a pantry has_many items
What CAN I call `.items` on??

**Comment by ghost** [comment]
ahhh, so only a pantry can call `.items`.
So I'll need to define a relationship between user and items.

**Comment by ghost** [comment]
Made an update to user.rb:
```ruby
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :pantries
  has_many :items, through: :pantries
end
```

Now getting a new error so there's progress!
```
Started POST "/items" for 127.0.0.1 at 2017-04-28 21:19:23 -0400
Processing by ItemsController#create as */*
  Parameters: {"item"=>{"item_name"=>"Doritos", "purchase_date"=>"2017-04-28", "expiry_date"=>"2017-07-02", "price"=>"0.99", "category"=>"Junk Food", "perishable"=>"yes", "shelf_life"=>"", "pantry_id"=>"11", "quantity"=>"42", "item_size"=>"3.5", "item_unit"=>"oz"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "c00487eb9c12d714d9b7ed86ed08d378"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.3ms)


  
ActiveRecord::HasManyThroughSourceAssociationNotFoundError (Could not find the source association(s) "item" or :items in model Pantry. Try 'has_many :items, :through => :pantries, :source => <name>'. Is it one of pantry_user or pantry_items?):
  
app/controllers/items_controller.rb:20:in `create'
```

**Comment by ghost** [comment]
Updated item.rb:
```ruby
class Item < ApplicationRecord
  belongs_to :main_pantry, class_name: 'Pantry', foreign_key: 'pantry_id'
  has_one :user, through: :pantries
end
```
Getting the same error, will keep looking into the relationships.

**Comment by ghost** [comment]
Issue is now resolved. Fixed the relationship in the pantry model per the error message. So now my models look like - 
user.rb:
```ruby
class User < ApplicationRecord
  include Authentication
  has_many :examples
  has_many :pantries
  has_many :items, through: :pantries
end
```
pantry.rb:
```ruby
class Pantry < ApplicationRecord
  belongs_to :pantry_user, class_name: 'User', foreign_key: 'user_id'
  has_many :items
end
```
item.rb:
```ruby
class Item < ApplicationRecord
  belongs_to :main_pantry, class_name: 'Pantry', foreign_key: 'pantry_id'
  has_one :user, through: :pantries
end
```

Thanks!

**Comment by payne-chris-r** [comment]
This isn't right.
```
payne-chris-r commented 4 hours ago
You don't want to add user_id to the items table
```

**Comment by payne-chris-r** [comment]
```ruby
current_user.pantries.find().items
```

**Comment by ghost** [comment]
Does this mean that I should be adding user_id into the items table?
> This isn't right.
> 
> payne-chris-r commented 4 hours ago
> You don't want to add user_id to the items table
 
And once it's added, the item can be looked up via
`current_user.pantries.find().items` ?

**Comment by ghost** [comment]
Chris, I'm going try another approach. I think I have overcomplicated things by having a pantries table as an intermediary between users and items. Now that a user can successfully create an item, a user can also create items in any other pantry not created or "owned" by them.

Will take out the pantries table and link users directly to items. I'll revisit the idea of an intermediate table for additional features later on if I ever get to that stage for this project. Thanks for the help!

**Comment by payne-chris-r** [comment]
You had it all set up correctly before. You just need to reach through the pantries table to get to items. Assigning user ID to the items table is not the right answer because a user has_many pantries and pantries has_many items. A user does not have items.

**Comment by ghost** [comment]
Chris, I decided to not give up on the 1 user to Many pantries scenario since it seems and you've mentioned that I'm pretty close to getting it resolved.

I _think_ I better understand where you were trying to point me with the need for a user to reach through the pantries table in order to create an item. 
So when an item is to be created, it needs to go: user > pantry > item. So this means:
the new item needs to be associated with a pantry via pantry id, then the pantry needs to be associated to a user via user_id. 
Previously, I had attempted to associate an item to a user somehow which totally does not work/hot mess.

Have updated how I assign @item in the create method to:
```ruby
@item = current_user.pantries.find(:id).items.build(item_params)
```

Now I get a different (but with progress) error:
```
Started POST "/items" for 127.0.0.1 at 2017-04-30 13:51:00 -0400
Processing by ItemsController#create as */*
  Parameters: {"item"=>{"item_name"=>"Bacon", "purchase_date"=>"2017-04-28", "expiry_date"=>"2017-05-02", "price"=>"0.99", "category"=>"Meat", "perishable"=>"yes", "shelf_life"=>"", "pantry_id"=>"11", "quantity"=>"42", "item_size"=>"3.5", "item_unit"=>"oz"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "88ae375f1bd92f1bd11ca1772cdc4eee"], ["LIMIT", 1]]
  Pantry Load (0.2ms)  SELECT  "pantries".* FROM "pantries" WHERE "pantries"."user_id" = $1 AND "pantries"."id" = $2 LIMIT $3  [["user_id", 1], ["id", nil], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.11ms)
Completed 404 Not Found in 16ms (Views: 2.0ms | ActiveRecord: 0.4ms)
```

The key takeaway I'm seeing is that it now knows to go through the pantries table, but unsure of which pantry specifically since "id" is nil. This is what I'm trying to resolve now.
