### ISSUE TITLE
Handlebars hitting error on page loading

### ISSUE THREAD

**Issue by donpowers** [ga-wdi-boston/full-stack-project#776]
I'm implementing handlebars and ran into this error when the page is loading the first time(not logged in yet!)

ui.js:4 Uncaught Error: Cannot find module "../templates/hive-listing.handlebars"
    at webpackMissingModule (ui.js:4)
    at Object.<anonymous> (ui.js:4)
    at Object.89 (application.js:448)
    at __webpack_require__ (bootstrap e6e79b6…:52)
    at Object.<anonymous> (events.js:7)
    at Object.85 (application.js:226)
    at __webpack_require__ (bootstrap e6e79b6…:52)
    at Object.<anonymous> (index.js:10)
    at Object.77 (application.js:51)
    at __webpack_require__ (bootstrap e6e79b6…:52)

Basically I copied what we had in the training and I uncommented the 'partial' line since it was complaining about 'partial' initially.  Google the above error but did not find any useful info.

Do we need to include any other files in the index.html to use handlebars?
 
../templates/hive-listing.handlebars is below.

{{#each hives as |hive|}}

  {{> partial}}

 
  <h1 data-id="{{hive.id}}"> <small>Name: {{hive.hive_name}}</small></h1>
  <div>
    {{#if hive.queen_type}}
      <ul>{{hive.queen_type}}</ul>
    {{else}}
      No queen.
    {{/if}}
      <li><button button-id="{{hives.id}}" type="button">Hide</button></li>
  </div>

{{/each}}

**Comment by donpowers** [comment]
The grunt serve console is showing this error:

ERROR in ./assets/scripts/templates/hive-listing.handlebars
Module build failed: Error: Partial './partial' not found
    at tryExtension (/Users/don/wdi/projects/bee-mgt-client/node_modules/handlebars-loader/index.js:256:27)
    at /Users/don/wdi/projects/bee-mgt-client/node_modules/handlebars-loader/index.js:264:11
    at next (/Users/don/wdi/projects/bee-mgt-client/node_modules/handlebars-loader/index.js:211:20)
    at /Users/don/wdi/projects/bee-mgt-client/node_modules/handlebars-loader/index.js:227:20
    at /Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/don/wdi/projects/bee-mgt-client/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Users/don/wdi/projects/bee-mgt-client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/Users/don/wdi/projects/bee-mgt-client/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
 @ ./assets/scripts/auth/ui.js 5:24-71

**Comment by cpm5041** [comment]
Hey Don, I don't think you need any additional files to use handlebars. I'm using it and haven't added anything. My suggestion would be to comment out the partial lines for now. In the training we pointed to the partial file and required it, but I'm guessing since you don't have the file to point to, it's throwing an error. I can take a look tomorrow if you're still experiencing issues!

**Comment by donpowers** [comment]
As Chris and Ryan suggested I got rid of the stuff from class and made it simple.  The loading error went away.  Probably related to the 'partial' thing which I don't need.

Thanks Guys!
