### ISSUE TITLE
Cannot access ID, Created at, or Updated at

### ISSUE THREAD

**Issue by sstone72389** [ga-wdi-boston/full-stack-project#820]
I have scaffolded my table and when testing cannot get it to log an id or created at value. 

e.g.

```js
[1] pry(main)> Task.create([{name: 'take out the trash'}])
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
=> [#<Task:0x007fd07a8e53a8
  id: nil,
  name: "take out the trash",
  is_complete: false,
  user_id: nil,
  created_at: nil,
  updated_at: nil>]
```

I believe I have properly modified the controller per the below code:

```rb
class ExamplesController < OpenReadController
  before_action :set_example, only: [:update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all

    render json: @examples
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    render json: Example.find(params[:id])
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = current_user.examples.build(example_params)

    if @example.save
      render json: @example, status: :created
    else
      render json: @example.errors, status: :unprocessable_entity
    end
  end
```

I am really not sure where to go from here. Would love a 1:1 if possible.

**Comment by jordanallain** [comment]
did you mean to post the examples controller? what does the task table look like in your schema?

**Comment by MicFin** [comment]
Does the `.create` instance method take an array of an object as its argument?
`Task.create([{name: 'take out the trash'}])`

**Comment by sstone72389** [comment]
Okay here is a repost of my controller, schema and error message.

I am running curl scripts (able to successfully login), but receive an error message stating that "method tasks is undefined."  I have seen a similar issue with Alex's project and will review. Please see the below snippets and let me know if there is anything that sticks out. I will report back after reviewing alex's issue.

controller:

```
# frozen_string_literal: true

# git clean -n, -f if this doesn't work. It is set exactly as you had it before
# the "current_user" issue

class TasksController < ApplicationController
  before_action :set_task, only: %i[show update destroy]
  before_action :validate_user, only: %i[index create update destroy set_task]

  # GET /tasks
  def index
    # view by user_id
    # @tasks = Task.all
    @tasks = current_user.tasks # .all?

    render json: @tasks
  end

  # GET /tasks/1
  def show
    render json: @task
    # render json: @task = current_user.tasks.find(params[:id])
  end

  # POST /tasks
  def create
    # get current user_id from ApplicationController
    @task = current_user.tasks.build(task_params)

    if @task.save
      render json: @task, status: :created, location: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tasks/1
  def update
    # @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      render json: @task
    else
      render json: @task.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tasks/1
  def destroy
    # may need for destroy
    # @task = current_user.tasks.find(params[:id])
    @task.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      # @task = Task.find(params[:id])
      validate_user
      @task = current_user.tasks.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:name, :is_complete, :user_id)
    end
end
```

Schema
```

ActiveRecord::Schema.define(version: 20170504190533) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "examples", force: :cascade do |t|
    t.text     "text",       null: false
    t.integer  "user_id",    null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_examples_on_user_id", using: :btree
  end

  create_table "tasks", force: :cascade do |t|
    t.text     "name",                        null: false
    t.boolean  "is_complete", default: false
    t.integer  "user_id"
    t.datetime "created_at",                  null: false
    t.datetime "updated_at",                  null: false
    t.index ["user_id"], name: "index_tasks_on_user_id", using: :btree
  end

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.index ["email"], name: "index_users_on_email", unique: true, using: :btree
    t.index ["token"], name: "index_users_on_token", unique: true, using: :btree
  end

  add_foreign_key "examples", "users"
  add_foreign_key "tasks", "users"
end
```

Server Error

```
NoMethodError (undefined method `tasks' for nil:NilClass):
  
app/controllers/tasks_controller.rb:28:in `create'
```

curl script error

```
{"status":500,"error":"Internal Server Error","exception":"#\u003cNoMethodError: undefined method `tasks' for nil:NilClass\u003e","traces":{"Application Trace":[{"id":0,"trace":"app/controllers/tasks_controller.rb:28:in `create'"}],

```

**Comment by sstone72389** [comment]
Okay, update:

I am able to get the curl request to respond with a 200

```
{"user":{"id":68,"email":"mom","token":"BAhJIiU4Y2Q1MmYxZTZlNGJiNjA3MDg0YTM5ZDIzZTk2OTQ1ZAY6BkVG--6d0f274f3cb91f2042f0741444693302eed5f937"}}
~/wdi/projects/space-out/rails-api-template/scripts (tasks-api)
$ TEXT="walk the dog" TOKEN="BAhJIiU4Y2Q1MmYxZTZlNGJiNjA3MDg0YTM5ZDIzZTk2OTQ1ZAY6BkVG--6d0f274f3cb91f2042f0741444693302eed5f937" sh create_task.sh
HTTP/1.1 201 Created
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Location: http://localhost:4741/tasks/1
Content-Type: application/json; charset=utf-8
ETag: W/"f8b2ec718e32cc76ecbea858f4846e13"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 05f1e514-810c-4cc3-9ab5-3ecc75a1baa4
X-Runtime: 0.137009
Vary: Origin
Transfer-Encoding: chunked

{"task":{"id":1,"name":"walk the dog","is_complete":false,"user":{"id":68,"email":"mom"}}}
~/wdi/projects/space-out/rails-api-template/scripts (tasks-api)
```

but when going to my local host i still see a 500 error of:

```
"status": 500,
"error": "Internal Server Error",
"exception": "#<NoMethodError: undefined method `tasks' for nil:NilClass>",
"traces": 

```

**Comment by tvcrawley** [comment]
Can you post the `task` model?

**Comment by sstone72389** [comment]
Task model:

```
class Task < ApplicationRecord
  belongs_to :user
end
```

**Comment by danman01** [comment]
When you look at your rails server output, what file and line number is the error occurring at, and what does it mean to say a method is undefined for something else?

**Comment by sstone72389** [comment]
```
app/controllers/tasks_controller.rb:14:in `index'

```

That is where i defined index as such: 

```
  def index
    # view by user_id
    # @tasks = Task.all
    @tasks = current_user.tasks # .all?

    render json: @tasks
  end
```

It is telling me that there is something wrong with my Task class it appears... hmmmmm

**Comment by danman01** [comment]
I'm not so sure it is a problem with the Task class. Is the Task class responsible for using the instance method `tasks` in this scenario?

**Comment by sstone72389** [comment]
I believe it is due to the current_user.tasks.... When I run a binding.pry on the index method, and type current_user. I get a response of nil. However, I can list all the tasks on my server if I dont call the current user using:
```
@tasks = Task.all
```

This is useless for my purposes, though, as I need it to reflect the signed in user.

**Comment by sstone72389** [comment]
any chance I can get a 1:1 for this? I am really having trouble finding the cause of this issue....

**Comment by MicFin** [comment]
You haven't defined `current_user`.  Please read this issue https://github.com/ga-wdi-boston/full-stack-project/issues/814 and consider making your controller inherit from another controller other than `ApplicationController`.

**Comment by sstone72389** [comment]
I reviewed that post last night and it appears as though my setup is very similar. Even when inheriting from OpenReadController I have the same issue. Isnt current_user being defined in application controller? I don't see why I need to re-define it....

**Comment by danman01** [comment]
Yes, `set_current_user` is defined in `ApplicationController`. However, you have to manually call that method unless you inherit from `OpenReadController` or `ProtectedController`. Check out those `before` actions in the controllers to trace the flow of how `@current_user` gets setup.

**Comment by sstone72389** [comment]
Okay, I will review this. Thank you. I will provide updates shortly.

**Comment by sstone72389** [comment]
Okay, I hope I am not being hard headed, here.... but I still can't find the answer. I cannot move forward until I get this to work.

**Comment by danman01** [comment]
Are you still getting the same error, `undefined method tasks for nil`?

**Comment by sstone72389** [comment]
Still not making much progress :(

**Comment by sstone72389** [comment]
This issue is resolved. I was testing via local host 4741 and not inheriting through the protected controller. All tests should be run via curl script to ensure functionality.
