### ISSUE TITLE
HTTP requests not working after rolling back database to version 2

### ISSUE THREAD

**Issue by nriser** [ga-wdi-boston/full-stack-project#828]
I spoke with @MicFin earlier today regarding an issue I had with reverting the database back to version 2 (where the template originally started with). 
(Issue: https://github.com/ga-wdi-boston/full-stack-project/issues/822)

Now I tried signing up/signing in and they no longer work. I expected the requests to work because I have my users table back in my database. 

Console error: 
```
POST http://localhost:4741/sign-up 500 (Internal Server Error)
```

Rails error: 
```
Started POST "/sign-in" for 127.0.0.1 at 2017-05-05 10:11:47 -0400
  ActiveRecord::SchemaMigration Load (5.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
  
ActiveRecord::PendingMigrationError (

Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=development

):
  
activerecord (5.0.1) lib/active_record/migration.rb:573:in `check_pending!'
activerecord (5.0.1) lib/active_record/migration.rb:549:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

My question is, should I run ```bin/rails db:migrate RAILS_ENV=development```? It seems like I need to migrate 001_create_users.rb and 002_create_examples.rb but my schema already consists of the users and examples tables, so I see no need to migrate again. I looked up online to see what ```bin/rails db:migrate RAILS_ENV=development``` does, but I'd like to speak with a consultant first before I run anything I'm not familiar with.

**Comment by MicFin** [comment]
Sound safe to try running `bin/rails db:migrate RAILS_ENV=development`

**Comment by nriser** [comment]
Hooray, it works now! Thank you for your help @MicFin. I ran ```bin/rails db:migrate RAILS_ENV=development``` to resolve this issue.
