### ISSUE TITLE
Receiving a 500 error while trying to POST on my API

### ISSUE THREAD

**Issue by jbeltrami** [ga-wdi-boston/full-stack-project#834]
I'm trying to post an item on my list, but I'm getting a 500 error back.

```
Started POST "/wishes" for 127.0.0.1 at 2017-05-05 13:07:25 -0400
Processing by WishesController#create as */*
  Parameters: {"wish"=>"a"}
Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `permit' for "a":String
Did you mean?  print):
  
app/controllers/wishes_controller.rb:49:in `wish_params'
app/controllers/wishes_controller.rb:18:in `create'
```

I have a form to pass the info to the API:
```html
      <form id="create-wish">
        <div class="add-wish-screen">
          <input name="wish" type="text" placeholder="Make a wish" class="form-control">
          <input type="submit" class="btn btn-default create-wish-button" value="Add wish">
        </div>
      </form>
```
 the API is expecting a string as a wish:
```
  create_table "wishes", force: :cascade do |t|
    t.integer  "user_id"
    t.string   "wish",       null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_wishes_on_user_id", using: :btree
  end
```

The event is created:
```js
const onCreateWish = function (event) {
  const data = getFormFields(event.target)
  event.preventDefault()
  api.createWish(data)
    .then(ui.createWishSuccess)
    .catch(ui.createWishFailure)
}


$('#create-wish').on('submit', onCreateWish)
```
The AJAX is also created:
```js
const createWish = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/wishes',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```

I'm not really sure of what is wrong or what to do next.

**Comment by jordanallain** [comment]
can you post the controller for wishes?

**Comment by jbeltrami** [comment]
This is my controller as of now:
```rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :update, :destroy]

  # GET /wishes
  def index
    @wishes = Wish.all

    render json: @wishes
  end

  # GET /wishes/1
  def show
    render json: @wish
  end

  # POST /wishes
  def create
    @wish = Wish.new(wish_params)

    if @wish.save
      render json: @wish, status: :created, location: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /wishes/1
  def update
    if @wish.update(wish_params)
      render json: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # DELETE /wishes/1
  def destroy
    @wish.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wish_params
      params.require(:wish).permit(:user_id, :wish)
    end
end
```

**Comment by jordanallain** [comment]
i would check out the examples controller's create method and compare it to the one in this controller.

**Comment by jbeltrami** [comment]
Thanks for the tip. I did that and also checked another issue that someone opened before (https://github.com/ga-wdi-boston/full-stack-project/issues/814). This helped to clarify a little bit.

Now my controller looks like this:
```rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :update, :destroy]
  before_action :validate_user

  # GET /wishes
  def index
    @wishes = Wish.all

    render json: @wishes
  end

  # GET /wishes/1
  def show
    render json: @wish
  end

  # POST /wishes
  def create
    @wish = current_user.wishes.build(wish_params)

    if @wish.save
      render json: @wish, status: :created, location: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /wishes/1
  def update
    if @wish.update(wish_params)
      render json: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # DELETE /wishes/1
  def destroy
    @wish.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      # @wish = Wish.find(params[:id])
      validate_user
      @item = current_user.items.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def wish_params
      params.require(:wish).permit(:user_id, :wish)
    end
end
```

It is authenticating the user when I try to POST, but I'm still getting a 500 error:
```
Started POST "/wishes" for 127.0.0.1 at 2017-05-05 14:10:47 -0400
Processing by WishesController#create as */*
  Parameters: {"wish"=>"asdasd"}
  User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "cb4f5281efcc7c16d5944c8e0f8fe8a6"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 104ms (ActiveRecord: 48.7ms)


  
NoMethodError (undefined method `permit' for "asdasd":String
Did you mean?  print):
  
app/controllers/wishes_controller.rb:56:in `wish_params'
app/controllers/wishes_controller.rb:19:in `create'
```

**Comment by danman01** [comment]
Look at the params incoming from your form:
```
<form id="create-wish">
        <div class="add-wish-screen">
          <input name="wish" type="text" placeholder="Make a wish" class="form-control">
          <input type="submit" class="btn btn-default create-wish-button" value="Add wish">
        </div>
      </form>
```
How could you structure your params so that the rails method in your controller accesses the params correctly? Try using `binding.pry` in your controller to investigate what is in params.

**Comment by jbeltrami** [comment]
I'm still stuck.
I realized that my table and my column had the same name. So I created a new migration file to change the column name:
```rb
class ChangesColumnName < ActiveRecord::Migration[5.0]
  def change
    rename_column :wishes, :wish, :goal
  end
end
```

That worked, but I'm still not being able to POST on my API.
This is what I have now:
Schema:
```
  create_table "wishes", force: :cascade do |t|
    t.integer  "user_id"
    t.string   "goal",       null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_wishes_on_user_id", using: :btree
  end
```

- Controller:
```rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :update, :destroy]
  before_action :validate_user

  # GET /wishes
  def index
    @wishes = Wish.all

    render json: @wishes
  end

  # GET /wishes/1
  def show
    render json: @wish
  end

  # POST /wishes
  def create
    # require 'pry'
    # binding.pry
    @wish = current_user.wishes.build(wish_params)
    if @wish.save
      render json: @wish, status: :created, location: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /wishes/1
  def update
    if @wish.update(wish_params)
      render json: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # DELETE /wishes/1
  def destroy
    @wish.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      # @wish = Wish.find(params[:id])
      validate_user
      @wish = current_user.wishes.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def wish_params
      params.require(:wish).permit(:goal)
    end
end
```

HTML:
```html
      <form id="create-wish">
        <div class="add-wish-screen">
          <input name="goal" type="text" placeholder="Make a wish" class="form-control">
          <input type="submit" class="btn btn-default create-wish-button" value="Add wish">
        </div>
      </form>
```

**Comment by tvcrawley** [comment]
How does your form data compare to curl script data? What are you passing in in both cases and **how** (or what format) is the data being passed?

**Comment by danman01** [comment]
To add to what Toni mentioned, use `binding.pry` to see how the data is hitting your controller action in your curl script vs your form submission, and what the value of `params` is.

**Comment by MicFin** [comment]
Review how you need to set up the HTML for the `getFormFields` method to work. It relies on a `name` attribute being a certain value.
`<input name="goal" type="text" placeholder="Make a wish" class="form-control">`
That is not correct.  `name="goal"` is not the correct format.
https://git.generalassemb.ly/ga-wdi-boston/jquery-ajax-post/blob/master/index.html#L42

**Comment by jbeltrami** [comment]
So, I tried fixing all that and this is how it looks like right now.
Controller:
```rb
class WishesController < ApplicationController
  before_action :set_wish, only: %i[show update destroy]
  before_action :validate_user

  # GET /wishes
  def index
    @wishes = Wish.all

    render json: @wishes
  end

  # GET /wishes/1
  def show
    render json: @wish
  end

  # POST /wishes
  def create
    require 'pry'
    binding.pry
    @wish = current_user.wishes.build(wish_params)
      @wish.valid?
    if @wish.save
      render json: @wish, status: :created, location: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /wishes/1
  def update
    if @wish.update(wish_params)
      render json: @wish
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end

  # DELETE /wishes/1
  def destroy
    @wish.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      # @wish = Wish.find(params[:id])
      validate_user
      @wish = current_user.wishes.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def wish_params
      params.require(:wish).permit(:goal)
    end
end
```

HTML Input:
```html
      <form id="create-wish">
        <div class="add-wish-screen">
          <input name="wish[goal]" type="text" placeholder="Make a wish" class="form-control">
          <input type="submit" class="btn btn-default create-wish-button" value="Add wish">
        </div>
      </form>
```

Curl request:
```sh
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/wishes"
curl "${API}${URL_PATH}" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=$TOKEN" \
  --data '{
    "wish": {
      "goal": "'"${TEXT}"'"
    }
  }'

echo

```

Whats is interesting is that in PRY I can create and save the new instance by typing the commands, but for some reason it is not doing it automatically through the browser.

I'm still getting the 500 error:
```
Completed 500 Internal Server Error in 336510ms (ActiveRecord: 40.0ms)


  
NoMethodError (undefined method `wish' for #<Wish:0x007faee4c18398>):
  
app/controllers/wishes_controller.rb:24:in `create'
```

**Comment by MicFin** [comment]
What is line 24 in `wishes_controller.rb`?

**Comment by jbeltrami** [comment]
```rb
      render json: @wish, status: :created, location: @wish
```

**Comment by MicFin** [comment]
Make it look more like this and see if that helps.
https://git.generalassemb.ly/ga-wdi-boston/rails-api-library-demo/blob/master/app/controllers/examples_controller.rb#L25

**Comment by MicFin** [comment]
After that, I would add some `binding.pry` and see what data you have passing around.
```rb
  def create
    require 'pry'
    binding.pry # what is params? what is wish_params?
    @wish = current_user.wishes.build(wish_params)
    binding.pry # what is @wish? 
    if @wish.save
      binding.pry # what is @wish now?  Did it save?  Does it have an ID?
      render json: @wish, status: :created
    else
      render json: @wish.errors, status: :unprocessable_entity
    end
  end
```

**Comment by MicFin** [comment]
And after that, what does your `WishSerializer` look like?

**Comment by jbeltrami** [comment]
Thanks for all the help.
The last link of the chain was the `WishSerializer`. It still had my previous table column name as an attribute.
It is working properly now.
