### ISSUE TITLE
Getting a 500 error on post

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/full-stack-project#864]
was getting a 404 error but now getting a 500 saying undefined method 'locations'?

```
Started POST "/create-location" for 127.0.0.1 at 2017-05-08 12:07:15 -0400
Processing by LocationsController#create as */*
  Parameters: {"location"=>{"city"=>"bhuj", "country"=>"nbj", "comment"=>"nbi", "zipcode"=>"98"}, "submit"=>"Submit"}
Completed 500 Internal Server Error in 68ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `locations' for nil:NilClass):
  
app/controllers/locations_controller.rb:18:in `create'
```

**Comment by eliottenos** [comment]
this is my controller:
```rb
def create
    @location = current_user.locations.build(location_params)

    if @location.save
      render json: @location, status: :created
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end
```

**Comment by jordanallain** [comment]
did rails have any errors?

**Comment by jordanallain** [comment]
can you post the whole controller.

**Comment by eliottenos** [comment]
Rails said the above
```rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all

    render json: @locations
  end

  # GET /locations/1
  def show
    render json: Location.find(params[:id])
  end

  # POST /locations
  def create
    @location = current_user.locations.build(location_params)

    if @location.save
      render json: @location, status: :created
      # render json: @location, status: :created, location: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      render json: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = current_user.locations.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:city, :country, :comment, :zipcode, :user_id)
    end
end
```

**Comment by eliottenos** [comment]
Im getting this in the console now so its not even hitting the api
![screen shot 2017-05-08 at 14 07 04](https://cloud.githubusercontent.com/assets/26254104/25818190/caea775a-33f7-11e7-90c6-9fd10cb4b00c.png)

**Comment by jordanallain** [comment]
so there must be a problem in your ajax call with how you are using `token`

**Comment by eliottenos** [comment]
heres my api
```js
const createLocation = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/create-location',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const deleteLocation = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/update-location',
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const updateLocation = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/delete-location',
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}

const weather = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/weather/',
    method: 'GET',
    data
    // data: data
  })
}
```

**Comment by eliottenos** [comment]
ok, now back to 500 internal server error

rails says undefined method 'locations'

**Comment by tvcrawley** [comment]
One problem at a time: this issue stems from an api issue:
`NoMethodError (undefined method locations for nil:NilClass)`

If you don't have access to `locations`, then something is wrong with `current_user`. Does this controller know what `current_user` is?

[Also, you may want to review Mike's answer to this.](https://github.com/ga-wdi-boston/full-stack-project/issues/814)

**Comment by eliottenos** [comment]
as far as I can see controller should know what current_user is?
```rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :update, :destroy]
  before_action :validate_user, only: [:index, :create, :update, :destroy, :set_location]

  # GET /locations
  def index
    @locations = Location.all

    render json: @locations
  end

  # GET /locations/1
  def show
    render json: Location.find(params[:id])
  end

  # POST /locations
  def create
    @location = current_user.locations.build(location_params)

    if @location.save
      render json: @location, status: :created, location: @location
      # render json: @location, status: :created, location: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      render json: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      validate_user
      @location = current_user.locations.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:city, :country, :comment, :zipcode, :user_id)
    end
end
```

**Comment by tvcrawley** [comment]
This is different from what was posted before. If an error is still occurring, can you paste in the error from the **rails server** as well as from the **terminal** after running a curl request.

**Comment by eliottenos** [comment]
rails server
```
app/controllers/locations_controller.rb:19:in `create'
Started POST "/create-location" for 127.0.0.1 at 2017-05-08 14:49:16 -0400
Processing by LocationsController#create as */*
  Parameters: {"location"=>{"city"=>"ugb", "country"=>"uhj", "comment"=>"jb", "zipcode"=>"767"}, "submit"=>"Submit"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)


  
NoMethodError (undefined method `locations' for nil:NilClass):
```
terminal is not showing an error?
console error is this...
![screen shot 2017-05-08 at 15 15 50](https://cloud.githubusercontent.com/assets/26254104/25820986/481e3ee2-3401-11e7-94ea-ef9ee64c975b.png)

**Comment by jordanallain** [comment]
how about the rails logs?

**Comment by eliottenos** [comment]
I can now post! but still not update or delete so will open a new issue
problem was with my api calls clientside
```js
onst createLocation = (data) => {
  return $.ajax({
    url: config.apiOrigin + '/create-location',
    method: 'POST',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data: data
  })
}
```
