### ISSUE TITLE
getting 404 not found for PATCH and DELETE

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/full-stack-project#870]
similar issue to my last https://github.com/ga-wdi-boston/full-stack-project/issues/864
Can post new locations now but not update or delete
server:
```
ActionController::RoutingError (No route matches [DELETE] "/update-location"):
  
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
puma (3.7.0) lib/puma/configuration.rb:226:in `call'
puma (3.7.0) lib/puma/server.rb:578:in `handle_request'
puma (3.7.0) lib/puma/server.rb:415:in `process_client'
puma (3.7.0) lib/puma/server.rb:275:in `block in run'
puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by jordanallain** [comment]
> ActionController::RoutingError (No route matches [DELETE] "/update-location"):

seems like an issue

**Comment by eliottenos** [comment]
new error!
```
Started DELETE "/delete-location" for 127.0.0.1 at 2017-05-08 15:35:20 -0400
  
AbstractController::ActionNotFound (The action 'delete' could not be found for LocationsController):
```

**Comment by jordanallain** [comment]
> AbstractController::ActionNotFound (The action 'delete' could not be found for LocationsController):

Are you reading your errors?

**Comment by eliottenos** [comment]
new error!
```
Started DELETE "/destroy-location" for 127.0.0.1 at 2017-05-08 15:37:31 -0400
  
ActionController::RoutingError (No route matches [DELETE] "/destroy-location")
```

**Comment by jordanallain** [comment]
follow the errors padawan

**Comment by eliottenos** [comment]
ever evolving errors
```
Started DELETE "/destroy-location" for 127.0.0.1 at 2017-05-08 15:37:31 -0400
  
ActionController::RoutingError (No route matches [DELETE] "/destroy-location")
```

**Comment by eliottenos** [comment]
middle me this...no errors showing on server but 404 in console?
```
Started DELETE "/destroy-location" for 127.0.0.1 at 2017-05-08 15:46:00 -0400
Processing by LocationsController#destroy as */*
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "d492ccff7aff95e4b8b33cb962d54aff"], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.16ms)
Completed 404 Not Found in 8ms (Views: 1.5ms | ActiveRecord: 0.6ms)
```

**Comment by jordanallain** [comment]
what are you deleting?

**Comment by eliottenos** [comment]
'boston' from 'locations'
```
{
"id": 3,
"city": "boston",
"country": "usa",
"comment": "a place",
"zipcode": 1944,
"user": {
"id": 2,
"email": "hi@hi.com"
}
}
]
}
```

**Comment by jordanallain** [comment]
was it created by the user that was signed in?

**Comment by eliottenos** [comment]
yep

**Comment by jordanallain** [comment]
can you post the appropriate route and controller method?

**Comment by eliottenos** [comment]
here are my routes
```rb
Rails.application.routes.draw do
  resources :locations
  resources :examples, except: [:new, :edit, :destroy]
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out/:id' => 'users#signout'
  patch '/change-password/:id' => 'users#changepw'
  post '/create-location' => 'locations#create'
  patch '/update-location' => 'locations#update'
  delete '/destroy-location' => 'locations#destroy'
  resources :users, only: [:index, :show]
end
```
and controller
```rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :update, :destroy]
  before_action :validate_user, only: [:index, :create, :update, :destroy, :set_location]

  # GET /locations
  def index
    @locations = Location.all

    render json: @locations
  end

  # GET /locations/1
  def show
    render json: Location.find(params[:id])
  end

  # POST /locations
  def create
    @location = current_user.locations.build(location_params)

    if @location.save
      render json: @location, status: :created, location: @location
      # render json: @location, status: :created, location: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      render json: @location
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      validate_user
      @location = current_user.locations.find(params[:id])
    end

    def validate_user
      set_current_user
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:city, :country, :comment, :zipcode, :user_id)
    end
end
```

**Comment by jordanallain** [comment]
does this pattern from your controller action:

> DELETE /locations/1

match the url you are trying to hit in the route?

> delete '/destroy-location' => 'locations#destroy'

**Comment by eliottenos** [comment]
with ```delete '/destroy-location' => 'locations#destroy'``` the server gives me:
```
Started DELETE "/destroy-location" for 127.0.0.1 at 2017-05-09 09:14:05 -0400
Processing by LocationsController#destroy as */*
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "8f7a48e98f800fd9241761158cfb0e8d"], ["LIMIT", 1]]
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.09ms)
Completed 404 Not Found in 5ms (Views: 0.8ms | ActiveRecord: 0.4ms)
```

I tried ```delete '/destroy-locations/1' => 'locations#destroy'```to match the controller?  But it doesn't hit the server

**Comment by jordanallain** [comment]
look at the routes we did in class, how did we specify an id?

**Comment by jordanallain** [comment]
or even in your other routes in the file for sign-out and change-password, those are routes that also require an id

**Comment by eliottenos** [comment]
so I need to integrate an id into destroy route? similar to this...
```
def signout
    if current_user == User.find(params[:id])
      current_user.logout
      head :no_content
    else
      head :unauthorized
    end
  end
```

**Comment by jordanallain** [comment]
that's the method not the route. this is the route

`delete '/sign-out/:id' => 'users#signout'`

so make sure your new delete route looks something like that and you can use the signout method to see how we specify in the action where to grab the id

**Comment by eliottenos** [comment]
ok Ive changed my controller to 
```rb
def destroy
    @location = current_user.locations.delete(location_params)

    if @location.destroy
      render json: @location, status: :destroyed
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end
```
and getting back a different error after running the curl script
```
HTTP/1.1 404 Not Found
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 6ef1e0ab-a8cc-4e2d-aaad-c3702517d330
X-Runtime: 0.007422
Vary: Origin
Transfer-Encoding: chunked

{"error":{"message":"Not Found"}}~/documents/eliott-rails-api (locations)
```

**Comment by eliottenos** [comment]
this was my curl script:
```
API="${API_ORIGIN:-http://localhost:4741}"
URL_PATH="/destroy-location/:8"
curl "${API}${URL_PATH}" \
  --include \
  --request DELETE \
  --header "Content-Type: application/json" \
  --header "Authorization: Token token=BAhJIiU5ZTRhYmY4NjE1NTNkMzJjYTQzYjRhMTQwMTMxZDI5MAY6BkVG--98e577e641ad94a292cfc450d980467644b892fd" \
  --data '{
    "location": {
      "city": "'"flor"'"
    }
  }'
```

**Comment by jordanallain** [comment]
you don't want the colon in when you are passing the actual id, you only have `:id` in the route as a stand in

**Comment by eliottenos** [comment]
ah ok, getting a 500 back now

**Comment by eliottenos** [comment]
resolved
amended controller method to:
```rb
def destroy
    
    @location.destroy
    if @location.destroy
   
      head :no_content
    else
      render json: @location.errors, status: :unprocessable_entity
    end
  end
```
as params already defined
