### ISSUE TITLE
Existing Functionality Not Working Upon Code Revision - 500 Internal Server Error

### ISSUE THREAD

**Issue by glasneed** [ga-wdi-boston/full-stack-project#895]
The working version of my project that was submitted last week now has a new bug in it that I cannot resolve and did not exist last week on first submission. This bug occurred while fixing other code based on feedback for resubmission.

The bug only occurs in production. It does not occur on localhost. The bug is that I am unable to return the (previously functioning) GET request to return ALL items in my ToDo list. I did not change my API calls for this resubmission. A CURL request to production server doesn't work either and can generate the same 500 error.

Also, all other CRUD items work perfectly fine in both localhost and on the production (heroku) version as they did last week.

Here is the error when I click on the GET ITEMS button
 
![screen shot 2017-05-09 at 11 11 38 pm](https://cloud.githubusercontent.com/assets/26227953/25882069/cdd452b6-350e-11e7-887a-38915cf4b1e7.png)

I recycled the Heroku server but it had no impact. I've made no changes to my Controller on my server side code for this resubmit. And I can successfully return data for a GET request for a passed in ID on the front end. It is only the GET for ALL records that chokes.

**Comment by payne-chris-r** [comment]
What's the error in the logs?
Have you tried curl? Same thing?

**Comment by glasneed** [comment]
Chris -
I can answer one of your questions so far as I ran Curl last night and got the same 500 error. Here is it's output.  I checked the Heroku site and didn't see a log directory but I'll google it when I get in.

Here is the curl input and output.


Thanks

``` conor@LIBP45P-10984DY ~/wdi/projects/chores-server (master) $   curl --include --request GET https://dry-hollows-40181.herokuapp.com/chores \
>     --header "Content-Type: application/json" \
>     --header "Authorization: Token token=BAhJIiUzMWZiN2M0ZWVmNmUxYWE5MTYyZWNiYmEyMmJiMTkzMgY6BkVG--adb3d8089e1f390eb0589d1f9200b5ce5cad7a72" \
> 
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Date: Wed, 10 May 2017 12:29:26 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
X-Request-Id: 881c6e8d-5c75-474b-9ee8-49048e9ae448
X-Runtime: 0.032779
Vary: Origin
Content-Length: 46
Via: 1.1 vegur

{"status":500,"error":"Internal Server Error"}conor@LIBP45P-10984DY ~/wdi/projects/chores-server (master) $ 
```

**Comment by glasneed** [comment]
Here is the heroku log output:

``` 2017-05-10T12:29:27.482128+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448]   Chore Load (0.8ms)  SELECT "chores".* FROM "chores" WHERE "chores"."user_id" = $1  [["user_id", 1]]
2017-05-10T12:29:27.495932+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (3.09ms)
2017-05-10T12:29:27.496189+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] Completed 500 Internal Server Error in 30ms (ActiveRecord: 4.3ms)
2017-05-10T12:29:27.496999+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448]   
2017-05-10T12:29:27.497046+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] NoMethodError (undefined method `-' for nil:NilClass):
2017-05-10T12:29:27.466070+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] Processing by ChoresController#index as */*
2017-05-10T12:29:27.497081+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] app/serializers/chore_serializer.rb:10:in `days_to_due_date'
2017-05-10T12:29:27.497078+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448]   
2017-05-10T12:29:27.497082+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] app/controllers/chores_controller.rb:12:in `index'
2017-05-10T13:01:54.941181+00:00 heroku[web.1]: Idling
2017-05-10T13:01:54.941745+00:00 heroku[web.1]: State changed from up to down
```
Could I please meet somebody at workshop time later today to discuss this issue as I'm confused how it works in localhost but not in production? 

Thank you.

Conor

**Comment by jordanallain** [comment]
looks like your problem is 
> NoMethodError (undefined method `-' for nil:NilClass): 

do you have a dash somewhere in your code by mistake?

**Comment by jordanallain** [comment]
likely in the chores controller

**Comment by danman01** [comment]
I think as we talked about, this is a data difference issue. Prod and development data is different and can bring out some bugs.

Take a look at the stack trace and drill down to the file, method and line number, then see what you can figure out:
```
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (3.09ms)
2017-05-10T12:29:27.496189+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] Completed 500 Internal Server Error in 30ms (ActiveRecord: 4.3ms)
2017-05-10T12:29:27.496999+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448]   
2017-05-10T12:29:27.497046+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] NoMethodError (undefined method `-' for nil:NilClass):
2017-05-10T12:29:27.466070+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] Processing by ChoresController#index as */*
2017-05-10T12:29:27.497081+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] app/serializers/chore_serializer.rb:10:in `days_to_due_date'
2017-05-10T12:29:27.497078+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448]   
2017-05-10T12:29:27.497082+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] app/controllers/chores_controller.rb:12:in `index'
```

**Comment by glasneed** [comment]
Thanks Jordan and Danny for your input. I'll look at this during workshop today. Different data in prod v development makes a lot of sense. I'll look into that next.

**Comment by glasneed** [comment]
Danny - You were correct! It was caused by 'bad' data injected into the production table via CURL requests. I cleared out the chores table and did a bunch of new inserts and it is working as before.

As for you question to look at the above stack trace, I couldn't see how this would have pointed me to this answer. It talked about undefined method ''-' which was incorrect as I didn't change my Chores controller for this revision. It was the same code as my initial version. 
Was there something in there that would have pointed me to questioning the integrity of the data in prod.

Thank you very much for your help!

Conor

**Comment by danman01** [comment]
Nice work!

```
2017-05-10T12:29:27.497046+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] NoMethodError (undefined method `-' for nil:NilClass):
2017-05-10T12:29:27.466070+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] Processing by ChoresController#index as */*
2017-05-10T12:29:27.497081+00:00 app[web.1]: [881c6e8d-5c75-474b-9ee8-49048e9ae448] app/serializers/chore_serializer.rb:10:in `days_to_due_date'
```
leads me to believe `days_to_due_date` is doing some calculation with the minus sign...is that a custom method and do you need a condition to check for certain values, like `nil`?

**Comment by glasneed** [comment]
Yes, ``` days_to_due_date ``` is a custom method in my serializer code. However, this field will no longer be nullable due to the change I had to implement for my revision as I ensure that due_date can no longer be null, even with a CURL script. 

Thank you
