### ISSUE TITLE
i m trying to use  handlebar for index of cars getting an eror

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/full-stack-project#914]
````
Object {cars: Array(2)}cars: Array(2)__proto__: Object "success" Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
ui.js:63 undefined
jquery.js:3860 jQuery.Deferred exception: Cannot read property 'cars' of undefined TypeError: Cannot read property 'cars' of undefined
    at getAllCarsSuccess (http://localhost:7165/public/application.js:561:52)
    at mightThrow (http://localhost:7165/public/vendor.js:11500:30)
    at process (http://localhost:7165/public/vendor.js:11568:13) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655
jquery.js:3649 [Violation] 'setTimeout' handler took 51874ms
ui.js:69 TypeError: Cannot read property 'cars' of undefined
    at getAllCarsSuccess (ui.js:64)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
```
THIS IS MY CODE FOR HANDLE BARS


{{#each cars as |car|}}

<!--we are using data id and not id -->
<ul data-id="{{car.id}}">
  <li><small>Model:{{car.model}}</small></li>
  <li><small>Color-of-car:{{car.color}}</small></li>
  <li><small>licence-plate-no:{{car.lcp}}</small></li>
  <li><small>Repair-needed:{{car.repair}}</small></li>
</ul>
{{/each}}

**Comment by isharma-sharma** [comment]
I M USING IYT IN MY sucesscar

const getAllCarsSuccess = (data) => {
  console.log(data)
  let showcarsHtml = showCarsTemplate({ cars: data.cars })
  $('#alcr').append(showcarsHtml)
}

**Comment by jordanallain** [comment]
you need to set a variable to require the path to your handlebars template

**Comment by isharma-sharma** [comment]
this is the path which I mentioned on my ui

const showCarsTemplate = require('../templates/car-listing.handlebars')

**Comment by jordanallain** [comment]
ui.js:69 TypeError: Cannot read property 'cars' of undefined

it appears to not know what `cars` is on line 69 in your ui file.

**Comment by isharma-sharma** [comment]
this is line 69 

  const showcarsHtml = showCarsTemplate({ cars: data.cars })

**Comment by jordanallain** [comment]
`ui.js:63 undefined`

what about line 63? is it possible the data you are getting back isn't what you think it is?
