### ISSUE TITLE
my update is shown when i sign-in again

### ISSUE THREAD

**Issue by isharma-sharma** [ga-wdi-boston/full-stack-project#919]
my api for update
```js
const updateCarInfo = function (id, data) {
  console.log('inside updateGame repair is ', data)
  return $.ajax({
    url: config.apiOrigin + '/cars/' + id,
    method: 'PATCH',
    headers: {
      Authorization: 'Token token=' + store.userToken
    },
    data
  })
    .then((response) => {
      $("ul[data-id='" + data + "']").update(data)
    })
}

const onUpdateCar = function (event) {
  event.preventDefault()
  console.log('is handler working')
  const data = getFormFields(event.target)
  const id = $(event.target).parent().parent().attr('data-id')
  console.log(id, data)
  api.updateCarInfo(id, data)
  .then(ui.onUpdateCarSuccess)
.catch(ui.onUpdateCarfailure)
}
```
and the error on console
```js
jquery.js:3583 Object {userToken: "BAhJIiU3YTg4ZWQ1YTczODJmMjcwMGZiZWEzOTc2ZWM0MjFlNQY6BkVG--ed4c8cfeff5853d963b0eb6e5f5df0bbd306c06f", userId: 3}
jquery.js:5009 [Violation] 'click' handler took 1582ms
ui.js:55 Object {cars: Array(3)}
event.js:56 is handler working
event.js:59 20 Object {car: Object}
api.js:75 inside updateGame repair is  Object {car: Object}
jquery.js:5009 [Violation] 'submit' handler took 3748ms
3jquery.js:3860 jQuery.Deferred exception: $(...).update is not a function TypeError: $(...).update is not a function
    at Object.<anonymous> (http://localhost:7165/public/application.js:1730:38)
    at mightThrow (http://localhost:7165/public/vendor.js:11500:30)
    at process (http://localhost:7165/public/vendor.js:11568:13) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3860
process @ jquery.js:3655

**Comment by MicFin** [comment]
What are you trying to do with this line of code `$("ul[data-id='" + data + "']").update(data)`?

**Comment by isharma-sharma** [comment]
the data i m  giving will be update by this

**Comment by isharma-sharma** [comment]
is this wrong

**Comment by scottyscripts** [comment]
What are you expecting `.update` to do? Take a look at your error message especially the line ```3jquery.js:3860 jQuery.Deferred exception: $(...).update is not a function TypeError: $(...).update is not a function```
Is the actual issue here that update isn't working?

**Comment by isharma-sharma** [comment]
is this line
```
$("ul[data-id='" + data + "']").update(data) 

is wrong it is just same as of my remove 
$("ul[data-id='" + data + "']").remove()

**Comment by isharma-sharma** [comment]
i just wrote the line because i saw it in google 
```
element.update( newContent );
``
is this wrong

**Comment by isharma-sharma** [comment]
have to right this 
$("ul[data-id='" + id + "']").find('.rep').text(response.car.repair)
